-- Logs begin at Tue 2022-07-26 03:07:45 IST, end at Tue 2022-07-26 03:09:03 IST. --
Jul 26 03:07:46 datacore-PowerEdge-R740 sudo[2676917]: pam_unix(sudo:session): session closed for user root
Jul 26 03:07:46 datacore-PowerEdge-R740 cinder-volume[2676807]: DEBUG oslo_concurrency.processutils [None req-90392122-610e-4cd4-a1ce-813deb2d8974 None None] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C pvs --noheadings --unit=g -o vg_name,name,size,free --separator | --nosuffix --ignoreskippedcluster" returned: 0 in 1.069s {{(pid=2676807) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Jul 26 03:07:46 datacore-PowerEdge-R740 cinder-volume[2676807]: DEBUG oslo_concurrency.processutils [None req-90392122-610e-4cd4-a1ce-813deb2d8974 None None] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix stack-volumes-lvmdriver-1 {{(pid=2676807) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Jul 26 03:07:46 datacore-PowerEdge-R740 sudo[2676964]:    stack : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/local/bin/cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix stack-volumes-lvmdriver-1
Jul 26 03:07:46 datacore-PowerEdge-R740 sudo[2676964]: pam_unix(sudo:session): session opened for user root by (uid=0)
Jul 26 03:07:47 datacore-PowerEdge-R740 sudo[2676964]: pam_unix(sudo:session): session closed for user root
Jul 26 03:07:47 datacore-PowerEdge-R740 cinder-volume[2676807]: DEBUG oslo_concurrency.processutils [None req-90392122-610e-4cd4-a1ce-813deb2d8974 None None] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix stack-volumes-lvmdriver-1" returned: 0 in 0.827s {{(pid=2676807) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Jul 26 03:07:47 datacore-PowerEdge-R740 cinder-volume[2676807]: DEBUG oslo_concurrency.processutils [None req-90392122-610e-4cd4-a1ce-813deb2d8974 None None] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix stack-volumes-lvmdriver-1 {{(pid=2676807) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Jul 26 03:07:47 datacore-PowerEdge-R740 sudo[2677180]:    stack : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/local/bin/cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix stack-volumes-lvmdriver-1
Jul 26 03:07:47 datacore-PowerEdge-R740 sudo[2677180]: pam_unix(sudo:session): session opened for user root by (uid=0)
Jul 26 03:07:47 datacore-PowerEdge-R740 sudo[2677180]: pam_unix(sudo:session): session closed for user root
Jul 26 03:07:47 datacore-PowerEdge-R740 cinder-volume[2676807]: DEBUG oslo_concurrency.processutils [None req-90392122-610e-4cd4-a1ce-813deb2d8974 None None] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix stack-volumes-lvmdriver-1" returned: 0 in 0.678s {{(pid=2676807) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Jul 26 03:07:47 datacore-PowerEdge-R740 cinder-volume[2676807]: DEBUG oslo_concurrency.processutils [None req-90392122-610e-4cd4-a1ce-813deb2d8974 None None] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1 {{(pid=2676807) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Jul 26 03:07:47 datacore-PowerEdge-R740 sudo[2677209]:    stack : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/local/bin/cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1
Jul 26 03:07:47 datacore-PowerEdge-R740 sudo[2677209]: pam_unix(sudo:session): session opened for user root by (uid=0)
Jul 26 03:07:48 datacore-PowerEdge-R740 sudo[2677209]: pam_unix(sudo:session): session closed for user root
Jul 26 03:07:48 datacore-PowerEdge-R740 cinder-volume[2676807]: DEBUG oslo_concurrency.processutils [None req-90392122-610e-4cd4-a1ce-813deb2d8974 None None] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1" returned: 0 in 0.661s {{(pid=2676807) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Jul 26 03:07:48 datacore-PowerEdge-R740 cinder-volume[2676807]: DEBUG oslo_concurrency.processutils [None req-90392122-610e-4cd4-a1ce-813deb2d8974 None None] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o size,data_percent --separator : --nosuffix /dev/stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool {{(pid=2676807) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Jul 26 03:07:48 datacore-PowerEdge-R740 sudo[2677239]:    stack : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/local/bin/cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o size,data_percent --separator : --nosuffix /dev/stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool
Jul 26 03:07:48 datacore-PowerEdge-R740 sudo[2677239]: pam_unix(sudo:session): session opened for user root by (uid=0)
Jul 26 03:07:49 datacore-PowerEdge-R740 sudo[2677239]: pam_unix(sudo:session): session closed for user root
Jul 26 03:07:49 datacore-PowerEdge-R740 cinder-volume[2676807]: DEBUG oslo_concurrency.processutils [None req-90392122-610e-4cd4-a1ce-813deb2d8974 None None] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o size,data_percent --separator : --nosuffix /dev/stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool" returned: 0 in 0.660s {{(pid=2676807) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Jul 26 03:07:49 datacore-PowerEdge-R740 cinder-volume[2676807]: DEBUG oslo_concurrency.processutils [None req-90392122-610e-4cd4-a1ce-813deb2d8974 None None] Running cmd (subprocess): env LC_ALL=C lvm version {{(pid=2676807) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Jul 26 03:07:49 datacore-PowerEdge-R740 cinder-volume[2676807]: DEBUG oslo_concurrency.processutils [None req-90392122-610e-4cd4-a1ce-813deb2d8974 None None] CMD "env LC_ALL=C lvm version" returned: 0 in 0.016s {{(pid=2676807) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Jul 26 03:07:49 datacore-PowerEdge-R740 cinder-volume[2676807]: DEBUG oslo_concurrency.processutils [None req-90392122-610e-4cd4-a1ce-813deb2d8974 None None] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool {{(pid=2676807) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Jul 26 03:07:49 datacore-PowerEdge-R740 sudo[2677247]:    stack : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/local/bin/cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool
Jul 26 03:07:49 datacore-PowerEdge-R740 sudo[2677247]: pam_unix(sudo:session): session opened for user root by (uid=0)
Jul 26 03:07:49 datacore-PowerEdge-R740 sudo[2677247]: pam_unix(sudo:session): session closed for user root
Jul 26 03:07:49 datacore-PowerEdge-R740 cinder-volume[2676807]: DEBUG oslo_concurrency.processutils [None req-90392122-610e-4cd4-a1ce-813deb2d8974 None None] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool" returned: 0 in 0.712s {{(pid=2676807) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Jul 26 03:07:49 datacore-PowerEdge-R740 cinder-volume[2676807]: INFO cinder.volume.drivers.lvm [None req-90392122-610e-4cd4-a1ce-813deb2d8974 None None] Enabling LVM thin provisioning by default because a thin pool exists.
Jul 26 03:07:49 datacore-PowerEdge-R740 cinder-volume[2676807]: DEBUG oslo_concurrency.processutils [None req-90392122-610e-4cd4-a1ce-813deb2d8974 None None] Running cmd (subprocess): env LC_ALL=C lvm version {{(pid=2676807) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Jul 26 03:07:49 datacore-PowerEdge-R740 cinder-volume[2676807]: DEBUG oslo_concurrency.processutils [None req-90392122-610e-4cd4-a1ce-813deb2d8974 None None] CMD "env LC_ALL=C lvm version" returned: 0 in 0.020s {{(pid=2676807) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Jul 26 03:07:49 datacore-PowerEdge-R740 cinder-volume[2676807]: DEBUG oslo_concurrency.processutils [None req-90392122-610e-4cd4-a1ce-813deb2d8974 None None] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool {{(pid=2676807) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Jul 26 03:07:49 datacore-PowerEdge-R740 sudo[2677261]:    stack : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/local/bin/cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool
Jul 26 03:07:49 datacore-PowerEdge-R740 sudo[2677261]: pam_unix(sudo:session): session opened for user root by (uid=0)
Jul 26 03:07:50 datacore-PowerEdge-R740 sudo[2677261]: pam_unix(sudo:session): session closed for user root
Jul 26 03:07:50 datacore-PowerEdge-R740 cinder-volume[2676807]: DEBUG oslo_concurrency.processutils [None req-90392122-610e-4cd4-a1ce-813deb2d8974 None None] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool" returned: 0 in 0.673s {{(pid=2676807) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Jul 26 03:07:50 datacore-PowerEdge-R740 cinder-volume[2676807]: DEBUG cinder.volume.drivers.lvm [None req-90392122-610e-4cd4-a1ce-813deb2d8974 None None] Updating volume stats {{(pid=2676807) _update_volume_stats /opt/stack/cinder/cinder/volume/drivers/lvm.py:213}}
Jul 26 03:07:50 datacore-PowerEdge-R740 cinder-volume[2676807]: DEBUG oslo_concurrency.processutils [None req-90392122-610e-4cd4-a1ce-813deb2d8974 None None] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix stack-volumes-lvmdriver-1 {{(pid=2676807) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Jul 26 03:07:50 datacore-PowerEdge-R740 sudo[2677271]:    stack : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/local/bin/cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix stack-volumes-lvmdriver-1
Jul 26 03:07:50 datacore-PowerEdge-R740 sudo[2677271]: pam_unix(sudo:session): session opened for user root by (uid=0)
Jul 26 03:07:51 datacore-PowerEdge-R740 sudo[2677271]: pam_unix(sudo:session): session closed for user root
Jul 26 03:07:51 datacore-PowerEdge-R740 cinder-volume[2676807]: DEBUG oslo_concurrency.processutils [None req-90392122-610e-4cd4-a1ce-813deb2d8974 None None] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix stack-volumes-lvmdriver-1" returned: 0 in 0.667s {{(pid=2676807) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Jul 26 03:07:51 datacore-PowerEdge-R740 cinder-volume[2676807]: DEBUG oslo_concurrency.processutils [None req-90392122-610e-4cd4-a1ce-813deb2d8974 None None] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1 {{(pid=2676807) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Jul 26 03:07:51 datacore-PowerEdge-R740 sudo[2677275]:    stack : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/local/bin/cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1
Jul 26 03:07:51 datacore-PowerEdge-R740 sudo[2677275]: pam_unix(sudo:session): session opened for user root by (uid=0)
Jul 26 03:07:51 datacore-PowerEdge-R740 cinder-volume[2676588]: DEBUG dbcounter [-] [2676588] Writing DB stats cinder:SELECT=16,cinder:UPDATE=1 {{(pid=2676588) stat_writer /usr/local/lib/python3.8/dist-packages/dbcounter.py:114}}
Jul 26 03:07:51 datacore-PowerEdge-R740 sudo[2677275]: pam_unix(sudo:session): session closed for user root
Jul 26 03:07:51 datacore-PowerEdge-R740 cinder-volume[2676807]: DEBUG oslo_concurrency.processutils [None req-90392122-610e-4cd4-a1ce-813deb2d8974 None None] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1" returned: 0 in 0.631s {{(pid=2676807) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Jul 26 03:07:51 datacore-PowerEdge-R740 cinder-volume[2676807]: DEBUG oslo_concurrency.processutils [None req-90392122-610e-4cd4-a1ce-813deb2d8974 None None] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o size,data_percent --separator : --nosuffix /dev/stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool {{(pid=2676807) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Jul 26 03:07:51 datacore-PowerEdge-R740 sudo[2677291]:    stack : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/local/bin/cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o size,data_percent --separator : --nosuffix /dev/stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool
Jul 26 03:07:51 datacore-PowerEdge-R740 sudo[2677291]: pam_unix(sudo:session): session opened for user root by (uid=0)
Jul 26 03:07:52 datacore-PowerEdge-R740 sudo[2677291]: pam_unix(sudo:session): session closed for user root
Jul 26 03:07:52 datacore-PowerEdge-R740 cinder-volume[2676807]: DEBUG oslo_concurrency.processutils [None req-90392122-610e-4cd4-a1ce-813deb2d8974 None None] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o size,data_percent --separator : --nosuffix /dev/stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool" returned: 0 in 0.660s {{(pid=2676807) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Jul 26 03:07:52 datacore-PowerEdge-R740 cinder-volume[2676807]: DEBUG oslo_concurrency.processutils [None req-90392122-610e-4cd4-a1ce-813deb2d8974 None None] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1 {{(pid=2676807) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Jul 26 03:07:52 datacore-PowerEdge-R740 sudo[2677296]:    stack : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/local/bin/cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1
Jul 26 03:07:52 datacore-PowerEdge-R740 sudo[2677296]: pam_unix(sudo:session): session opened for user root by (uid=0)
Jul 26 03:07:53 datacore-PowerEdge-R740 sudo[2677296]: pam_unix(sudo:session): session closed for user root
Jul 26 03:07:53 datacore-PowerEdge-R740 cinder-volume[2676807]: DEBUG oslo_concurrency.processutils [None req-90392122-610e-4cd4-a1ce-813deb2d8974 None None] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1" returned: 0 in 0.627s {{(pid=2676807) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Jul 26 03:07:53 datacore-PowerEdge-R740 cinder-volume[2676807]: INFO cinder.volume.driver [None req-90392122-610e-4cd4-a1ce-813deb2d8974 None None] Driver hasn't implemented _init_vendor_properties()
Jul 26 03:07:53 datacore-PowerEdge-R740 cinder-volume[2676807]: DEBUG cinder.volume.driver [None req-90392122-610e-4cd4-a1ce-813deb2d8974 None None] Initialized capabilities list: {'volume_backend_name': 'lvmdriver-1', 'vendor_name': 'Open Source', 'driver_version': '3.0.0', 'storage_protocol': 'iSCSI', 'pools': [{'pool_name': 'lvmdriver-1', 'total_capacity_gb': 28.5, 'free_capacity_gb': 28.5, 'reserved_percentage': 0, 'location_info': 'LVMVolumeDriver:datacore-PowerEdge-R740:stack-volumes-lvmdriver-1:thin:0', 'QoS_support': False, 'provisioned_capacity_gb': 0.0, 'max_over_subscription_ratio': '20.0', 'thin_provisioning_support': True, 'thick_provisioning_support': False, 'total_volumes': 1, 'filter_function': None, 'goodness_function': None, 'multiattach': True, 'backend_state': 'up'}], 'shared_targets': False, 'sparse_copy_volume': True, 'properties': {'thin_provisioning': {'title': 'Thin Provisioning', 'description': 'Sets thin provisioning.', 'type': 'boolean'}, 'compression': {'title': 'Compression', 'description': 'Enables compression.', 'type': 'boolean'}, 'qos': {'title': 'QoS', 'description': 'Enables QoS.', 'type': 'boolean'}, 'replication_enabled': {'title': 'Replication', 'description': 'Enables replication.', 'type': 'boolean'}}}. {{(pid=2676807) init_capabilities /opt/stack/cinder/cinder/volume/driver.py:812}}
Jul 26 03:07:53 datacore-PowerEdge-R740 cinder-volume[2676807]: DEBUG oslo_db.sqlalchemy.engines [None req-90392122-610e-4cd4-a1ce-813deb2d8974 None None] MySQL server mode set to STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_ENGINE_SUBSTITUTION {{(pid=2676807) _check_effective_sql_mode /usr/local/lib/python3.8/dist-packages/oslo_db/sqlalchemy/engines.py:314}}
Jul 26 03:07:53 datacore-PowerEdge-R740 cinder-volume[2676807]: DEBUG dbcounter [-] [2676807] Writer thread running {{(pid=2676807) stat_writer /usr/local/lib/python3.8/dist-packages/dbcounter.py:99}}
Jul 26 03:07:53 datacore-PowerEdge-R740 cinder-volume[2676807]: DEBUG cinder.db.sqlalchemy.api [None req-90392122-610e-4cd4-a1ce-813deb2d8974 None None] Building query based on filter {{(pid=2676807) _process_snaps_filters /opt/stack/cinder/cinder/db/sqlalchemy/api.py:3878}}
Jul 26 03:07:53 datacore-PowerEdge-R740 cinder-volume[2676807]: DEBUG cinder.image.image_utils [None req-90392122-610e-4cd4-a1ce-813deb2d8974 None None] Configuration image_conversion_dir is None or the path doesn't exist. {{(pid=2676807) cleanup_temporary_file /opt/stack/cinder/cinder/image/image_utils.py:991}}
Jul 26 03:07:53 datacore-PowerEdge-R740 cinder-volume[2676807]: DEBUG cinder.volume.drivers.lvm [None req-90392122-610e-4cd4-a1ce-813deb2d8974 None None] Updating volume stats {{(pid=2676807) _update_volume_stats /opt/stack/cinder/cinder/volume/drivers/lvm.py:213}}
Jul 26 03:07:53 datacore-PowerEdge-R740 cinder-volume[2676807]: DEBUG oslo_concurrency.processutils [None req-90392122-610e-4cd4-a1ce-813deb2d8974 None None] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix stack-volumes-lvmdriver-1 {{(pid=2676807) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Jul 26 03:07:53 datacore-PowerEdge-R740 sudo[2677307]:    stack : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/local/bin/cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix stack-volumes-lvmdriver-1
Jul 26 03:07:53 datacore-PowerEdge-R740 sudo[2677307]: pam_unix(sudo:session): session opened for user root by (uid=0)
Jul 26 03:07:53 datacore-PowerEdge-R740 cinder-volume[2676807]: INFO cinder.keymgr.migration [None req-6eda331d-f1c1-4c6f-b479-6b2179a53a0d None None] Not migrating encryption keys because the ConfKeyManager is still in use.
Jul 26 03:07:53 datacore-PowerEdge-R740 sudo[2677307]: pam_unix(sudo:session): session closed for user root
Jul 26 03:07:53 datacore-PowerEdge-R740 cinder-volume[2676807]: DEBUG oslo_concurrency.processutils [None req-90392122-610e-4cd4-a1ce-813deb2d8974 None None] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix stack-volumes-lvmdriver-1" returned: 0 in 0.628s {{(pid=2676807) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Jul 26 03:07:53 datacore-PowerEdge-R740 cinder-volume[2676807]: DEBUG oslo_concurrency.processutils [None req-90392122-610e-4cd4-a1ce-813deb2d8974 None None] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1 {{(pid=2676807) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Jul 26 03:07:53 datacore-PowerEdge-R740 sudo[2677317]:    stack : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/local/bin/cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1
Jul 26 03:07:53 datacore-PowerEdge-R740 sudo[2677317]: pam_unix(sudo:session): session opened for user root by (uid=0)
Jul 26 03:07:54 datacore-PowerEdge-R740 sudo[2677317]: pam_unix(sudo:session): session closed for user root
Jul 26 03:07:54 datacore-PowerEdge-R740 cinder-volume[2676807]: DEBUG oslo_concurrency.processutils [None req-90392122-610e-4cd4-a1ce-813deb2d8974 None None] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1" returned: 0 in 0.627s {{(pid=2676807) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Jul 26 03:07:54 datacore-PowerEdge-R740 cinder-volume[2676807]: DEBUG oslo_concurrency.processutils [None req-90392122-610e-4cd4-a1ce-813deb2d8974 None None] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o size,data_percent --separator : --nosuffix /dev/stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool {{(pid=2676807) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Jul 26 03:07:54 datacore-PowerEdge-R740 sudo[2677326]:    stack : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/local/bin/cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o size,data_percent --separator : --nosuffix /dev/stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool
Jul 26 03:07:54 datacore-PowerEdge-R740 sudo[2677326]: pam_unix(sudo:session): session opened for user root by (uid=0)
Jul 26 03:07:55 datacore-PowerEdge-R740 sudo[2677326]: pam_unix(sudo:session): session closed for user root
Jul 26 03:07:55 datacore-PowerEdge-R740 cinder-volume[2676807]: DEBUG oslo_concurrency.processutils [None req-90392122-610e-4cd4-a1ce-813deb2d8974 None None] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o size,data_percent --separator : --nosuffix /dev/stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool" returned: 0 in 0.673s {{(pid=2676807) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Jul 26 03:07:55 datacore-PowerEdge-R740 cinder-volume[2676807]: DEBUG oslo_concurrency.processutils [None req-90392122-610e-4cd4-a1ce-813deb2d8974 None None] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1 {{(pid=2676807) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Jul 26 03:07:55 datacore-PowerEdge-R740 sudo[2677336]:    stack : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/local/bin/cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1
Jul 26 03:07:55 datacore-PowerEdge-R740 sudo[2677336]: pam_unix(sudo:session): session opened for user root by (uid=0)
Jul 26 03:07:55 datacore-PowerEdge-R740 sudo[2677336]: pam_unix(sudo:session): session closed for user root
Jul 26 03:07:55 datacore-PowerEdge-R740 cinder-volume[2676807]: DEBUG oslo_concurrency.processutils [None req-90392122-610e-4cd4-a1ce-813deb2d8974 None None] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1" returned: 0 in 0.665s {{(pid=2676807) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Jul 26 03:07:55 datacore-PowerEdge-R740 cinder-volume[2676807]: DEBUG cinder.manager [None req-90392122-610e-4cd4-a1ce-813deb2d8974 None None] Notifying Schedulers of capabilities ... {{(pid=2676807) _publish_service_capabilities /opt/stack/cinder/cinder/manager.py:202}}
Jul 26 03:07:55 datacore-PowerEdge-R740 cinder-volume[2676807]: INFO cinder.volume.manager [None req-90392122-610e-4cd4-a1ce-813deb2d8974 None None] Driver initialization completed successfully.
Jul 26 03:07:55 datacore-PowerEdge-R740 cinder-volume[2676807]: INFO cinder.manager [None req-90392122-610e-4cd4-a1ce-813deb2d8974 None None] Initiating service 2 cleanup
Jul 26 03:07:55 datacore-PowerEdge-R740 cinder-volume[2676807]: INFO cinder.manager [None req-90392122-610e-4cd4-a1ce-813deb2d8974 None None] Service 2 cleanup completed.
Jul 26 03:07:55 datacore-PowerEdge-R740 cinder-volume[2676807]: DEBUG cinder.service [None req-90392122-610e-4cd4-a1ce-813deb2d8974 None None] Creating RPC server for service cinder-volume {{(pid=2676807) start /opt/stack/cinder/cinder/service.py:231}}
Jul 26 03:07:55 datacore-PowerEdge-R740 cinder-volume[2676807]: DEBUG cinder.service [None req-90392122-610e-4cd4-a1ce-813deb2d8974 None None] Pinning object versions for RPC server serializer to 1.39 {{(pid=2676807) start /opt/stack/cinder/cinder/service.py:237}}
Jul 26 03:07:55 datacore-PowerEdge-R740 cinder-volume[2676807]: INFO cinder.volume.manager [None req-90392122-610e-4cd4-a1ce-813deb2d8974 None None] Initializing RPC dependent components of volume driver LVMVolumeDriver (3.0.0)
Jul 26 03:07:55 datacore-PowerEdge-R740 cinder-volume[2676807]: DEBUG cinder.volume.drivers.lvm [None req-90392122-610e-4cd4-a1ce-813deb2d8974 None None] Updating volume stats {{(pid=2676807) _update_volume_stats /opt/stack/cinder/cinder/volume/drivers/lvm.py:213}}
Jul 26 03:07:55 datacore-PowerEdge-R740 cinder-volume[2676807]: DEBUG oslo_concurrency.processutils [None req-90392122-610e-4cd4-a1ce-813deb2d8974 None None] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix stack-volumes-lvmdriver-1 {{(pid=2676807) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Jul 26 03:07:55 datacore-PowerEdge-R740 sudo[2677348]:    stack : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/local/bin/cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix stack-volumes-lvmdriver-1
Jul 26 03:07:55 datacore-PowerEdge-R740 sudo[2677348]: pam_unix(sudo:session): session opened for user root by (uid=0)
Jul 26 03:07:56 datacore-PowerEdge-R740 sudo[2677348]: pam_unix(sudo:session): session closed for user root
Jul 26 03:07:56 datacore-PowerEdge-R740 cinder-volume[2676807]: DEBUG oslo_concurrency.processutils [None req-90392122-610e-4cd4-a1ce-813deb2d8974 None None] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix stack-volumes-lvmdriver-1" returned: 0 in 0.650s {{(pid=2676807) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Jul 26 03:07:56 datacore-PowerEdge-R740 cinder-volume[2676807]: DEBUG oslo_concurrency.processutils [None req-90392122-610e-4cd4-a1ce-813deb2d8974 None None] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1 {{(pid=2676807) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Jul 26 03:07:56 datacore-PowerEdge-R740 sudo[2677373]:    stack : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/local/bin/cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1
Jul 26 03:07:56 datacore-PowerEdge-R740 sudo[2677373]: pam_unix(sudo:session): session opened for user root by (uid=0)
Jul 26 03:07:57 datacore-PowerEdge-R740 sudo[2677373]: pam_unix(sudo:session): session closed for user root
Jul 26 03:07:57 datacore-PowerEdge-R740 cinder-volume[2676807]: DEBUG oslo_concurrency.processutils [None req-90392122-610e-4cd4-a1ce-813deb2d8974 None None] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1" returned: 0 in 0.669s {{(pid=2676807) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Jul 26 03:07:57 datacore-PowerEdge-R740 cinder-volume[2676807]: DEBUG oslo_concurrency.processutils [None req-90392122-610e-4cd4-a1ce-813deb2d8974 None None] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o size,data_percent --separator : --nosuffix /dev/stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool {{(pid=2676807) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Jul 26 03:07:57 datacore-PowerEdge-R740 sudo[2677386]:    stack : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/local/bin/cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o size,data_percent --separator : --nosuffix /dev/stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool
Jul 26 03:07:57 datacore-PowerEdge-R740 sudo[2677386]: pam_unix(sudo:session): session opened for user root by (uid=0)
Jul 26 03:07:57 datacore-PowerEdge-R740 sudo[2677386]: pam_unix(sudo:session): session closed for user root
Jul 26 03:07:57 datacore-PowerEdge-R740 cinder-volume[2676807]: DEBUG oslo_concurrency.processutils [None req-90392122-610e-4cd4-a1ce-813deb2d8974 None None] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o size,data_percent --separator : --nosuffix /dev/stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool" returned: 0 in 0.622s {{(pid=2676807) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Jul 26 03:07:57 datacore-PowerEdge-R740 cinder-volume[2676807]: DEBUG oslo_concurrency.processutils [None req-90392122-610e-4cd4-a1ce-813deb2d8974 None None] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1 {{(pid=2676807) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Jul 26 03:07:57 datacore-PowerEdge-R740 sudo[2677393]:    stack : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/local/bin/cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1
Jul 26 03:07:57 datacore-PowerEdge-R740 sudo[2677393]: pam_unix(sudo:session): session opened for user root by (uid=0)
Jul 26 03:07:58 datacore-PowerEdge-R740 sudo[2677393]: pam_unix(sudo:session): session closed for user root
Jul 26 03:07:58 datacore-PowerEdge-R740 cinder-volume[2676807]: DEBUG oslo_concurrency.processutils [None req-90392122-610e-4cd4-a1ce-813deb2d8974 None None] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1" returned: 0 in 0.658s {{(pid=2676807) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Jul 26 03:07:58 datacore-PowerEdge-R740 cinder-volume[2676807]: INFO cinder.volume.manager [None req-90392122-610e-4cd4-a1ce-813deb2d8974 None None] Driver post RPC initialization completed successfully.
Jul 26 03:08:00 datacore-PowerEdge-R740 systemd[1]: Stopping Devstack devstack@c-vol.service...
Jul 26 03:08:00 datacore-PowerEdge-R740 cinder-volume[2676588]: INFO oslo_service.service [None req-489abc7a-822b-4258-8373-ddf55c344d5f None None] Caught SIGTERM, stopping children
Jul 26 03:08:00 datacore-PowerEdge-R740 cinder-volume[2676588]: DEBUG oslo_concurrency.lockutils [None req-489abc7a-822b-4258-8373-ddf55c344d5f None None] Acquired lock "singleton_lock" {{(pid=2676588) lock /usr/local/lib/python3.8/dist-packages/oslo_concurrency/lockutils.py:294}}
Jul 26 03:08:00 datacore-PowerEdge-R740 cinder-volume[2676588]: DEBUG oslo_concurrency.lockutils [None req-489abc7a-822b-4258-8373-ddf55c344d5f None None] Releasing lock "singleton_lock" {{(pid=2676588) lock /usr/local/lib/python3.8/dist-packages/oslo_concurrency/lockutils.py:312}}
Jul 26 03:08:00 datacore-PowerEdge-R740 cinder-volume[2676588]: DEBUG oslo_service.service [None req-489abc7a-822b-4258-8373-ddf55c344d5f None None] Stop services. {{(pid=2676588) stop /usr/local/lib/python3.8/dist-packages/oslo_service/service.py:695}}
Jul 26 03:08:00 datacore-PowerEdge-R740 cinder-volume[2676588]: DEBUG oslo_service.service [None req-489abc7a-822b-4258-8373-ddf55c344d5f None None] Killing children. {{(pid=2676588) stop /usr/local/lib/python3.8/dist-packages/oslo_service/service.py:700}}
Jul 26 03:08:00 datacore-PowerEdge-R740 cinder-volume[2676588]: INFO oslo_service.service [None req-489abc7a-822b-4258-8373-ddf55c344d5f None None] Waiting on 1 children to exit
Jul 26 03:08:00 datacore-PowerEdge-R740 cinder-volume[2676807]: DEBUG oslo_concurrency.lockutils [None req-489abc7a-822b-4258-8373-ddf55c344d5f None None] Acquired lock "singleton_lock" {{(pid=2676807) lock /usr/local/lib/python3.8/dist-packages/oslo_concurrency/lockutils.py:294}}
Jul 26 03:08:00 datacore-PowerEdge-R740 cinder-volume[2676807]: DEBUG oslo_concurrency.lockutils [None req-489abc7a-822b-4258-8373-ddf55c344d5f None None] Releasing lock "singleton_lock" {{(pid=2676807) lock /usr/local/lib/python3.8/dist-packages/oslo_concurrency/lockutils.py:312}}
Jul 26 03:08:00 datacore-PowerEdge-R740 cinder-volume[2676807]: WARNING amqp [None req-489abc7a-822b-4258-8373-ddf55c344d5f None None] Received method (60, 30) during closing channel 1. This method will be ignored
Jul 26 03:08:00 datacore-PowerEdge-R740 cinder-volume[2676807]: WARNING amqp [None req-489abc7a-822b-4258-8373-ddf55c344d5f None None] Received method (60, 30) during closing channel 1. This method will be ignored
Jul 26 03:08:00 datacore-PowerEdge-R740 cinder-volume[2676588]: INFO oslo_service.service [None req-489abc7a-822b-4258-8373-ddf55c344d5f None None] Child 2676807 exited with status 0
Jul 26 03:08:00 datacore-PowerEdge-R740 cinder-volume[2676588]: /usr/lib/python3/dist-packages/secretstorage/dhcrypto.py:15: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
Jul 26 03:08:00 datacore-PowerEdge-R740 cinder-volume[2676588]:   from cryptography.utils import int_from_bytes
Jul 26 03:08:00 datacore-PowerEdge-R740 cinder-volume[2676588]: /usr/lib/python3/dist-packages/secretstorage/util.py:19: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
Jul 26 03:08:00 datacore-PowerEdge-R740 cinder-volume[2676588]:   from cryptography.utils import int_from_bytes
Jul 26 03:08:00 datacore-PowerEdge-R740 cinder-volume[2676588]: /opt/stack/cinder/cinder/db/sqlalchemy/models.py:152: SAWarning: implicitly coercing SELECT object to scalar subquery; please use the .scalar_subquery() method to produce a scalar subquery.
Jul 26 03:08:00 datacore-PowerEdge-R740 cinder-volume[2676588]:   last_heartbeat = column_property(
Jul 26 03:08:00 datacore-PowerEdge-R740 cinder-volume[2676588]: /opt/stack/cinder/cinder/db/sqlalchemy/models.py:160: SAWarning: implicitly coercing SELECT object to scalar subquery; please use the .scalar_subquery() method to produce a scalar subquery.
Jul 26 03:08:00 datacore-PowerEdge-R740 cinder-volume[2676588]:   num_hosts = column_property(
Jul 26 03:08:00 datacore-PowerEdge-R740 cinder-volume[2676588]: /opt/stack/cinder/cinder/db/sqlalchemy/models.py:169: SAWarning: implicitly coercing SELECT object to scalar subquery; please use the .scalar_subquery() method to produce a scalar subquery.
Jul 26 03:08:00 datacore-PowerEdge-R740 cinder-volume[2676588]:   num_down_hosts = column_property(
Jul 26 03:08:01 datacore-PowerEdge-R740 systemd[1]: devstack@c-vol.service: Succeeded.
Jul 26 03:08:01 datacore-PowerEdge-R740 systemd[1]: Stopped Devstack devstack@c-vol.service.
Jul 26 03:08:01 datacore-PowerEdge-R740 systemd[1]: Started Devstack devstack@c-vol.service.
Jul 26 03:08:02 datacore-PowerEdge-R740 cinder-volume[2677467]: DEBUG oslo_concurrency.lockutils [-] Acquired lock "singleton_lock" {{(pid=2677467) lock /usr/local/lib/python3.8/dist-packages/oslo_concurrency/lockutils.py:294}}
Jul 26 03:08:02 datacore-PowerEdge-R740 cinder-volume[2677467]: DEBUG oslo_concurrency.lockutils [-] Releasing lock "singleton_lock" {{(pid=2677467) lock /usr/local/lib/python3.8/dist-packages/oslo_concurrency/lockutils.py:312}}
Jul 26 03:08:03 datacore-PowerEdge-R740 cinder-volume[2677467]: INFO dbcounter [None req-18ffb873-e965-4af2-9859-e82c0c056bf8 None None] Registered counter for database cinder
Jul 26 03:08:03 datacore-PowerEdge-R740 cinder-volume[2677467]: DEBUG oslo_db.sqlalchemy.engines [None req-18ffb873-e965-4af2-9859-e82c0c056bf8 None None] MySQL server mode set to STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_ENGINE_SUBSTITUTION {{(pid=2677467) _check_effective_sql_mode /usr/local/lib/python3.8/dist-packages/oslo_db/sqlalchemy/engines.py:314}}
Jul 26 03:08:03 datacore-PowerEdge-R740 cinder-volume[2677467]: DEBUG dbcounter [-] [2677467] Writer thread running {{(pid=2677467) stat_writer /usr/local/lib/python3.8/dist-packages/dbcounter.py:99}}
Jul 26 03:08:03 datacore-PowerEdge-R740 cinder-volume[2677467]: INFO cinder.rpc [None req-18ffb873-e965-4af2-9859-e82c0c056bf8 None None] Automatically selected cinder-scheduler objects version 1.39 as minimum service version.
Jul 26 03:08:03 datacore-PowerEdge-R740 cinder-volume[2677467]: INFO cinder.rpc [None req-18ffb873-e965-4af2-9859-e82c0c056bf8 None None] Automatically selected cinder-scheduler RPC version 3.12 as minimum service version.
Jul 26 03:08:03 datacore-PowerEdge-R740 cinder-volume[2677467]: DEBUG oslo_db.sqlalchemy.engines [None req-18ffb873-e965-4af2-9859-e82c0c056bf8 None None] MySQL server mode set to STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_ENGINE_SUBSTITUTION {{(pid=2677467) _check_effective_sql_mode /usr/local/lib/python3.8/dist-packages/oslo_db/sqlalchemy/engines.py:314}}
Jul 26 03:08:03 datacore-PowerEdge-R740 cinder-volume[2677467]: INFO cinder.volume.manager [None req-18ffb873-e965-4af2-9859-e82c0c056bf8 None None] Determined volume DB was empty at startup.
Jul 26 03:08:03 datacore-PowerEdge-R740 cinder-volume[2677467]: DEBUG cinder.volume.manager [None req-18ffb873-e965-4af2-9859-e82c0c056bf8 None None] Cinder Volume DB check: vol_db_empty=True {{(pid=2677467) __init__ /opt/stack/cinder/cinder/volume/manager.py:290}}
Jul 26 03:08:03 datacore-PowerEdge-R740 cinder-volume[2677467]: INFO cinder.volume.manager [None req-18ffb873-e965-4af2-9859-e82c0c056bf8 None None] Service not found for updating active_backend_id, assuming default for driver init.
Jul 26 03:08:03 datacore-PowerEdge-R740 cinder-volume[2677467]: WARNING stevedore.named [None req-18ffb873-e965-4af2-9859-e82c0c056bf8 None None] Could not load cinder.keymgr.conf_key_mgr.ConfKeyManager
Jul 26 03:08:03 datacore-PowerEdge-R740 cinder-volume[2677467]: WARNING castellan.key_manager [None req-18ffb873-e965-4af2-9859-e82c0c056bf8 None None] Deprecation Warning : cinder.keymgr.conf_key_mgr.ConfKeyManager is not a stevedore based driver, trying to load it as a class: stevedore.exception.NoMatches: No 'castellan.drivers' driver found, looking for 'cinder.keymgr.conf_key_mgr.ConfKeyManager'
Jul 26 03:08:03 datacore-PowerEdge-R740 cinder-volume[2677467]: WARNING cinder.keymgr.conf_key_mgr [None req-18ffb873-e965-4af2-9859-e82c0c056bf8 None None] This key manager is insecure and is not recommended for production deployments: stevedore.exception.NoMatches: No 'castellan.drivers' driver found, looking for 'cinder.keymgr.conf_key_mgr.ConfKeyManager'
Jul 26 03:08:03 datacore-PowerEdge-R740 cinder-volume[2677467]: ERROR cinder.cmd.volume [None req-18ffb873-e965-4af2-9859-e82c0c056bf8 None None] Volume service hostgroup@datacore_iscsi1 failed to start.: ModuleNotFoundError: No module named 'cinder.volume.drivers.datacore.iscsi'
Jul 26 03:08:03 datacore-PowerEdge-R740 cinder-volume[2677467]: ERROR cinder.cmd.volume Traceback (most recent call last):
Jul 26 03:08:03 datacore-PowerEdge-R740 cinder-volume[2677467]: ERROR cinder.cmd.volume   File "/opt/stack/cinder/cinder/cmd/volume.py", line 99, in _launch_service
Jul 26 03:08:03 datacore-PowerEdge-R740 cinder-volume[2677467]: ERROR cinder.cmd.volume     server = service.Service.create(host=host,
Jul 26 03:08:03 datacore-PowerEdge-R740 cinder-volume[2677467]: ERROR cinder.cmd.volume   File "/opt/stack/cinder/cinder/service.py", line 394, in create
Jul 26 03:08:03 datacore-PowerEdge-R740 cinder-volume[2677467]: ERROR cinder.cmd.volume     service_obj = cls(host, binary, topic, manager,
Jul 26 03:08:03 datacore-PowerEdge-R740 cinder-volume[2677467]: ERROR cinder.cmd.volume   File "/opt/stack/cinder/cinder/service.py", line 152, in __init__
Jul 26 03:08:03 datacore-PowerEdge-R740 cinder-volume[2677467]: ERROR cinder.cmd.volume     self.manager = manager_class(host=self.host,
Jul 26 03:08:03 datacore-PowerEdge-R740 cinder-volume[2677467]: ERROR cinder.cmd.volume   File "/opt/stack/cinder/cinder/volume/manager.py", line 313, in __init__
Jul 26 03:08:03 datacore-PowerEdge-R740 cinder-volume[2677467]: ERROR cinder.cmd.volume     self.driver = importutils.import_object(
Jul 26 03:08:03 datacore-PowerEdge-R740 cinder-volume[2677467]: ERROR cinder.cmd.volume   File "/usr/local/lib/python3.8/dist-packages/oslo_utils/importutils.py", line 44, in import_object
Jul 26 03:08:03 datacore-PowerEdge-R740 cinder-volume[2677467]: ERROR cinder.cmd.volume     return import_class(import_str)(*args, **kwargs)
Jul 26 03:08:03 datacore-PowerEdge-R740 cinder-volume[2677467]: ERROR cinder.cmd.volume   File "/usr/local/lib/python3.8/dist-packages/oslo_utils/importutils.py", line 30, in import_class
Jul 26 03:08:03 datacore-PowerEdge-R740 cinder-volume[2677467]: ERROR cinder.cmd.volume     __import__(mod_str)
Jul 26 03:08:03 datacore-PowerEdge-R740 cinder-volume[2677467]: ERROR cinder.cmd.volume ModuleNotFoundError: No module named 'cinder.volume.drivers.datacore.iscsi'
Jul 26 03:08:03 datacore-PowerEdge-R740 cinder-volume[2677467]: ERROR cinder.cmd.volume 
Jul 26 03:08:03 datacore-PowerEdge-R740 cinder-volume[2677467]: ERROR cinder.cmd.volume [None req-18ffb873-e965-4af2-9859-e82c0c056bf8 None None] No volume service(s) started successfully, terminating.
Jul 26 03:08:03 datacore-PowerEdge-R740 cinder-volume[2677467]: /usr/lib/python3/dist-packages/secretstorage/dhcrypto.py:15: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
Jul 26 03:08:03 datacore-PowerEdge-R740 cinder-volume[2677467]:   from cryptography.utils import int_from_bytes
Jul 26 03:08:03 datacore-PowerEdge-R740 cinder-volume[2677467]: /usr/lib/python3/dist-packages/secretstorage/util.py:19: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
Jul 26 03:08:03 datacore-PowerEdge-R740 cinder-volume[2677467]:   from cryptography.utils import int_from_bytes
Jul 26 03:08:03 datacore-PowerEdge-R740 cinder-volume[2677467]: /opt/stack/cinder/cinder/db/sqlalchemy/models.py:152: SAWarning: implicitly coercing SELECT object to scalar subquery; please use the .scalar_subquery() method to produce a scalar subquery.
Jul 26 03:08:03 datacore-PowerEdge-R740 cinder-volume[2677467]:   last_heartbeat = column_property(
Jul 26 03:08:03 datacore-PowerEdge-R740 cinder-volume[2677467]: /opt/stack/cinder/cinder/db/sqlalchemy/models.py:160: SAWarning: implicitly coercing SELECT object to scalar subquery; please use the .scalar_subquery() method to produce a scalar subquery.
Jul 26 03:08:03 datacore-PowerEdge-R740 cinder-volume[2677467]:   num_hosts = column_property(
Jul 26 03:08:03 datacore-PowerEdge-R740 cinder-volume[2677467]: /opt/stack/cinder/cinder/db/sqlalchemy/models.py:169: SAWarning: implicitly coercing SELECT object to scalar subquery; please use the .scalar_subquery() method to produce a scalar subquery.
Jul 26 03:08:03 datacore-PowerEdge-R740 cinder-volume[2677467]:   num_down_hosts = column_property(
Jul 26 03:08:04 datacore-PowerEdge-R740 systemd[1]: devstack@c-vol.service: Main process exited, code=exited, status=1/FAILURE
Jul 26 03:08:04 datacore-PowerEdge-R740 systemd[1]: devstack@c-vol.service: Failed with result 'exit-code'.
