-- Logs begin at Thu 2022-09-15 12:33:25 IST, end at Thu 2022-09-15 12:33:36 IST. --
Sep 15 12:33:25 datacore-PowerEdge-R740 sudo[2824109]: pam_unix(sudo:session): session closed for user root
Sep 15 12:33:25 datacore-PowerEdge-R740 cinder-volume[2824027]: DEBUG oslo_concurrency.processutils [None req-09535606-58e4-470c-85d9-089a436e0dea None None] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf lvchange -a y --yes -K stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool" returned: 0 in 0.958s {{(pid=2824027) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Sep 15 12:33:25 datacore-PowerEdge-R740 cinder-volume[2824027]: DEBUG oslo_concurrency.processutils [None req-09535606-58e4-470c-85d9-089a436e0dea None None] Running cmd (subprocess): env LC_ALL=C lvm version {{(pid=2824027) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Sep 15 12:33:25 datacore-PowerEdge-R740 cinder-volume[2824027]: DEBUG oslo_concurrency.processutils [None req-09535606-58e4-470c-85d9-089a436e0dea None None] CMD "env LC_ALL=C lvm version" returned: 0 in 0.018s {{(pid=2824027) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Sep 15 12:33:25 datacore-PowerEdge-R740 cinder-volume[2824027]: DEBUG oslo_concurrency.processutils [None req-09535606-58e4-470c-85d9-089a436e0dea None None] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C pvs --noheadings --unit=g -o vg_name,name,size,free --separator | --nosuffix --ignoreskippedcluster {{(pid=2824027) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Sep 15 12:33:25 datacore-PowerEdge-R740 sudo[2824255]:    stack : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/local/bin/cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C pvs --noheadings --unit=g -o vg_name,name,size,free --separator | --nosuffix --ignoreskippedcluster
Sep 15 12:33:25 datacore-PowerEdge-R740 sudo[2824255]: pam_unix(sudo:session): session opened for user root by (uid=0)
Sep 15 12:33:26 datacore-PowerEdge-R740 sudo[2824255]: pam_unix(sudo:session): session closed for user root
Sep 15 12:33:26 datacore-PowerEdge-R740 cinder-volume[2824027]: DEBUG oslo_concurrency.processutils [None req-09535606-58e4-470c-85d9-089a436e0dea None None] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C pvs --noheadings --unit=g -o vg_name,name,size,free --separator | --nosuffix --ignoreskippedcluster" returned: 0 in 0.681s {{(pid=2824027) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Sep 15 12:33:26 datacore-PowerEdge-R740 cinder-volume[2824027]: DEBUG oslo_concurrency.processutils [None req-09535606-58e4-470c-85d9-089a436e0dea None None] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix stack-volumes-lvmdriver-1 {{(pid=2824027) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Sep 15 12:33:26 datacore-PowerEdge-R740 sudo[2824286]:    stack : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/local/bin/cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix stack-volumes-lvmdriver-1
Sep 15 12:33:26 datacore-PowerEdge-R740 sudo[2824286]: pam_unix(sudo:session): session opened for user root by (uid=0)
Sep 15 12:33:26 datacore-PowerEdge-R740 sudo[2824286]: pam_unix(sudo:session): session closed for user root
Sep 15 12:33:26 datacore-PowerEdge-R740 cinder-volume[2824027]: DEBUG oslo_concurrency.processutils [None req-09535606-58e4-470c-85d9-089a436e0dea None None] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix stack-volumes-lvmdriver-1" returned: 0 in 0.682s {{(pid=2824027) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Sep 15 12:33:26 datacore-PowerEdge-R740 cinder-volume[2824027]: DEBUG oslo_concurrency.processutils [None req-09535606-58e4-470c-85d9-089a436e0dea None None] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix stack-volumes-lvmdriver-1 {{(pid=2824027) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Sep 15 12:33:26 datacore-PowerEdge-R740 sudo[2824322]:    stack : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/local/bin/cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix stack-volumes-lvmdriver-1
Sep 15 12:33:26 datacore-PowerEdge-R740 sudo[2824322]: pam_unix(sudo:session): session opened for user root by (uid=0)
Sep 15 12:33:27 datacore-PowerEdge-R740 sudo[2824322]: pam_unix(sudo:session): session closed for user root
Sep 15 12:33:27 datacore-PowerEdge-R740 cinder-volume[2824027]: DEBUG oslo_concurrency.processutils [None req-09535606-58e4-470c-85d9-089a436e0dea None None] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix stack-volumes-lvmdriver-1" returned: 0 in 0.666s {{(pid=2824027) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Sep 15 12:33:27 datacore-PowerEdge-R740 cinder-volume[2824027]: DEBUG oslo_concurrency.processutils [None req-09535606-58e4-470c-85d9-089a436e0dea None None] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1 {{(pid=2824027) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Sep 15 12:33:27 datacore-PowerEdge-R740 sudo[2824328]:    stack : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/local/bin/cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1
Sep 15 12:33:27 datacore-PowerEdge-R740 sudo[2824328]: pam_unix(sudo:session): session opened for user root by (uid=0)
Sep 15 12:33:28 datacore-PowerEdge-R740 sudo[2824328]: pam_unix(sudo:session): session closed for user root
Sep 15 12:33:28 datacore-PowerEdge-R740 cinder-volume[2824027]: DEBUG oslo_concurrency.processutils [None req-09535606-58e4-470c-85d9-089a436e0dea None None] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1" returned: 0 in 0.632s {{(pid=2824027) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Sep 15 12:33:28 datacore-PowerEdge-R740 cinder-volume[2824027]: DEBUG oslo_concurrency.processutils [None req-09535606-58e4-470c-85d9-089a436e0dea None None] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o size,data_percent --separator : --nosuffix /dev/stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool {{(pid=2824027) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Sep 15 12:33:28 datacore-PowerEdge-R740 sudo[2824332]:    stack : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/local/bin/cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o size,data_percent --separator : --nosuffix /dev/stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool
Sep 15 12:33:28 datacore-PowerEdge-R740 sudo[2824332]: pam_unix(sudo:session): session opened for user root by (uid=0)
Sep 15 12:33:28 datacore-PowerEdge-R740 sudo[2824332]: pam_unix(sudo:session): session closed for user root
Sep 15 12:33:28 datacore-PowerEdge-R740 cinder-volume[2824027]: DEBUG oslo_concurrency.processutils [None req-09535606-58e4-470c-85d9-089a436e0dea None None] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o size,data_percent --separator : --nosuffix /dev/stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool" returned: 0 in 0.620s {{(pid=2824027) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Sep 15 12:33:28 datacore-PowerEdge-R740 cinder-volume[2824027]: DEBUG oslo_concurrency.processutils [None req-09535606-58e4-470c-85d9-089a436e0dea None None] Running cmd (subprocess): env LC_ALL=C lvm version {{(pid=2824027) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Sep 15 12:33:28 datacore-PowerEdge-R740 cinder-volume[2824027]: DEBUG oslo_concurrency.processutils [None req-09535606-58e4-470c-85d9-089a436e0dea None None] CMD "env LC_ALL=C lvm version" returned: 0 in 0.020s {{(pid=2824027) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Sep 15 12:33:28 datacore-PowerEdge-R740 cinder-volume[2824027]: DEBUG oslo_concurrency.processutils [None req-09535606-58e4-470c-85d9-089a436e0dea None None] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool {{(pid=2824027) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Sep 15 12:33:28 datacore-PowerEdge-R740 sudo[2824339]:    stack : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/local/bin/cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool
Sep 15 12:33:28 datacore-PowerEdge-R740 sudo[2824339]: pam_unix(sudo:session): session opened for user root by (uid=0)
Sep 15 12:33:29 datacore-PowerEdge-R740 sudo[2824339]: pam_unix(sudo:session): session closed for user root
Sep 15 12:33:29 datacore-PowerEdge-R740 cinder-volume[2824027]: DEBUG oslo_concurrency.processutils [None req-09535606-58e4-470c-85d9-089a436e0dea None None] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool" returned: 0 in 0.635s {{(pid=2824027) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Sep 15 12:33:29 datacore-PowerEdge-R740 cinder-volume[2824027]: INFO cinder.volume.drivers.lvm [None req-09535606-58e4-470c-85d9-089a436e0dea None None] Enabling LVM thin provisioning by default because a thin pool exists.
Sep 15 12:33:29 datacore-PowerEdge-R740 cinder-volume[2824027]: DEBUG oslo_concurrency.processutils [None req-09535606-58e4-470c-85d9-089a436e0dea None None] Running cmd (subprocess): env LC_ALL=C lvm version {{(pid=2824027) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Sep 15 12:33:29 datacore-PowerEdge-R740 cinder-volume[2824027]: DEBUG oslo_concurrency.processutils [None req-09535606-58e4-470c-85d9-089a436e0dea None None] CMD "env LC_ALL=C lvm version" returned: 0 in 0.016s {{(pid=2824027) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Sep 15 12:33:29 datacore-PowerEdge-R740 cinder-volume[2824027]: DEBUG oslo_concurrency.processutils [None req-09535606-58e4-470c-85d9-089a436e0dea None None] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool {{(pid=2824027) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Sep 15 12:33:29 datacore-PowerEdge-R740 sudo[2824344]:    stack : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/local/bin/cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool
Sep 15 12:33:29 datacore-PowerEdge-R740 sudo[2824344]: pam_unix(sudo:session): session opened for user root by (uid=0)
Sep 15 12:33:30 datacore-PowerEdge-R740 sudo[2824344]: pam_unix(sudo:session): session closed for user root
Sep 15 12:33:30 datacore-PowerEdge-R740 cinder-volume[2824027]: DEBUG oslo_concurrency.processutils [None req-09535606-58e4-470c-85d9-089a436e0dea None None] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool" returned: 0 in 0.630s {{(pid=2824027) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Sep 15 12:33:30 datacore-PowerEdge-R740 cinder-volume[2824027]: DEBUG cinder.volume.drivers.lvm [None req-09535606-58e4-470c-85d9-089a436e0dea None None] Updating volume stats {{(pid=2824027) _update_volume_stats /opt/stack/cinder/cinder/volume/drivers/lvm.py:213}}
Sep 15 12:33:30 datacore-PowerEdge-R740 cinder-volume[2824027]: DEBUG oslo_concurrency.processutils [None req-09535606-58e4-470c-85d9-089a436e0dea None None] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix stack-volumes-lvmdriver-1 {{(pid=2824027) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Sep 15 12:33:30 datacore-PowerEdge-R740 sudo[2824360]:    stack : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/local/bin/cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix stack-volumes-lvmdriver-1
Sep 15 12:33:30 datacore-PowerEdge-R740 sudo[2824360]: pam_unix(sudo:session): session opened for user root by (uid=0)
Sep 15 12:33:30 datacore-PowerEdge-R740 sudo[2824360]: pam_unix(sudo:session): session closed for user root
Sep 15 12:33:30 datacore-PowerEdge-R740 cinder-volume[2824027]: DEBUG oslo_concurrency.processutils [None req-09535606-58e4-470c-85d9-089a436e0dea None None] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix stack-volumes-lvmdriver-1" returned: 0 in 0.689s {{(pid=2824027) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Sep 15 12:33:30 datacore-PowerEdge-R740 cinder-volume[2824027]: DEBUG oslo_concurrency.processutils [None req-09535606-58e4-470c-85d9-089a436e0dea None None] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1 {{(pid=2824027) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Sep 15 12:33:30 datacore-PowerEdge-R740 sudo[2824365]:    stack : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/local/bin/cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1
Sep 15 12:33:30 datacore-PowerEdge-R740 sudo[2824365]: pam_unix(sudo:session): session opened for user root by (uid=0)
Sep 15 12:33:31 datacore-PowerEdge-R740 sudo[2824365]: pam_unix(sudo:session): session closed for user root
Sep 15 12:33:31 datacore-PowerEdge-R740 cinder-volume[2824027]: DEBUG oslo_concurrency.processutils [None req-09535606-58e4-470c-85d9-089a436e0dea None None] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1" returned: 0 in 0.661s {{(pid=2824027) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Sep 15 12:33:31 datacore-PowerEdge-R740 cinder-volume[2824027]: DEBUG oslo_concurrency.processutils [None req-09535606-58e4-470c-85d9-089a436e0dea None None] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o size,data_percent --separator : --nosuffix /dev/stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool {{(pid=2824027) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Sep 15 12:33:31 datacore-PowerEdge-R740 sudo[2824371]:    stack : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/local/bin/cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o size,data_percent --separator : --nosuffix /dev/stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool
Sep 15 12:33:31 datacore-PowerEdge-R740 sudo[2824371]: pam_unix(sudo:session): session opened for user root by (uid=0)
Sep 15 12:33:32 datacore-PowerEdge-R740 sudo[2824371]: pam_unix(sudo:session): session closed for user root
Sep 15 12:33:32 datacore-PowerEdge-R740 cinder-volume[2824027]: DEBUG oslo_concurrency.processutils [None req-09535606-58e4-470c-85d9-089a436e0dea None None] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o size,data_percent --separator : --nosuffix /dev/stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool" returned: 0 in 0.689s {{(pid=2824027) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Sep 15 12:33:32 datacore-PowerEdge-R740 cinder-volume[2824027]: DEBUG oslo_concurrency.processutils [None req-09535606-58e4-470c-85d9-089a436e0dea None None] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1 {{(pid=2824027) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Sep 15 12:33:32 datacore-PowerEdge-R740 sudo[2824380]:    stack : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/local/bin/cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1
Sep 15 12:33:32 datacore-PowerEdge-R740 sudo[2824380]: pam_unix(sudo:session): session opened for user root by (uid=0)
Sep 15 12:33:32 datacore-PowerEdge-R740 cinder-volume[2823812]: DEBUG dbcounter [-] [2823812] Writing DB stats cinder:SELECT=16,cinder:UPDATE=1 {{(pid=2823812) stat_writer /usr/local/lib/python3.8/dist-packages/dbcounter.py:114}}
Sep 15 12:33:32 datacore-PowerEdge-R740 sudo[2824380]: pam_unix(sudo:session): session closed for user root
Sep 15 12:33:32 datacore-PowerEdge-R740 cinder-volume[2824027]: DEBUG oslo_concurrency.processutils [None req-09535606-58e4-470c-85d9-089a436e0dea None None] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1" returned: 0 in 0.664s {{(pid=2824027) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Sep 15 12:33:32 datacore-PowerEdge-R740 cinder-volume[2824027]: INFO cinder.volume.driver [None req-09535606-58e4-470c-85d9-089a436e0dea None None] Driver hasn't implemented _init_vendor_properties()
Sep 15 12:33:32 datacore-PowerEdge-R740 cinder-volume[2824027]: DEBUG cinder.volume.driver [None req-09535606-58e4-470c-85d9-089a436e0dea None None] Initialized capabilities list: {'volume_backend_name': 'lvmdriver-1', 'vendor_name': 'Open Source', 'driver_version': '3.0.0', 'storage_protocol': 'iSCSI', 'pools': [{'pool_name': 'lvmdriver-1', 'total_capacity_gb': 28.5, 'free_capacity_gb': 28.5, 'reserved_percentage': 0, 'location_info': 'LVMVolumeDriver:datacore-PowerEdge-R740:stack-volumes-lvmdriver-1:thin:0', 'QoS_support': False, 'provisioned_capacity_gb': 0.0, 'max_over_subscription_ratio': '20.0', 'thin_provisioning_support': True, 'thick_provisioning_support': False, 'total_volumes': 1, 'filter_function': None, 'goodness_function': None, 'multiattach': True, 'backend_state': 'up'}], 'shared_targets': False, 'sparse_copy_volume': True, 'properties': {'thin_provisioning': {'title': 'Thin Provisioning', 'description': 'Sets thin provisioning.', 'type': 'boolean'}, 'compression': {'title': 'Compression', 'description': 'Enables compression.', 'type': 'boolean'}, 'qos': {'title': 'QoS', 'description': 'Enables QoS.', 'type': 'boolean'}, 'replication_enabled': {'title': 'Replication', 'description': 'Enables replication.', 'type': 'boolean'}}}. {{(pid=2824027) init_capabilities /opt/stack/cinder/cinder/volume/driver.py:820}}
Sep 15 12:33:32 datacore-PowerEdge-R740 cinder-volume[2824027]: DEBUG oslo_db.sqlalchemy.engines [None req-09535606-58e4-470c-85d9-089a436e0dea None None] MySQL server mode set to STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_ENGINE_SUBSTITUTION {{(pid=2824027) _check_effective_sql_mode /usr/local/lib/python3.8/dist-packages/oslo_db/sqlalchemy/engines.py:314}}
Sep 15 12:33:32 datacore-PowerEdge-R740 cinder-volume[2824027]: DEBUG dbcounter [-] [2824027] Writer thread running {{(pid=2824027) stat_writer /usr/local/lib/python3.8/dist-packages/dbcounter.py:99}}
Sep 15 12:33:32 datacore-PowerEdge-R740 cinder-volume[2824027]: DEBUG cinder.db.sqlalchemy.api [None req-09535606-58e4-470c-85d9-089a436e0dea None None] Building query based on filter {{(pid=2824027) _process_snaps_filters /opt/stack/cinder/cinder/db/sqlalchemy/api.py:3156}}
Sep 15 12:33:32 datacore-PowerEdge-R740 cinder-volume[2824027]: DEBUG cinder.image.image_utils [None req-09535606-58e4-470c-85d9-089a436e0dea None None] Configuration image_conversion_dir is None or the path doesn't exist. {{(pid=2824027) cleanup_temporary_file /opt/stack/cinder/cinder/image/image_utils.py:955}}
Sep 15 12:33:32 datacore-PowerEdge-R740 cinder-volume[2824027]: DEBUG cinder.volume.drivers.lvm [None req-09535606-58e4-470c-85d9-089a436e0dea None None] Updating volume stats {{(pid=2824027) _update_volume_stats /opt/stack/cinder/cinder/volume/drivers/lvm.py:213}}
Sep 15 12:33:32 datacore-PowerEdge-R740 cinder-volume[2824027]: DEBUG oslo_concurrency.processutils [None req-09535606-58e4-470c-85d9-089a436e0dea None None] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix stack-volumes-lvmdriver-1 {{(pid=2824027) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Sep 15 12:33:32 datacore-PowerEdge-R740 cinder-volume[2824027]: INFO cinder.keymgr.migration [None req-cb2d5998-591e-457c-9e28-a9ea5ea6a60a None None] Not migrating encryption keys because the ConfKeyManager is still in use.
Sep 15 12:33:32 datacore-PowerEdge-R740 sudo[2824395]:    stack : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/local/bin/cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix stack-volumes-lvmdriver-1
Sep 15 12:33:32 datacore-PowerEdge-R740 sudo[2824395]: pam_unix(sudo:session): session opened for user root by (uid=0)
Sep 15 12:33:33 datacore-PowerEdge-R740 sudo[2824395]: pam_unix(sudo:session): session closed for user root
Sep 15 12:33:33 datacore-PowerEdge-R740 cinder-volume[2824027]: DEBUG oslo_concurrency.processutils [None req-09535606-58e4-470c-85d9-089a436e0dea None None] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix stack-volumes-lvmdriver-1" returned: 0 in 0.660s {{(pid=2824027) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Sep 15 12:33:33 datacore-PowerEdge-R740 cinder-volume[2824027]: DEBUG oslo_concurrency.processutils [None req-09535606-58e4-470c-85d9-089a436e0dea None None] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1 {{(pid=2824027) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Sep 15 12:33:33 datacore-PowerEdge-R740 sudo[2824401]:    stack : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/local/bin/cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1
Sep 15 12:33:33 datacore-PowerEdge-R740 sudo[2824401]: pam_unix(sudo:session): session opened for user root by (uid=0)
Sep 15 12:33:34 datacore-PowerEdge-R740 sudo[2824401]: pam_unix(sudo:session): session closed for user root
Sep 15 12:33:34 datacore-PowerEdge-R740 cinder-volume[2824027]: DEBUG oslo_concurrency.processutils [None req-09535606-58e4-470c-85d9-089a436e0dea None None] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1" returned: 0 in 0.648s {{(pid=2824027) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Sep 15 12:33:34 datacore-PowerEdge-R740 cinder-volume[2824027]: DEBUG oslo_concurrency.processutils [None req-09535606-58e4-470c-85d9-089a436e0dea None None] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o size,data_percent --separator : --nosuffix /dev/stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool {{(pid=2824027) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Sep 15 12:33:34 datacore-PowerEdge-R740 sudo[2824409]:    stack : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/local/bin/cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o size,data_percent --separator : --nosuffix /dev/stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool
Sep 15 12:33:34 datacore-PowerEdge-R740 sudo[2824409]: pam_unix(sudo:session): session opened for user root by (uid=0)
Sep 15 12:33:34 datacore-PowerEdge-R740 sudo[2824409]: pam_unix(sudo:session): session closed for user root
Sep 15 12:33:34 datacore-PowerEdge-R740 cinder-volume[2824027]: DEBUG oslo_concurrency.processutils [None req-09535606-58e4-470c-85d9-089a436e0dea None None] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o size,data_percent --separator : --nosuffix /dev/stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool" returned: 0 in 0.667s {{(pid=2824027) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Sep 15 12:33:34 datacore-PowerEdge-R740 cinder-volume[2824027]: DEBUG oslo_concurrency.processutils [None req-09535606-58e4-470c-85d9-089a436e0dea None None] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1 {{(pid=2824027) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Sep 15 12:33:34 datacore-PowerEdge-R740 sudo[2824428]:    stack : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/local/bin/cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1
Sep 15 12:33:34 datacore-PowerEdge-R740 sudo[2824428]: pam_unix(sudo:session): session opened for user root by (uid=0)
Sep 15 12:33:35 datacore-PowerEdge-R740 sudo[2824428]: pam_unix(sudo:session): session closed for user root
Sep 15 12:33:35 datacore-PowerEdge-R740 cinder-volume[2824027]: DEBUG oslo_concurrency.processutils [None req-09535606-58e4-470c-85d9-089a436e0dea None None] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1" returned: 0 in 0.644s {{(pid=2824027) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Sep 15 12:33:35 datacore-PowerEdge-R740 cinder-volume[2824027]: DEBUG cinder.manager [None req-09535606-58e4-470c-85d9-089a436e0dea None None] Notifying Schedulers of capabilities ... {{(pid=2824027) _publish_service_capabilities /opt/stack/cinder/cinder/manager.py:202}}
Sep 15 12:33:35 datacore-PowerEdge-R740 cinder-volume[2824027]: INFO cinder.volume.manager [None req-09535606-58e4-470c-85d9-089a436e0dea None None] Driver initialization completed successfully.
Sep 15 12:33:35 datacore-PowerEdge-R740 cinder-volume[2824027]: INFO cinder.manager [None req-09535606-58e4-470c-85d9-089a436e0dea None None] Initiating service 2 cleanup
Sep 15 12:33:35 datacore-PowerEdge-R740 cinder-volume[2824027]: INFO cinder.manager [None req-09535606-58e4-470c-85d9-089a436e0dea None None] Service 2 cleanup completed.
Sep 15 12:33:35 datacore-PowerEdge-R740 cinder-volume[2824027]: DEBUG cinder.service [None req-09535606-58e4-470c-85d9-089a436e0dea None None] Creating RPC server for service cinder-volume {{(pid=2824027) start /opt/stack/cinder/cinder/service.py:231}}
Sep 15 12:33:35 datacore-PowerEdge-R740 cinder-volume[2824027]: DEBUG cinder.service [None req-09535606-58e4-470c-85d9-089a436e0dea None None] Pinning object versions for RPC server serializer to 1.39 {{(pid=2824027) start /opt/stack/cinder/cinder/service.py:237}}
Sep 15 12:33:35 datacore-PowerEdge-R740 cinder-volume[2824027]: INFO cinder.volume.manager [None req-09535606-58e4-470c-85d9-089a436e0dea None None] Initializing RPC dependent components of volume driver LVMVolumeDriver (3.0.0)
Sep 15 12:33:35 datacore-PowerEdge-R740 cinder-volume[2824027]: DEBUG cinder.volume.drivers.lvm [None req-09535606-58e4-470c-85d9-089a436e0dea None None] Updating volume stats {{(pid=2824027) _update_volume_stats /opt/stack/cinder/cinder/volume/drivers/lvm.py:213}}
Sep 15 12:33:35 datacore-PowerEdge-R740 cinder-volume[2824027]: DEBUG oslo_concurrency.processutils [None req-09535606-58e4-470c-85d9-089a436e0dea None None] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix stack-volumes-lvmdriver-1 {{(pid=2824027) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Sep 15 12:33:35 datacore-PowerEdge-R740 sudo[2824446]:    stack : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/local/bin/cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix stack-volumes-lvmdriver-1
Sep 15 12:33:35 datacore-PowerEdge-R740 sudo[2824446]: pam_unix(sudo:session): session opened for user root by (uid=0)
Sep 15 12:33:36 datacore-PowerEdge-R740 sudo[2824446]: pam_unix(sudo:session): session closed for user root
Sep 15 12:33:36 datacore-PowerEdge-R740 cinder-volume[2824027]: DEBUG oslo_concurrency.processutils [None req-09535606-58e4-470c-85d9-089a436e0dea None None] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix stack-volumes-lvmdriver-1" returned: 0 in 0.655s {{(pid=2824027) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Sep 15 12:33:36 datacore-PowerEdge-R740 cinder-volume[2824027]: DEBUG oslo_concurrency.processutils [None req-09535606-58e4-470c-85d9-089a436e0dea None None] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1 {{(pid=2824027) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
