-- Logs begin at Tue 2022-09-20 12:46:10 IST, end at Tue 2022-09-20 12:46:21 IST. --
Sep 20 12:46:11 datacore-PowerEdge-R740 sudo[2339480]: pam_unix(sudo:session): session closed for user root
Sep 20 12:46:11 datacore-PowerEdge-R740 cinder-volume[2339399]: DEBUG oslo_concurrency.processutils [None req-c815772e-e5a8-458a-a573-9cf58fb40b2d None None] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf lvchange -a y --yes -K stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool" returned: 0 in 0.906s {{(pid=2339399) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Sep 20 12:46:11 datacore-PowerEdge-R740 cinder-volume[2339399]: DEBUG oslo_concurrency.processutils [None req-c815772e-e5a8-458a-a573-9cf58fb40b2d None None] Running cmd (subprocess): env LC_ALL=C lvm version {{(pid=2339399) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Sep 20 12:46:11 datacore-PowerEdge-R740 cinder-volume[2339399]: DEBUG oslo_concurrency.processutils [None req-c815772e-e5a8-458a-a573-9cf58fb40b2d None None] CMD "env LC_ALL=C lvm version" returned: 0 in 0.018s {{(pid=2339399) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Sep 20 12:46:11 datacore-PowerEdge-R740 cinder-volume[2339399]: DEBUG oslo_concurrency.processutils [None req-c815772e-e5a8-458a-a573-9cf58fb40b2d None None] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C pvs --noheadings --unit=g -o vg_name,name,size,free --separator | --nosuffix --ignoreskippedcluster {{(pid=2339399) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Sep 20 12:46:11 datacore-PowerEdge-R740 sudo[2339526]:    stack : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/local/bin/cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C pvs --noheadings --unit=g -o vg_name,name,size,free --separator | --nosuffix --ignoreskippedcluster
Sep 20 12:46:11 datacore-PowerEdge-R740 sudo[2339526]: pam_unix(sudo:session): session opened for user root by (uid=0)
Sep 20 12:46:11 datacore-PowerEdge-R740 sudo[2339526]: pam_unix(sudo:session): session closed for user root
Sep 20 12:46:11 datacore-PowerEdge-R740 cinder-volume[2339399]: DEBUG oslo_concurrency.processutils [None req-c815772e-e5a8-458a-a573-9cf58fb40b2d None None] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C pvs --noheadings --unit=g -o vg_name,name,size,free --separator | --nosuffix --ignoreskippedcluster" returned: 0 in 0.815s {{(pid=2339399) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Sep 20 12:46:11 datacore-PowerEdge-R740 cinder-volume[2339399]: DEBUG oslo_concurrency.processutils [None req-c815772e-e5a8-458a-a573-9cf58fb40b2d None None] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix stack-volumes-lvmdriver-1 {{(pid=2339399) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Sep 20 12:46:12 datacore-PowerEdge-R740 sudo[2339661]:    stack : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/local/bin/cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix stack-volumes-lvmdriver-1
Sep 20 12:46:12 datacore-PowerEdge-R740 sudo[2339661]: pam_unix(sudo:session): session opened for user root by (uid=0)
Sep 20 12:46:12 datacore-PowerEdge-R740 sudo[2339661]: pam_unix(sudo:session): session closed for user root
Sep 20 12:46:12 datacore-PowerEdge-R740 cinder-volume[2339399]: DEBUG oslo_concurrency.processutils [None req-c815772e-e5a8-458a-a573-9cf58fb40b2d None None] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix stack-volumes-lvmdriver-1" returned: 0 in 0.660s {{(pid=2339399) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Sep 20 12:46:12 datacore-PowerEdge-R740 cinder-volume[2339399]: DEBUG oslo_concurrency.processutils [None req-c815772e-e5a8-458a-a573-9cf58fb40b2d None None] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix stack-volumes-lvmdriver-1 {{(pid=2339399) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Sep 20 12:46:12 datacore-PowerEdge-R740 sudo[2339694]:    stack : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/local/bin/cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix stack-volumes-lvmdriver-1
Sep 20 12:46:12 datacore-PowerEdge-R740 sudo[2339694]: pam_unix(sudo:session): session opened for user root by (uid=0)
Sep 20 12:46:13 datacore-PowerEdge-R740 sudo[2339694]: pam_unix(sudo:session): session closed for user root
Sep 20 12:46:13 datacore-PowerEdge-R740 cinder-volume[2339399]: DEBUG oslo_concurrency.processutils [None req-c815772e-e5a8-458a-a573-9cf58fb40b2d None None] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix stack-volumes-lvmdriver-1" returned: 0 in 0.702s {{(pid=2339399) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Sep 20 12:46:13 datacore-PowerEdge-R740 cinder-volume[2339399]: DEBUG oslo_concurrency.processutils [None req-c815772e-e5a8-458a-a573-9cf58fb40b2d None None] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1 {{(pid=2339399) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Sep 20 12:46:13 datacore-PowerEdge-R740 sudo[2339705]:    stack : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/local/bin/cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1
Sep 20 12:46:13 datacore-PowerEdge-R740 sudo[2339705]: pam_unix(sudo:session): session opened for user root by (uid=0)
Sep 20 12:46:14 datacore-PowerEdge-R740 sudo[2339705]: pam_unix(sudo:session): session closed for user root
Sep 20 12:46:14 datacore-PowerEdge-R740 cinder-volume[2339399]: DEBUG oslo_concurrency.processutils [None req-c815772e-e5a8-458a-a573-9cf58fb40b2d None None] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1" returned: 0 in 0.673s {{(pid=2339399) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Sep 20 12:46:14 datacore-PowerEdge-R740 cinder-volume[2339399]: DEBUG oslo_concurrency.processutils [None req-c815772e-e5a8-458a-a573-9cf58fb40b2d None None] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o size,data_percent --separator : --nosuffix /dev/stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool {{(pid=2339399) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Sep 20 12:46:14 datacore-PowerEdge-R740 sudo[2339711]:    stack : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/local/bin/cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o size,data_percent --separator : --nosuffix /dev/stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool
Sep 20 12:46:14 datacore-PowerEdge-R740 sudo[2339711]: pam_unix(sudo:session): session opened for user root by (uid=0)
Sep 20 12:46:14 datacore-PowerEdge-R740 sudo[2339711]: pam_unix(sudo:session): session closed for user root
Sep 20 12:46:14 datacore-PowerEdge-R740 cinder-volume[2339399]: DEBUG oslo_concurrency.processutils [None req-c815772e-e5a8-458a-a573-9cf58fb40b2d None None] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o size,data_percent --separator : --nosuffix /dev/stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool" returned: 0 in 0.616s {{(pid=2339399) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Sep 20 12:46:14 datacore-PowerEdge-R740 cinder-volume[2339399]: DEBUG oslo_concurrency.processutils [None req-c815772e-e5a8-458a-a573-9cf58fb40b2d None None] Running cmd (subprocess): env LC_ALL=C lvm version {{(pid=2339399) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Sep 20 12:46:14 datacore-PowerEdge-R740 cinder-volume[2339399]: DEBUG oslo_concurrency.processutils [None req-c815772e-e5a8-458a-a573-9cf58fb40b2d None None] CMD "env LC_ALL=C lvm version" returned: 0 in 0.019s {{(pid=2339399) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Sep 20 12:46:14 datacore-PowerEdge-R740 cinder-volume[2339399]: DEBUG oslo_concurrency.processutils [None req-c815772e-e5a8-458a-a573-9cf58fb40b2d None None] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool {{(pid=2339399) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Sep 20 12:46:14 datacore-PowerEdge-R740 sudo[2339716]:    stack : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/local/bin/cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool
Sep 20 12:46:14 datacore-PowerEdge-R740 sudo[2339716]: pam_unix(sudo:session): session opened for user root by (uid=0)
Sep 20 12:46:15 datacore-PowerEdge-R740 sudo[2339716]: pam_unix(sudo:session): session closed for user root
Sep 20 12:46:15 datacore-PowerEdge-R740 cinder-volume[2339399]: DEBUG oslo_concurrency.processutils [None req-c815772e-e5a8-458a-a573-9cf58fb40b2d None None] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool" returned: 0 in 0.619s {{(pid=2339399) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Sep 20 12:46:15 datacore-PowerEdge-R740 cinder-volume[2339399]: INFO cinder.volume.drivers.lvm [None req-c815772e-e5a8-458a-a573-9cf58fb40b2d None None] Enabling LVM thin provisioning by default because a thin pool exists.
Sep 20 12:46:15 datacore-PowerEdge-R740 cinder-volume[2339399]: DEBUG oslo_concurrency.processutils [None req-c815772e-e5a8-458a-a573-9cf58fb40b2d None None] Running cmd (subprocess): env LC_ALL=C lvm version {{(pid=2339399) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Sep 20 12:46:15 datacore-PowerEdge-R740 cinder-volume[2339399]: DEBUG oslo_concurrency.processutils [None req-c815772e-e5a8-458a-a573-9cf58fb40b2d None None] CMD "env LC_ALL=C lvm version" returned: 0 in 0.019s {{(pid=2339399) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Sep 20 12:46:15 datacore-PowerEdge-R740 cinder-volume[2339399]: DEBUG oslo_concurrency.processutils [None req-c815772e-e5a8-458a-a573-9cf58fb40b2d None None] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool {{(pid=2339399) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Sep 20 12:46:15 datacore-PowerEdge-R740 sudo[2339721]:    stack : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/local/bin/cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool
Sep 20 12:46:15 datacore-PowerEdge-R740 sudo[2339721]: pam_unix(sudo:session): session opened for user root by (uid=0)
Sep 20 12:46:15 datacore-PowerEdge-R740 sudo[2339721]: pam_unix(sudo:session): session closed for user root
Sep 20 12:46:15 datacore-PowerEdge-R740 cinder-volume[2339399]: DEBUG oslo_concurrency.processutils [None req-c815772e-e5a8-458a-a573-9cf58fb40b2d None None] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool" returned: 0 in 0.626s {{(pid=2339399) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Sep 20 12:46:15 datacore-PowerEdge-R740 cinder-volume[2339399]: DEBUG cinder.volume.drivers.lvm [None req-c815772e-e5a8-458a-a573-9cf58fb40b2d None None] Updating volume stats {{(pid=2339399) _update_volume_stats /opt/stack/cinder/cinder/volume/drivers/lvm.py:213}}
Sep 20 12:46:15 datacore-PowerEdge-R740 cinder-volume[2339399]: DEBUG oslo_concurrency.processutils [None req-c815772e-e5a8-458a-a573-9cf58fb40b2d None None] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix stack-volumes-lvmdriver-1 {{(pid=2339399) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Sep 20 12:46:15 datacore-PowerEdge-R740 sudo[2339736]:    stack : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/local/bin/cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix stack-volumes-lvmdriver-1
Sep 20 12:46:15 datacore-PowerEdge-R740 sudo[2339736]: pam_unix(sudo:session): session opened for user root by (uid=0)
Sep 20 12:46:16 datacore-PowerEdge-R740 sudo[2339736]: pam_unix(sudo:session): session closed for user root
Sep 20 12:46:16 datacore-PowerEdge-R740 cinder-volume[2339399]: DEBUG oslo_concurrency.processutils [None req-c815772e-e5a8-458a-a573-9cf58fb40b2d None None] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix stack-volumes-lvmdriver-1" returned: 0 in 0.655s {{(pid=2339399) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Sep 20 12:46:16 datacore-PowerEdge-R740 cinder-volume[2339399]: DEBUG oslo_concurrency.processutils [None req-c815772e-e5a8-458a-a573-9cf58fb40b2d None None] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1 {{(pid=2339399) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Sep 20 12:46:16 datacore-PowerEdge-R740 sudo[2339740]:    stack : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/local/bin/cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1
Sep 20 12:46:16 datacore-PowerEdge-R740 sudo[2339740]: pam_unix(sudo:session): session opened for user root by (uid=0)
Sep 20 12:46:17 datacore-PowerEdge-R740 sudo[2339740]: pam_unix(sudo:session): session closed for user root
Sep 20 12:46:17 datacore-PowerEdge-R740 cinder-volume[2339399]: DEBUG oslo_concurrency.processutils [None req-c815772e-e5a8-458a-a573-9cf58fb40b2d None None] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1" returned: 0 in 0.626s {{(pid=2339399) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Sep 20 12:46:17 datacore-PowerEdge-R740 cinder-volume[2339399]: DEBUG oslo_concurrency.processutils [None req-c815772e-e5a8-458a-a573-9cf58fb40b2d None None] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o size,data_percent --separator : --nosuffix /dev/stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool {{(pid=2339399) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Sep 20 12:46:17 datacore-PowerEdge-R740 sudo[2339749]:    stack : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/local/bin/cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o size,data_percent --separator : --nosuffix /dev/stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool
Sep 20 12:46:17 datacore-PowerEdge-R740 sudo[2339749]: pam_unix(sudo:session): session opened for user root by (uid=0)
Sep 20 12:46:17 datacore-PowerEdge-R740 cinder-volume[2339188]: DEBUG dbcounter [-] [2339188] Writing DB stats cinder:SELECT=16,cinder:UPDATE=1 {{(pid=2339188) stat_writer /usr/local/lib/python3.8/dist-packages/dbcounter.py:114}}
Sep 20 12:46:17 datacore-PowerEdge-R740 sudo[2339749]: pam_unix(sudo:session): session closed for user root
Sep 20 12:46:17 datacore-PowerEdge-R740 cinder-volume[2339399]: DEBUG oslo_concurrency.processutils [None req-c815772e-e5a8-458a-a573-9cf58fb40b2d None None] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o size,data_percent --separator : --nosuffix /dev/stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool" returned: 0 in 0.672s {{(pid=2339399) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Sep 20 12:46:17 datacore-PowerEdge-R740 cinder-volume[2339399]: DEBUG oslo_concurrency.processutils [None req-c815772e-e5a8-458a-a573-9cf58fb40b2d None None] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1 {{(pid=2339399) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Sep 20 12:46:17 datacore-PowerEdge-R740 sudo[2339762]:    stack : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/local/bin/cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1
Sep 20 12:46:17 datacore-PowerEdge-R740 sudo[2339762]: pam_unix(sudo:session): session opened for user root by (uid=0)
Sep 20 12:46:18 datacore-PowerEdge-R740 sudo[2339762]: pam_unix(sudo:session): session closed for user root
Sep 20 12:46:18 datacore-PowerEdge-R740 cinder-volume[2339399]: DEBUG oslo_concurrency.processutils [None req-c815772e-e5a8-458a-a573-9cf58fb40b2d None None] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1" returned: 0 in 0.643s {{(pid=2339399) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Sep 20 12:46:18 datacore-PowerEdge-R740 cinder-volume[2339399]: INFO cinder.volume.driver [None req-c815772e-e5a8-458a-a573-9cf58fb40b2d None None] Driver hasn't implemented _init_vendor_properties()
Sep 20 12:46:18 datacore-PowerEdge-R740 cinder-volume[2339399]: DEBUG cinder.volume.driver [None req-c815772e-e5a8-458a-a573-9cf58fb40b2d None None] Initialized capabilities list: {'volume_backend_name': 'lvmdriver-1', 'vendor_name': 'Open Source', 'driver_version': '3.0.0', 'storage_protocol': 'iSCSI', 'pools': [{'pool_name': 'lvmdriver-1', 'total_capacity_gb': 28.5, 'free_capacity_gb': 28.5, 'reserved_percentage': 0, 'location_info': 'LVMVolumeDriver:datacore-PowerEdge-R740:stack-volumes-lvmdriver-1:thin:0', 'QoS_support': False, 'provisioned_capacity_gb': 0.0, 'max_over_subscription_ratio': '20.0', 'thin_provisioning_support': True, 'thick_provisioning_support': False, 'total_volumes': 1, 'filter_function': None, 'goodness_function': None, 'multiattach': True, 'backend_state': 'up'}], 'shared_targets': False, 'sparse_copy_volume': True, 'properties': {'thin_provisioning': {'title': 'Thin Provisioning', 'description': 'Sets thin provisioning.', 'type': 'boolean'}, 'compression': {'title': 'Compression', 'description': 'Enables compression.', 'type': 'boolean'}, 'qos': {'title': 'QoS', 'description': 'Enables QoS.', 'type': 'boolean'}, 'replication_enabled': {'title': 'Replication', 'description': 'Enables replication.', 'type': 'boolean'}}}. {{(pid=2339399) init_capabilities /opt/stack/cinder/cinder/volume/driver.py:812}}
Sep 20 12:46:18 datacore-PowerEdge-R740 cinder-volume[2339399]: DEBUG oslo_db.sqlalchemy.engines [None req-c815772e-e5a8-458a-a573-9cf58fb40b2d None None] MySQL server mode set to STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_ENGINE_SUBSTITUTION {{(pid=2339399) _check_effective_sql_mode /usr/local/lib/python3.8/dist-packages/oslo_db/sqlalchemy/engines.py:314}}
Sep 20 12:46:18 datacore-PowerEdge-R740 cinder-volume[2339399]: DEBUG dbcounter [-] [2339399] Writer thread running {{(pid=2339399) stat_writer /usr/local/lib/python3.8/dist-packages/dbcounter.py:99}}
Sep 20 12:46:18 datacore-PowerEdge-R740 cinder-volume[2339399]: DEBUG cinder.db.sqlalchemy.api [None req-c815772e-e5a8-458a-a573-9cf58fb40b2d None None] Building query based on filter {{(pid=2339399) _process_snaps_filters /opt/stack/cinder/cinder/db/sqlalchemy/api.py:3878}}
Sep 20 12:46:18 datacore-PowerEdge-R740 cinder-volume[2339399]: DEBUG cinder.image.image_utils [None req-c815772e-e5a8-458a-a573-9cf58fb40b2d None None] Configuration image_conversion_dir is None or the path doesn't exist. {{(pid=2339399) cleanup_temporary_file /opt/stack/cinder/cinder/image/image_utils.py:991}}
Sep 20 12:46:18 datacore-PowerEdge-R740 cinder-volume[2339399]: DEBUG cinder.volume.drivers.lvm [None req-c815772e-e5a8-458a-a573-9cf58fb40b2d None None] Updating volume stats {{(pid=2339399) _update_volume_stats /opt/stack/cinder/cinder/volume/drivers/lvm.py:213}}
Sep 20 12:46:18 datacore-PowerEdge-R740 cinder-volume[2339399]: DEBUG oslo_concurrency.processutils [None req-c815772e-e5a8-458a-a573-9cf58fb40b2d None None] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix stack-volumes-lvmdriver-1 {{(pid=2339399) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Sep 20 12:46:18 datacore-PowerEdge-R740 sudo[2339768]:    stack : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/local/bin/cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix stack-volumes-lvmdriver-1
Sep 20 12:46:18 datacore-PowerEdge-R740 cinder-volume[2339399]: INFO cinder.keymgr.migration [None req-982676ca-ff16-4810-bfca-1b21f20bf156 None None] Not migrating encryption keys because the ConfKeyManager is still in use.
Sep 20 12:46:18 datacore-PowerEdge-R740 sudo[2339768]: pam_unix(sudo:session): session opened for user root by (uid=0)
Sep 20 12:46:19 datacore-PowerEdge-R740 sudo[2339768]: pam_unix(sudo:session): session closed for user root
Sep 20 12:46:19 datacore-PowerEdge-R740 cinder-volume[2339399]: DEBUG oslo_concurrency.processutils [None req-c815772e-e5a8-458a-a573-9cf58fb40b2d None None] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix stack-volumes-lvmdriver-1" returned: 0 in 0.643s {{(pid=2339399) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Sep 20 12:46:19 datacore-PowerEdge-R740 cinder-volume[2339399]: DEBUG oslo_concurrency.processutils [None req-c815772e-e5a8-458a-a573-9cf58fb40b2d None None] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1 {{(pid=2339399) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Sep 20 12:46:19 datacore-PowerEdge-R740 sudo[2339777]:    stack : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/local/bin/cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1
Sep 20 12:46:19 datacore-PowerEdge-R740 sudo[2339777]: pam_unix(sudo:session): session opened for user root by (uid=0)
Sep 20 12:46:19 datacore-PowerEdge-R740 sudo[2339777]: pam_unix(sudo:session): session closed for user root
Sep 20 12:46:19 datacore-PowerEdge-R740 cinder-volume[2339399]: DEBUG oslo_concurrency.processutils [None req-c815772e-e5a8-458a-a573-9cf58fb40b2d None None] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1" returned: 0 in 0.675s {{(pid=2339399) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Sep 20 12:46:19 datacore-PowerEdge-R740 cinder-volume[2339399]: DEBUG oslo_concurrency.processutils [None req-c815772e-e5a8-458a-a573-9cf58fb40b2d None None] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o size,data_percent --separator : --nosuffix /dev/stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool {{(pid=2339399) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Sep 20 12:46:19 datacore-PowerEdge-R740 sudo[2339799]:    stack : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/local/bin/cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o size,data_percent --separator : --nosuffix /dev/stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool
Sep 20 12:46:19 datacore-PowerEdge-R740 sudo[2339799]: pam_unix(sudo:session): session opened for user root by (uid=0)
Sep 20 12:46:20 datacore-PowerEdge-R740 sudo[2339799]: pam_unix(sudo:session): session closed for user root
Sep 20 12:46:20 datacore-PowerEdge-R740 cinder-volume[2339399]: DEBUG oslo_concurrency.processutils [None req-c815772e-e5a8-458a-a573-9cf58fb40b2d None None] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o size,data_percent --separator : --nosuffix /dev/stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool" returned: 0 in 0.631s {{(pid=2339399) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Sep 20 12:46:20 datacore-PowerEdge-R740 cinder-volume[2339399]: DEBUG oslo_concurrency.processutils [None req-c815772e-e5a8-458a-a573-9cf58fb40b2d None None] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1 {{(pid=2339399) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Sep 20 12:46:20 datacore-PowerEdge-R740 sudo[2339809]:    stack : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/local/bin/cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1
Sep 20 12:46:20 datacore-PowerEdge-R740 sudo[2339809]: pam_unix(sudo:session): session opened for user root by (uid=0)
Sep 20 12:46:21 datacore-PowerEdge-R740 sudo[2339809]: pam_unix(sudo:session): session closed for user root
Sep 20 12:46:21 datacore-PowerEdge-R740 cinder-volume[2339399]: DEBUG oslo_concurrency.processutils [None req-c815772e-e5a8-458a-a573-9cf58fb40b2d None None] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1" returned: 0 in 0.660s {{(pid=2339399) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Sep 20 12:46:21 datacore-PowerEdge-R740 cinder-volume[2339399]: DEBUG cinder.manager [None req-c815772e-e5a8-458a-a573-9cf58fb40b2d None None] Notifying Schedulers of capabilities ... {{(pid=2339399) _publish_service_capabilities /opt/stack/cinder/cinder/manager.py:202}}
Sep 20 12:46:21 datacore-PowerEdge-R740 cinder-volume[2339399]: INFO cinder.volume.manager [None req-c815772e-e5a8-458a-a573-9cf58fb40b2d None None] Driver initialization completed successfully.
Sep 20 12:46:21 datacore-PowerEdge-R740 cinder-volume[2339399]: INFO cinder.manager [None req-c815772e-e5a8-458a-a573-9cf58fb40b2d None None] Initiating service 2 cleanup
Sep 20 12:46:21 datacore-PowerEdge-R740 cinder-volume[2339399]: INFO cinder.manager [None req-c815772e-e5a8-458a-a573-9cf58fb40b2d None None] Service 2 cleanup completed.
Sep 20 12:46:21 datacore-PowerEdge-R740 cinder-volume[2339399]: DEBUG cinder.service [None req-c815772e-e5a8-458a-a573-9cf58fb40b2d None None] Creating RPC server for service cinder-volume {{(pid=2339399) start /opt/stack/cinder/cinder/service.py:231}}
Sep 20 12:46:21 datacore-PowerEdge-R740 cinder-volume[2339399]: DEBUG cinder.service [None req-c815772e-e5a8-458a-a573-9cf58fb40b2d None None] Pinning object versions for RPC server serializer to 1.39 {{(pid=2339399) start /opt/stack/cinder/cinder/service.py:237}}
Sep 20 12:46:21 datacore-PowerEdge-R740 cinder-volume[2339399]: INFO cinder.volume.manager [None req-c815772e-e5a8-458a-a573-9cf58fb40b2d None None] Initializing RPC dependent components of volume driver LVMVolumeDriver (3.0.0)
Sep 20 12:46:21 datacore-PowerEdge-R740 cinder-volume[2339399]: DEBUG cinder.volume.drivers.lvm [None req-c815772e-e5a8-458a-a573-9cf58fb40b2d None None] Updating volume stats {{(pid=2339399) _update_volume_stats /opt/stack/cinder/cinder/volume/drivers/lvm.py:213}}
Sep 20 12:46:21 datacore-PowerEdge-R740 cinder-volume[2339399]: DEBUG oslo_concurrency.processutils [None req-c815772e-e5a8-458a-a573-9cf58fb40b2d None None] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix stack-volumes-lvmdriver-1 {{(pid=2339399) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Sep 20 12:46:21 datacore-PowerEdge-R740 sudo[2339825]:    stack : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/local/bin/cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix stack-volumes-lvmdriver-1
Sep 20 12:46:21 datacore-PowerEdge-R740 sudo[2339825]: pam_unix(sudo:session): session opened for user root by (uid=0)
