-- Logs begin at Thu 2022-09-15 15:28:48 IST, end at Thu 2022-09-15 15:28:59 IST. --
Sep 15 15:28:49 datacore-PowerEdge-R740 sudo[2930368]: pam_unix(sudo:session): session closed for user root
Sep 15 15:28:49 datacore-PowerEdge-R740 cinder-volume[2930312]: DEBUG oslo_concurrency.processutils [None req-534b1a5c-d853-402f-9162-e846d53aecf1 None None] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool" returned: 0 in 1.050s {{(pid=2930312) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Sep 15 15:28:49 datacore-PowerEdge-R740 cinder-volume[2930312]: DEBUG oslo_concurrency.processutils [None req-534b1a5c-d853-402f-9162-e846d53aecf1 None None] Running cmd (subprocess): env LC_ALL=C lvm version {{(pid=2930312) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Sep 15 15:28:49 datacore-PowerEdge-R740 cinder-volume[2930312]: DEBUG oslo_concurrency.processutils [None req-534b1a5c-d853-402f-9162-e846d53aecf1 None None] CMD "env LC_ALL=C lvm version" returned: 0 in 0.019s {{(pid=2930312) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Sep 15 15:28:49 datacore-PowerEdge-R740 cinder-volume[2930312]: DEBUG oslo_concurrency.processutils [None req-534b1a5c-d853-402f-9162-e846d53aecf1 None None] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf lvchange -a y --yes -K stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool {{(pid=2930312) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Sep 15 15:28:49 datacore-PowerEdge-R740 sudo[2930407]:    stack : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/local/bin/cinder-rootwrap /etc/cinder/rootwrap.conf lvchange -a y --yes -K stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool
Sep 15 15:28:49 datacore-PowerEdge-R740 sudo[2930407]: pam_unix(sudo:session): session opened for user root by (uid=0)
Sep 15 15:28:50 datacore-PowerEdge-R740 sudo[2930407]: pam_unix(sudo:session): session closed for user root
Sep 15 15:28:50 datacore-PowerEdge-R740 cinder-volume[2930312]: DEBUG oslo_concurrency.processutils [None req-534b1a5c-d853-402f-9162-e846d53aecf1 None None] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf lvchange -a y --yes -K stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool" returned: 0 in 0.926s {{(pid=2930312) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Sep 15 15:28:50 datacore-PowerEdge-R740 cinder-volume[2930312]: DEBUG oslo_concurrency.processutils [None req-534b1a5c-d853-402f-9162-e846d53aecf1 None None] Running cmd (subprocess): env LC_ALL=C lvm version {{(pid=2930312) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Sep 15 15:28:50 datacore-PowerEdge-R740 cinder-volume[2930312]: DEBUG oslo_concurrency.processutils [None req-534b1a5c-d853-402f-9162-e846d53aecf1 None None] CMD "env LC_ALL=C lvm version" returned: 0 in 0.014s {{(pid=2930312) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Sep 15 15:28:50 datacore-PowerEdge-R740 cinder-volume[2930312]: DEBUG oslo_concurrency.processutils [None req-534b1a5c-d853-402f-9162-e846d53aecf1 None None] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C pvs --noheadings --unit=g -o vg_name,name,size,free --separator | --nosuffix --ignoreskippedcluster {{(pid=2930312) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Sep 15 15:28:50 datacore-PowerEdge-R740 sudo[2930545]:    stack : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/local/bin/cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C pvs --noheadings --unit=g -o vg_name,name,size,free --separator | --nosuffix --ignoreskippedcluster
Sep 15 15:28:50 datacore-PowerEdge-R740 sudo[2930545]: pam_unix(sudo:session): session opened for user root by (uid=0)
Sep 15 15:28:50 datacore-PowerEdge-R740 sudo[2930545]: pam_unix(sudo:session): session closed for user root
Sep 15 15:28:50 datacore-PowerEdge-R740 cinder-volume[2930312]: DEBUG oslo_concurrency.processutils [None req-534b1a5c-d853-402f-9162-e846d53aecf1 None None] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C pvs --noheadings --unit=g -o vg_name,name,size,free --separator | --nosuffix --ignoreskippedcluster" returned: 0 in 0.670s {{(pid=2930312) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Sep 15 15:28:50 datacore-PowerEdge-R740 cinder-volume[2930312]: DEBUG oslo_concurrency.processutils [None req-534b1a5c-d853-402f-9162-e846d53aecf1 None None] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix stack-volumes-lvmdriver-1 {{(pid=2930312) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Sep 15 15:28:50 datacore-PowerEdge-R740 sudo[2930583]:    stack : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/local/bin/cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix stack-volumes-lvmdriver-1
Sep 15 15:28:50 datacore-PowerEdge-R740 sudo[2930583]: pam_unix(sudo:session): session opened for user root by (uid=0)
Sep 15 15:28:51 datacore-PowerEdge-R740 sudo[2930583]: pam_unix(sudo:session): session closed for user root
Sep 15 15:28:51 datacore-PowerEdge-R740 cinder-volume[2930312]: DEBUG oslo_concurrency.processutils [None req-534b1a5c-d853-402f-9162-e846d53aecf1 None None] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix stack-volumes-lvmdriver-1" returned: 0 in 0.723s {{(pid=2930312) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Sep 15 15:28:51 datacore-PowerEdge-R740 cinder-volume[2930312]: DEBUG oslo_concurrency.processutils [None req-534b1a5c-d853-402f-9162-e846d53aecf1 None None] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix stack-volumes-lvmdriver-1 {{(pid=2930312) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Sep 15 15:28:51 datacore-PowerEdge-R740 sudo[2930610]:    stack : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/local/bin/cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix stack-volumes-lvmdriver-1
Sep 15 15:28:51 datacore-PowerEdge-R740 sudo[2930610]: pam_unix(sudo:session): session opened for user root by (uid=0)
Sep 15 15:28:52 datacore-PowerEdge-R740 sudo[2930610]: pam_unix(sudo:session): session closed for user root
Sep 15 15:28:52 datacore-PowerEdge-R740 cinder-volume[2930312]: DEBUG oslo_concurrency.processutils [None req-534b1a5c-d853-402f-9162-e846d53aecf1 None None] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix stack-volumes-lvmdriver-1" returned: 0 in 0.673s {{(pid=2930312) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Sep 15 15:28:52 datacore-PowerEdge-R740 cinder-volume[2930312]: DEBUG oslo_concurrency.processutils [None req-534b1a5c-d853-402f-9162-e846d53aecf1 None None] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1 {{(pid=2930312) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Sep 15 15:28:52 datacore-PowerEdge-R740 sudo[2930614]:    stack : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/local/bin/cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1
Sep 15 15:28:52 datacore-PowerEdge-R740 sudo[2930614]: pam_unix(sudo:session): session opened for user root by (uid=0)
Sep 15 15:28:52 datacore-PowerEdge-R740 sudo[2930614]: pam_unix(sudo:session): session closed for user root
Sep 15 15:28:52 datacore-PowerEdge-R740 cinder-volume[2930312]: DEBUG oslo_concurrency.processutils [None req-534b1a5c-d853-402f-9162-e846d53aecf1 None None] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1" returned: 0 in 0.637s {{(pid=2930312) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Sep 15 15:28:52 datacore-PowerEdge-R740 cinder-volume[2930312]: DEBUG oslo_concurrency.processutils [None req-534b1a5c-d853-402f-9162-e846d53aecf1 None None] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o size,data_percent --separator : --nosuffix /dev/stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool {{(pid=2930312) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Sep 15 15:28:52 datacore-PowerEdge-R740 sudo[2930618]:    stack : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/local/bin/cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o size,data_percent --separator : --nosuffix /dev/stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool
Sep 15 15:28:52 datacore-PowerEdge-R740 sudo[2930618]: pam_unix(sudo:session): session opened for user root by (uid=0)
Sep 15 15:28:53 datacore-PowerEdge-R740 sudo[2930618]: pam_unix(sudo:session): session closed for user root
Sep 15 15:28:53 datacore-PowerEdge-R740 cinder-volume[2930312]: DEBUG oslo_concurrency.processutils [None req-534b1a5c-d853-402f-9162-e846d53aecf1 None None] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o size,data_percent --separator : --nosuffix /dev/stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool" returned: 0 in 0.634s {{(pid=2930312) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Sep 15 15:28:53 datacore-PowerEdge-R740 cinder-volume[2930312]: DEBUG oslo_concurrency.processutils [None req-534b1a5c-d853-402f-9162-e846d53aecf1 None None] Running cmd (subprocess): env LC_ALL=C lvm version {{(pid=2930312) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Sep 15 15:28:53 datacore-PowerEdge-R740 cinder-volume[2930312]: DEBUG oslo_concurrency.processutils [None req-534b1a5c-d853-402f-9162-e846d53aecf1 None None] CMD "env LC_ALL=C lvm version" returned: 0 in 0.015s {{(pid=2930312) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Sep 15 15:28:53 datacore-PowerEdge-R740 cinder-volume[2930312]: DEBUG oslo_concurrency.processutils [None req-534b1a5c-d853-402f-9162-e846d53aecf1 None None] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool {{(pid=2930312) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Sep 15 15:28:53 datacore-PowerEdge-R740 sudo[2930626]:    stack : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/local/bin/cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool
Sep 15 15:28:53 datacore-PowerEdge-R740 sudo[2930626]: pam_unix(sudo:session): session opened for user root by (uid=0)
Sep 15 15:28:54 datacore-PowerEdge-R740 sudo[2930626]: pam_unix(sudo:session): session closed for user root
Sep 15 15:28:54 datacore-PowerEdge-R740 cinder-volume[2930312]: DEBUG oslo_concurrency.processutils [None req-534b1a5c-d853-402f-9162-e846d53aecf1 None None] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool" returned: 0 in 0.615s {{(pid=2930312) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Sep 15 15:28:54 datacore-PowerEdge-R740 cinder-volume[2930312]: INFO cinder.volume.drivers.lvm [None req-534b1a5c-d853-402f-9162-e846d53aecf1 None None] Enabling LVM thin provisioning by default because a thin pool exists.
Sep 15 15:28:54 datacore-PowerEdge-R740 cinder-volume[2930312]: DEBUG oslo_concurrency.processutils [None req-534b1a5c-d853-402f-9162-e846d53aecf1 None None] Running cmd (subprocess): env LC_ALL=C lvm version {{(pid=2930312) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Sep 15 15:28:54 datacore-PowerEdge-R740 cinder-volume[2930312]: DEBUG oslo_concurrency.processutils [None req-534b1a5c-d853-402f-9162-e846d53aecf1 None None] CMD "env LC_ALL=C lvm version" returned: 0 in 0.019s {{(pid=2930312) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Sep 15 15:28:54 datacore-PowerEdge-R740 cinder-volume[2930312]: DEBUG oslo_concurrency.processutils [None req-534b1a5c-d853-402f-9162-e846d53aecf1 None None] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool {{(pid=2930312) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Sep 15 15:28:54 datacore-PowerEdge-R740 sudo[2930641]:    stack : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/local/bin/cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool
Sep 15 15:28:54 datacore-PowerEdge-R740 sudo[2930641]: pam_unix(sudo:session): session opened for user root by (uid=0)
Sep 15 15:28:54 datacore-PowerEdge-R740 sudo[2930641]: pam_unix(sudo:session): session closed for user root
Sep 15 15:28:54 datacore-PowerEdge-R740 cinder-volume[2930312]: DEBUG oslo_concurrency.processutils [None req-534b1a5c-d853-402f-9162-e846d53aecf1 None None] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool" returned: 0 in 0.649s {{(pid=2930312) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Sep 15 15:28:54 datacore-PowerEdge-R740 cinder-volume[2930312]: DEBUG cinder.volume.drivers.lvm [None req-534b1a5c-d853-402f-9162-e846d53aecf1 None None] Updating volume stats {{(pid=2930312) _update_volume_stats /opt/stack/cinder/cinder/volume/drivers/lvm.py:213}}
Sep 15 15:28:54 datacore-PowerEdge-R740 cinder-volume[2930312]: DEBUG oslo_concurrency.processutils [None req-534b1a5c-d853-402f-9162-e846d53aecf1 None None] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix stack-volumes-lvmdriver-1 {{(pid=2930312) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Sep 15 15:28:54 datacore-PowerEdge-R740 sudo[2930646]:    stack : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/local/bin/cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix stack-volumes-lvmdriver-1
Sep 15 15:28:54 datacore-PowerEdge-R740 sudo[2930646]: pam_unix(sudo:session): session opened for user root by (uid=0)
Sep 15 15:28:55 datacore-PowerEdge-R740 sudo[2930646]: pam_unix(sudo:session): session closed for user root
Sep 15 15:28:55 datacore-PowerEdge-R740 cinder-volume[2930312]: DEBUG oslo_concurrency.processutils [None req-534b1a5c-d853-402f-9162-e846d53aecf1 None None] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix stack-volumes-lvmdriver-1" returned: 0 in 0.657s {{(pid=2930312) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Sep 15 15:28:55 datacore-PowerEdge-R740 cinder-volume[2930312]: DEBUG oslo_concurrency.processutils [None req-534b1a5c-d853-402f-9162-e846d53aecf1 None None] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1 {{(pid=2930312) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Sep 15 15:28:55 datacore-PowerEdge-R740 sudo[2930652]:    stack : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/local/bin/cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1
Sep 15 15:28:55 datacore-PowerEdge-R740 sudo[2930652]: pam_unix(sudo:session): session opened for user root by (uid=0)
Sep 15 15:28:56 datacore-PowerEdge-R740 sudo[2930652]: pam_unix(sudo:session): session closed for user root
Sep 15 15:28:56 datacore-PowerEdge-R740 cinder-volume[2930312]: DEBUG oslo_concurrency.processutils [None req-534b1a5c-d853-402f-9162-e846d53aecf1 None None] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1" returned: 0 in 0.696s {{(pid=2930312) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Sep 15 15:28:56 datacore-PowerEdge-R740 cinder-volume[2930312]: DEBUG oslo_concurrency.processutils [None req-534b1a5c-d853-402f-9162-e846d53aecf1 None None] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o size,data_percent --separator : --nosuffix /dev/stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool {{(pid=2930312) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Sep 15 15:28:56 datacore-PowerEdge-R740 sudo[2930659]:    stack : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/local/bin/cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o size,data_percent --separator : --nosuffix /dev/stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool
Sep 15 15:28:56 datacore-PowerEdge-R740 sudo[2930659]: pam_unix(sudo:session): session opened for user root by (uid=0)
Sep 15 15:28:56 datacore-PowerEdge-R740 sudo[2930659]: pam_unix(sudo:session): session closed for user root
Sep 15 15:28:56 datacore-PowerEdge-R740 cinder-volume[2930312]: DEBUG oslo_concurrency.processutils [None req-534b1a5c-d853-402f-9162-e846d53aecf1 None None] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o size,data_percent --separator : --nosuffix /dev/stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool" returned: 0 in 0.663s {{(pid=2930312) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Sep 15 15:28:56 datacore-PowerEdge-R740 cinder-volume[2930312]: DEBUG oslo_concurrency.processutils [None req-534b1a5c-d853-402f-9162-e846d53aecf1 None None] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1 {{(pid=2930312) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Sep 15 15:28:56 datacore-PowerEdge-R740 sudo[2930670]:    stack : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/local/bin/cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1
Sep 15 15:28:56 datacore-PowerEdge-R740 sudo[2930670]: pam_unix(sudo:session): session opened for user root by (uid=0)
Sep 15 15:28:56 datacore-PowerEdge-R740 cinder-volume[2930126]: DEBUG dbcounter [-] [2930126] Writing DB stats cinder:SELECT=16,cinder:UPDATE=1 {{(pid=2930126) stat_writer /usr/local/lib/python3.8/dist-packages/dbcounter.py:114}}
Sep 15 15:28:57 datacore-PowerEdge-R740 sudo[2930670]: pam_unix(sudo:session): session closed for user root
Sep 15 15:28:57 datacore-PowerEdge-R740 cinder-volume[2930312]: DEBUG oslo_concurrency.processutils [None req-534b1a5c-d853-402f-9162-e846d53aecf1 None None] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1" returned: 0 in 0.645s {{(pid=2930312) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Sep 15 15:28:57 datacore-PowerEdge-R740 cinder-volume[2930312]: INFO cinder.volume.driver [None req-534b1a5c-d853-402f-9162-e846d53aecf1 None None] Driver hasn't implemented _init_vendor_properties()
Sep 15 15:28:57 datacore-PowerEdge-R740 cinder-volume[2930312]: DEBUG cinder.volume.driver [None req-534b1a5c-d853-402f-9162-e846d53aecf1 None None] Initialized capabilities list: {'volume_backend_name': 'lvmdriver-1', 'vendor_name': 'Open Source', 'driver_version': '3.0.0', 'storage_protocol': 'iSCSI', 'pools': [{'pool_name': 'lvmdriver-1', 'total_capacity_gb': 28.5, 'free_capacity_gb': 28.5, 'reserved_percentage': 0, 'location_info': 'LVMVolumeDriver:datacore-PowerEdge-R740:stack-volumes-lvmdriver-1:thin:0', 'QoS_support': False, 'provisioned_capacity_gb': 0.0, 'max_over_subscription_ratio': '20.0', 'thin_provisioning_support': True, 'thick_provisioning_support': False, 'total_volumes': 1, 'filter_function': None, 'goodness_function': None, 'multiattach': True, 'backend_state': 'up'}], 'shared_targets': False, 'sparse_copy_volume': True, 'properties': {'thin_provisioning': {'title': 'Thin Provisioning', 'description': 'Sets thin provisioning.', 'type': 'boolean'}, 'compression': {'title': 'Compression', 'description': 'Enables compression.', 'type': 'boolean'}, 'qos': {'title': 'QoS', 'description': 'Enables QoS.', 'type': 'boolean'}, 'replication_enabled': {'title': 'Replication', 'description': 'Enables replication.', 'type': 'boolean'}}}. {{(pid=2930312) init_capabilities /opt/stack/cinder/cinder/volume/driver.py:820}}
Sep 15 15:28:57 datacore-PowerEdge-R740 cinder-volume[2930312]: DEBUG oslo_db.sqlalchemy.engines [None req-534b1a5c-d853-402f-9162-e846d53aecf1 None None] MySQL server mode set to STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_ENGINE_SUBSTITUTION {{(pid=2930312) _check_effective_sql_mode /usr/local/lib/python3.8/dist-packages/oslo_db/sqlalchemy/engines.py:314}}
Sep 15 15:28:57 datacore-PowerEdge-R740 cinder-volume[2930312]: DEBUG dbcounter [-] [2930312] Writer thread running {{(pid=2930312) stat_writer /usr/local/lib/python3.8/dist-packages/dbcounter.py:99}}
Sep 15 15:28:57 datacore-PowerEdge-R740 cinder-volume[2930312]: DEBUG cinder.db.sqlalchemy.api [None req-534b1a5c-d853-402f-9162-e846d53aecf1 None None] Building query based on filter {{(pid=2930312) _process_snaps_filters /opt/stack/cinder/cinder/db/sqlalchemy/api.py:3156}}
Sep 15 15:28:57 datacore-PowerEdge-R740 cinder-volume[2930312]: DEBUG cinder.image.image_utils [None req-534b1a5c-d853-402f-9162-e846d53aecf1 None None] Configuration image_conversion_dir is None or the path doesn't exist. {{(pid=2930312) cleanup_temporary_file /opt/stack/cinder/cinder/image/image_utils.py:955}}
Sep 15 15:28:57 datacore-PowerEdge-R740 cinder-volume[2930312]: DEBUG cinder.volume.drivers.lvm [None req-534b1a5c-d853-402f-9162-e846d53aecf1 None None] Updating volume stats {{(pid=2930312) _update_volume_stats /opt/stack/cinder/cinder/volume/drivers/lvm.py:213}}
Sep 15 15:28:57 datacore-PowerEdge-R740 cinder-volume[2930312]: DEBUG oslo_concurrency.processutils [None req-534b1a5c-d853-402f-9162-e846d53aecf1 None None] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix stack-volumes-lvmdriver-1 {{(pid=2930312) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Sep 15 15:28:57 datacore-PowerEdge-R740 sudo[2930680]:    stack : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/local/bin/cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix stack-volumes-lvmdriver-1
Sep 15 15:28:57 datacore-PowerEdge-R740 sudo[2930680]: pam_unix(sudo:session): session opened for user root by (uid=0)
Sep 15 15:28:57 datacore-PowerEdge-R740 cinder-volume[2930312]: INFO cinder.keymgr.migration [None req-ec8dca93-2a52-4772-b5b3-22dc9956a378 None None] Not migrating encryption keys because the ConfKeyManager is still in use.
Sep 15 15:28:58 datacore-PowerEdge-R740 sudo[2930680]: pam_unix(sudo:session): session closed for user root
Sep 15 15:28:58 datacore-PowerEdge-R740 cinder-volume[2930312]: DEBUG oslo_concurrency.processutils [None req-534b1a5c-d853-402f-9162-e846d53aecf1 None None] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix stack-volumes-lvmdriver-1" returned: 0 in 0.641s {{(pid=2930312) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Sep 15 15:28:58 datacore-PowerEdge-R740 cinder-volume[2930312]: DEBUG oslo_concurrency.processutils [None req-534b1a5c-d853-402f-9162-e846d53aecf1 None None] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1 {{(pid=2930312) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Sep 15 15:28:58 datacore-PowerEdge-R740 sudo[2930701]:    stack : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/local/bin/cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1
Sep 15 15:28:58 datacore-PowerEdge-R740 sudo[2930701]: pam_unix(sudo:session): session opened for user root by (uid=0)
Sep 15 15:28:58 datacore-PowerEdge-R740 sudo[2930701]: pam_unix(sudo:session): session closed for user root
Sep 15 15:28:58 datacore-PowerEdge-R740 cinder-volume[2930312]: DEBUG oslo_concurrency.processutils [None req-534b1a5c-d853-402f-9162-e846d53aecf1 None None] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1" returned: 0 in 0.662s {{(pid=2930312) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Sep 15 15:28:58 datacore-PowerEdge-R740 cinder-volume[2930312]: DEBUG oslo_concurrency.processutils [None req-534b1a5c-d853-402f-9162-e846d53aecf1 None None] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o size,data_percent --separator : --nosuffix /dev/stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool {{(pid=2930312) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Sep 15 15:28:58 datacore-PowerEdge-R740 sudo[2930706]:    stack : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/local/bin/cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o size,data_percent --separator : --nosuffix /dev/stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool
Sep 15 15:28:58 datacore-PowerEdge-R740 sudo[2930706]: pam_unix(sudo:session): session opened for user root by (uid=0)
Sep 15 15:28:59 datacore-PowerEdge-R740 sudo[2930706]: pam_unix(sudo:session): session closed for user root
Sep 15 15:28:59 datacore-PowerEdge-R740 cinder-volume[2930312]: DEBUG oslo_concurrency.processutils [None req-534b1a5c-d853-402f-9162-e846d53aecf1 None None] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o size,data_percent --separator : --nosuffix /dev/stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool" returned: 0 in 0.629s {{(pid=2930312) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Sep 15 15:28:59 datacore-PowerEdge-R740 cinder-volume[2930312]: DEBUG oslo_concurrency.processutils [None req-534b1a5c-d853-402f-9162-e846d53aecf1 None None] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1 {{(pid=2930312) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Sep 15 15:28:59 datacore-PowerEdge-R740 sudo[2930715]:    stack : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/local/bin/cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1
Sep 15 15:28:59 datacore-PowerEdge-R740 sudo[2930715]: pam_unix(sudo:session): session opened for user root by (uid=0)
