-- Logs begin at Thu 2022-09-29 19:19:29 IST, end at Thu 2022-09-29 19:19:39 IST. --
Sep 29 19:19:30 datacore-PowerEdge-R740 sudo[1348024]: pam_unix(sudo:session): session closed for user root
Sep 29 19:19:30 datacore-PowerEdge-R740 cinder-volume[1347869]: DEBUG oslo_concurrency.processutils [None req-39e1c8c1-d8f3-4473-a337-ca6170216f1b None None] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C pvs --noheadings --unit=g -o vg_name,name,size,free --separator | --nosuffix --ignoreskippedcluster" returned: 0 in 0.753s {{(pid=1347869) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Sep 29 19:19:30 datacore-PowerEdge-R740 cinder-volume[1347869]: DEBUG oslo_concurrency.processutils [None req-39e1c8c1-d8f3-4473-a337-ca6170216f1b None None] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix stack-volumes-lvmdriver-1 {{(pid=1347869) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Sep 29 19:19:30 datacore-PowerEdge-R740 sudo[1348140]:    stack : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/local/bin/cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix stack-volumes-lvmdriver-1
Sep 29 19:19:30 datacore-PowerEdge-R740 sudo[1348140]: pam_unix(sudo:session): session opened for user root by (uid=0)
Sep 29 19:19:31 datacore-PowerEdge-R740 sudo[1348140]: pam_unix(sudo:session): session closed for user root
Sep 29 19:19:31 datacore-PowerEdge-R740 cinder-volume[1347869]: DEBUG oslo_concurrency.processutils [None req-39e1c8c1-d8f3-4473-a337-ca6170216f1b None None] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix stack-volumes-lvmdriver-1" returned: 0 in 0.718s {{(pid=1347869) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Sep 29 19:19:31 datacore-PowerEdge-R740 cinder-volume[1347869]: DEBUG oslo_concurrency.processutils [None req-39e1c8c1-d8f3-4473-a337-ca6170216f1b None None] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix stack-volumes-lvmdriver-1 {{(pid=1347869) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Sep 29 19:19:31 datacore-PowerEdge-R740 sudo[1348178]:    stack : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/local/bin/cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix stack-volumes-lvmdriver-1
Sep 29 19:19:31 datacore-PowerEdge-R740 sudo[1348178]: pam_unix(sudo:session): session opened for user root by (uid=0)
Sep 29 19:19:31 datacore-PowerEdge-R740 sudo[1348178]: pam_unix(sudo:session): session closed for user root
Sep 29 19:19:31 datacore-PowerEdge-R740 cinder-volume[1347869]: DEBUG oslo_concurrency.processutils [None req-39e1c8c1-d8f3-4473-a337-ca6170216f1b None None] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix stack-volumes-lvmdriver-1" returned: 0 in 0.642s {{(pid=1347869) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Sep 29 19:19:31 datacore-PowerEdge-R740 cinder-volume[1347869]: DEBUG oslo_concurrency.processutils [None req-39e1c8c1-d8f3-4473-a337-ca6170216f1b None None] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1 {{(pid=1347869) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Sep 29 19:19:31 datacore-PowerEdge-R740 sudo[1348184]:    stack : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/local/bin/cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1
Sep 29 19:19:31 datacore-PowerEdge-R740 sudo[1348184]: pam_unix(sudo:session): session opened for user root by (uid=0)
Sep 29 19:19:32 datacore-PowerEdge-R740 sudo[1348184]: pam_unix(sudo:session): session closed for user root
Sep 29 19:19:32 datacore-PowerEdge-R740 cinder-volume[1347869]: DEBUG oslo_concurrency.processutils [None req-39e1c8c1-d8f3-4473-a337-ca6170216f1b None None] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1" returned: 0 in 0.668s {{(pid=1347869) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Sep 29 19:19:32 datacore-PowerEdge-R740 cinder-volume[1347869]: DEBUG oslo_concurrency.processutils [None req-39e1c8c1-d8f3-4473-a337-ca6170216f1b None None] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o size,data_percent --separator : --nosuffix /dev/stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool {{(pid=1347869) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Sep 29 19:19:32 datacore-PowerEdge-R740 sudo[1348188]:    stack : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/local/bin/cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o size,data_percent --separator : --nosuffix /dev/stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool
Sep 29 19:19:32 datacore-PowerEdge-R740 sudo[1348188]: pam_unix(sudo:session): session opened for user root by (uid=0)
Sep 29 19:19:33 datacore-PowerEdge-R740 sudo[1348188]: pam_unix(sudo:session): session closed for user root
Sep 29 19:19:33 datacore-PowerEdge-R740 cinder-volume[1347869]: DEBUG oslo_concurrency.processutils [None req-39e1c8c1-d8f3-4473-a337-ca6170216f1b None None] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o size,data_percent --separator : --nosuffix /dev/stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool" returned: 0 in 0.648s {{(pid=1347869) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Sep 29 19:19:33 datacore-PowerEdge-R740 cinder-volume[1347869]: DEBUG oslo_concurrency.processutils [None req-39e1c8c1-d8f3-4473-a337-ca6170216f1b None None] Running cmd (subprocess): env LC_ALL=C lvm version {{(pid=1347869) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Sep 29 19:19:33 datacore-PowerEdge-R740 cinder-volume[1347869]: DEBUG oslo_concurrency.processutils [None req-39e1c8c1-d8f3-4473-a337-ca6170216f1b None None] CMD "env LC_ALL=C lvm version" returned: 0 in 0.017s {{(pid=1347869) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Sep 29 19:19:33 datacore-PowerEdge-R740 cinder-volume[1347869]: DEBUG oslo_concurrency.processutils [None req-39e1c8c1-d8f3-4473-a337-ca6170216f1b None None] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool {{(pid=1347869) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Sep 29 19:19:33 datacore-PowerEdge-R740 sudo[1348195]:    stack : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/local/bin/cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool
Sep 29 19:19:33 datacore-PowerEdge-R740 sudo[1348195]: pam_unix(sudo:session): session opened for user root by (uid=0)
Sep 29 19:19:33 datacore-PowerEdge-R740 sudo[1348195]: pam_unix(sudo:session): session closed for user root
Sep 29 19:19:33 datacore-PowerEdge-R740 cinder-volume[1347869]: DEBUG oslo_concurrency.processutils [None req-39e1c8c1-d8f3-4473-a337-ca6170216f1b None None] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool" returned: 0 in 0.624s {{(pid=1347869) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Sep 29 19:19:33 datacore-PowerEdge-R740 cinder-volume[1347869]: INFO cinder.volume.drivers.lvm [None req-39e1c8c1-d8f3-4473-a337-ca6170216f1b None None] Enabling LVM thin provisioning by default because a thin pool exists.
Sep 29 19:19:33 datacore-PowerEdge-R740 cinder-volume[1347869]: DEBUG oslo_concurrency.processutils [None req-39e1c8c1-d8f3-4473-a337-ca6170216f1b None None] Running cmd (subprocess): env LC_ALL=C lvm version {{(pid=1347869) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Sep 29 19:19:33 datacore-PowerEdge-R740 cinder-volume[1347869]: DEBUG oslo_concurrency.processutils [None req-39e1c8c1-d8f3-4473-a337-ca6170216f1b None None] CMD "env LC_ALL=C lvm version" returned: 0 in 0.016s {{(pid=1347869) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Sep 29 19:19:33 datacore-PowerEdge-R740 cinder-volume[1347869]: DEBUG oslo_concurrency.processutils [None req-39e1c8c1-d8f3-4473-a337-ca6170216f1b None None] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool {{(pid=1347869) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Sep 29 19:19:33 datacore-PowerEdge-R740 sudo[1348200]:    stack : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/local/bin/cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool
Sep 29 19:19:33 datacore-PowerEdge-R740 sudo[1348200]: pam_unix(sudo:session): session opened for user root by (uid=0)
Sep 29 19:19:34 datacore-PowerEdge-R740 sudo[1348200]: pam_unix(sudo:session): session closed for user root
Sep 29 19:19:34 datacore-PowerEdge-R740 cinder-volume[1347869]: DEBUG oslo_concurrency.processutils [None req-39e1c8c1-d8f3-4473-a337-ca6170216f1b None None] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool" returned: 0 in 0.640s {{(pid=1347869) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Sep 29 19:19:34 datacore-PowerEdge-R740 cinder-volume[1347869]: DEBUG cinder.volume.drivers.lvm [None req-39e1c8c1-d8f3-4473-a337-ca6170216f1b None None] Updating volume stats {{(pid=1347869) _update_volume_stats /opt/stack/cinder/cinder/volume/drivers/lvm.py:213}}
Sep 29 19:19:34 datacore-PowerEdge-R740 cinder-volume[1347869]: DEBUG oslo_concurrency.processutils [None req-39e1c8c1-d8f3-4473-a337-ca6170216f1b None None] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix stack-volumes-lvmdriver-1 {{(pid=1347869) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Sep 29 19:19:34 datacore-PowerEdge-R740 sudo[1348215]:    stack : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/local/bin/cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix stack-volumes-lvmdriver-1
Sep 29 19:19:34 datacore-PowerEdge-R740 sudo[1348215]: pam_unix(sudo:session): session opened for user root by (uid=0)
Sep 29 19:19:35 datacore-PowerEdge-R740 sudo[1348215]: pam_unix(sudo:session): session closed for user root
Sep 29 19:19:35 datacore-PowerEdge-R740 cinder-volume[1347869]: DEBUG oslo_concurrency.processutils [None req-39e1c8c1-d8f3-4473-a337-ca6170216f1b None None] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix stack-volumes-lvmdriver-1" returned: 0 in 0.642s {{(pid=1347869) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Sep 29 19:19:35 datacore-PowerEdge-R740 cinder-volume[1347869]: DEBUG oslo_concurrency.processutils [None req-39e1c8c1-d8f3-4473-a337-ca6170216f1b None None] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1 {{(pid=1347869) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Sep 29 19:19:35 datacore-PowerEdge-R740 sudo[1348223]:    stack : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/local/bin/cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1
Sep 29 19:19:35 datacore-PowerEdge-R740 sudo[1348223]: pam_unix(sudo:session): session opened for user root by (uid=0)
Sep 29 19:19:35 datacore-PowerEdge-R740 sudo[1348223]: pam_unix(sudo:session): session closed for user root
Sep 29 19:19:35 datacore-PowerEdge-R740 cinder-volume[1347869]: DEBUG oslo_concurrency.processutils [None req-39e1c8c1-d8f3-4473-a337-ca6170216f1b None None] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1" returned: 0 in 0.642s {{(pid=1347869) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Sep 29 19:19:35 datacore-PowerEdge-R740 cinder-volume[1347869]: DEBUG oslo_concurrency.processutils [None req-39e1c8c1-d8f3-4473-a337-ca6170216f1b None None] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o size,data_percent --separator : --nosuffix /dev/stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool {{(pid=1347869) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Sep 29 19:19:35 datacore-PowerEdge-R740 sudo[1348231]:    stack : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/local/bin/cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o size,data_percent --separator : --nosuffix /dev/stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool
Sep 29 19:19:35 datacore-PowerEdge-R740 sudo[1348231]: pam_unix(sudo:session): session opened for user root by (uid=0)
Sep 29 19:19:36 datacore-PowerEdge-R740 cinder-volume[1347551]: DEBUG dbcounter [-] [1347551] Writing DB stats cinder:SELECT=16,cinder:UPDATE=1 {{(pid=1347551) stat_writer /usr/local/lib/python3.8/dist-packages/dbcounter.py:114}}
Sep 29 19:19:36 datacore-PowerEdge-R740 sudo[1348231]: pam_unix(sudo:session): session closed for user root
Sep 29 19:19:36 datacore-PowerEdge-R740 cinder-volume[1347869]: DEBUG oslo_concurrency.processutils [None req-39e1c8c1-d8f3-4473-a337-ca6170216f1b None None] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o size,data_percent --separator : --nosuffix /dev/stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool" returned: 0 in 0.661s {{(pid=1347869) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Sep 29 19:19:36 datacore-PowerEdge-R740 cinder-volume[1347869]: DEBUG oslo_concurrency.processutils [None req-39e1c8c1-d8f3-4473-a337-ca6170216f1b None None] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1 {{(pid=1347869) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Sep 29 19:19:36 datacore-PowerEdge-R740 sudo[1348241]:    stack : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/local/bin/cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1
Sep 29 19:19:36 datacore-PowerEdge-R740 sudo[1348241]: pam_unix(sudo:session): session opened for user root by (uid=0)
Sep 29 19:19:36 datacore-PowerEdge-R740 sudo[1348241]: pam_unix(sudo:session): session closed for user root
Sep 29 19:19:36 datacore-PowerEdge-R740 cinder-volume[1347869]: DEBUG oslo_concurrency.processutils [None req-39e1c8c1-d8f3-4473-a337-ca6170216f1b None None] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1" returned: 0 in 0.653s {{(pid=1347869) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Sep 29 19:19:37 datacore-PowerEdge-R740 cinder-volume[1347869]: INFO cinder.volume.driver [None req-39e1c8c1-d8f3-4473-a337-ca6170216f1b None None] Driver hasn't implemented _init_vendor_properties()
Sep 29 19:19:37 datacore-PowerEdge-R740 cinder-volume[1347869]: DEBUG cinder.volume.driver [None req-39e1c8c1-d8f3-4473-a337-ca6170216f1b None None] Initialized capabilities list: {'volume_backend_name': 'lvmdriver-1', 'vendor_name': 'Open Source', 'driver_version': '3.0.0', 'storage_protocol': 'iSCSI', 'pools': [{'pool_name': 'lvmdriver-1', 'total_capacity_gb': 28.5, 'free_capacity_gb': 28.5, 'reserved_percentage': 0, 'location_info': 'LVMVolumeDriver:datacore-PowerEdge-R740:stack-volumes-lvmdriver-1:thin:0', 'QoS_support': False, 'provisioned_capacity_gb': 0.0, 'max_over_subscription_ratio': '20.0', 'thin_provisioning_support': True, 'thick_provisioning_support': False, 'total_volumes': 1, 'filter_function': None, 'goodness_function': None, 'multiattach': True, 'backend_state': 'up'}], 'shared_targets': False, 'sparse_copy_volume': True, 'properties': {'thin_provisioning': {'title': 'Thin Provisioning', 'description': 'Sets thin provisioning.', 'type': 'boolean'}, 'compression': {'title': 'Compression', 'description': 'Enables compression.', 'type': 'boolean'}, 'qos': {'title': 'QoS', 'description': 'Enables QoS.', 'type': 'boolean'}, 'replication_enabled': {'title': 'Replication', 'description': 'Enables replication.', 'type': 'boolean'}}}. {{(pid=1347869) init_capabilities /opt/stack/cinder/cinder/volume/driver.py:820}}
Sep 29 19:19:37 datacore-PowerEdge-R740 cinder-volume[1347869]: DEBUG oslo_db.sqlalchemy.engines [None req-39e1c8c1-d8f3-4473-a337-ca6170216f1b None None] MySQL server mode set to STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_ENGINE_SUBSTITUTION {{(pid=1347869) _check_effective_sql_mode /usr/local/lib/python3.8/dist-packages/oslo_db/sqlalchemy/engines.py:314}}
Sep 29 19:19:37 datacore-PowerEdge-R740 cinder-volume[1347869]: DEBUG dbcounter [-] [1347869] Writer thread running {{(pid=1347869) stat_writer /usr/local/lib/python3.8/dist-packages/dbcounter.py:99}}
Sep 29 19:19:37 datacore-PowerEdge-R740 cinder-volume[1347869]: DEBUG cinder.db.sqlalchemy.api [None req-39e1c8c1-d8f3-4473-a337-ca6170216f1b None None] Building query based on filter {{(pid=1347869) _process_snaps_filters /opt/stack/cinder/cinder/db/sqlalchemy/api.py:3156}}
Sep 29 19:19:37 datacore-PowerEdge-R740 cinder-volume[1347869]: DEBUG cinder.image.image_utils [None req-39e1c8c1-d8f3-4473-a337-ca6170216f1b None None] Configuration image_conversion_dir is None or the path doesn't exist. {{(pid=1347869) cleanup_temporary_file /opt/stack/cinder/cinder/image/image_utils.py:955}}
Sep 29 19:19:37 datacore-PowerEdge-R740 cinder-volume[1347869]: DEBUG cinder.volume.drivers.lvm [None req-39e1c8c1-d8f3-4473-a337-ca6170216f1b None None] Updating volume stats {{(pid=1347869) _update_volume_stats /opt/stack/cinder/cinder/volume/drivers/lvm.py:213}}
Sep 29 19:19:37 datacore-PowerEdge-R740 cinder-volume[1347869]: DEBUG oslo_concurrency.processutils [None req-39e1c8c1-d8f3-4473-a337-ca6170216f1b None None] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix stack-volumes-lvmdriver-1 {{(pid=1347869) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Sep 29 19:19:37 datacore-PowerEdge-R740 cinder-volume[1347869]: INFO cinder.keymgr.migration [None req-364258f9-6369-4a66-a990-c3f5a61712ee None None] Not migrating encryption keys because the ConfKeyManager is still in use.
Sep 29 19:19:37 datacore-PowerEdge-R740 sudo[1348247]:    stack : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/local/bin/cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix stack-volumes-lvmdriver-1
Sep 29 19:19:37 datacore-PowerEdge-R740 sudo[1348247]: pam_unix(sudo:session): session opened for user root by (uid=0)
Sep 29 19:19:37 datacore-PowerEdge-R740 sudo[1348247]: pam_unix(sudo:session): session closed for user root
Sep 29 19:19:37 datacore-PowerEdge-R740 cinder-volume[1347869]: DEBUG oslo_concurrency.processutils [None req-39e1c8c1-d8f3-4473-a337-ca6170216f1b None None] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix stack-volumes-lvmdriver-1" returned: 0 in 0.635s {{(pid=1347869) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Sep 29 19:19:37 datacore-PowerEdge-R740 cinder-volume[1347869]: DEBUG oslo_concurrency.processutils [None req-39e1c8c1-d8f3-4473-a337-ca6170216f1b None None] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1 {{(pid=1347869) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Sep 29 19:19:37 datacore-PowerEdge-R740 sudo[1348254]:    stack : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/local/bin/cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1
Sep 29 19:19:37 datacore-PowerEdge-R740 sudo[1348254]: pam_unix(sudo:session): session opened for user root by (uid=0)
Sep 29 19:19:38 datacore-PowerEdge-R740 sudo[1348254]: pam_unix(sudo:session): session closed for user root
Sep 29 19:19:38 datacore-PowerEdge-R740 cinder-volume[1347869]: DEBUG oslo_concurrency.processutils [None req-39e1c8c1-d8f3-4473-a337-ca6170216f1b None None] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1" returned: 0 in 0.639s {{(pid=1347869) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Sep 29 19:19:38 datacore-PowerEdge-R740 cinder-volume[1347869]: DEBUG oslo_concurrency.processutils [None req-39e1c8c1-d8f3-4473-a337-ca6170216f1b None None] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o size,data_percent --separator : --nosuffix /dev/stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool {{(pid=1347869) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Sep 29 19:19:38 datacore-PowerEdge-R740 sudo[1348279]:    stack : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/local/bin/cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o size,data_percent --separator : --nosuffix /dev/stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool
Sep 29 19:19:38 datacore-PowerEdge-R740 sudo[1348279]: pam_unix(sudo:session): session opened for user root by (uid=0)
Sep 29 19:19:38 datacore-PowerEdge-R740 sudo[1348279]: pam_unix(sudo:session): session closed for user root
Sep 29 19:19:38 datacore-PowerEdge-R740 cinder-volume[1347869]: DEBUG oslo_concurrency.processutils [None req-39e1c8c1-d8f3-4473-a337-ca6170216f1b None None] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o size,data_percent --separator : --nosuffix /dev/stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool" returned: 0 in 0.650s {{(pid=1347869) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Sep 29 19:19:38 datacore-PowerEdge-R740 cinder-volume[1347869]: DEBUG oslo_concurrency.processutils [None req-39e1c8c1-d8f3-4473-a337-ca6170216f1b None None] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1 {{(pid=1347869) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Sep 29 19:19:38 datacore-PowerEdge-R740 sudo[1348283]:    stack : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/local/bin/cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1
Sep 29 19:19:38 datacore-PowerEdge-R740 sudo[1348283]: pam_unix(sudo:session): session opened for user root by (uid=0)
Sep 29 19:19:39 datacore-PowerEdge-R740 sudo[1348283]: pam_unix(sudo:session): session closed for user root
Sep 29 19:19:39 datacore-PowerEdge-R740 cinder-volume[1347869]: DEBUG oslo_concurrency.processutils [None req-39e1c8c1-d8f3-4473-a337-ca6170216f1b None None] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1" returned: 0 in 0.644s {{(pid=1347869) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Sep 29 19:19:39 datacore-PowerEdge-R740 cinder-volume[1347869]: DEBUG cinder.manager [None req-39e1c8c1-d8f3-4473-a337-ca6170216f1b None None] Notifying Schedulers of capabilities ... {{(pid=1347869) _publish_service_capabilities /opt/stack/cinder/cinder/manager.py:202}}
Sep 29 19:19:39 datacore-PowerEdge-R740 cinder-volume[1347869]: INFO cinder.volume.manager [None req-39e1c8c1-d8f3-4473-a337-ca6170216f1b None None] Driver initialization completed successfully.
Sep 29 19:19:39 datacore-PowerEdge-R740 cinder-volume[1347869]: INFO cinder.manager [None req-39e1c8c1-d8f3-4473-a337-ca6170216f1b None None] Initiating service 2 cleanup
Sep 29 19:19:39 datacore-PowerEdge-R740 cinder-volume[1347869]: INFO cinder.manager [None req-39e1c8c1-d8f3-4473-a337-ca6170216f1b None None] Service 2 cleanup completed.
Sep 29 19:19:39 datacore-PowerEdge-R740 cinder-volume[1347869]: DEBUG cinder.service [None req-39e1c8c1-d8f3-4473-a337-ca6170216f1b None None] Creating RPC server for service cinder-volume {{(pid=1347869) start /opt/stack/cinder/cinder/service.py:231}}
Sep 29 19:19:39 datacore-PowerEdge-R740 cinder-volume[1347869]: DEBUG cinder.service [None req-39e1c8c1-d8f3-4473-a337-ca6170216f1b None None] Pinning object versions for RPC server serializer to 1.39 {{(pid=1347869) start /opt/stack/cinder/cinder/service.py:237}}
Sep 29 19:19:39 datacore-PowerEdge-R740 cinder-volume[1347869]: INFO cinder.volume.manager [None req-39e1c8c1-d8f3-4473-a337-ca6170216f1b None None] Initializing RPC dependent components of volume driver LVMVolumeDriver (3.0.0)
Sep 29 19:19:39 datacore-PowerEdge-R740 cinder-volume[1347869]: DEBUG cinder.volume.drivers.lvm [None req-39e1c8c1-d8f3-4473-a337-ca6170216f1b None None] Updating volume stats {{(pid=1347869) _update_volume_stats /opt/stack/cinder/cinder/volume/drivers/lvm.py:213}}
Sep 29 19:19:39 datacore-PowerEdge-R740 cinder-volume[1347869]: DEBUG oslo_concurrency.processutils [None req-39e1c8c1-d8f3-4473-a337-ca6170216f1b None None] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix stack-volumes-lvmdriver-1 {{(pid=1347869) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Sep 29 19:19:39 datacore-PowerEdge-R740 sudo[1348300]:    stack : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/local/bin/cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix stack-volumes-lvmdriver-1
Sep 29 19:19:39 datacore-PowerEdge-R740 sudo[1348300]: pam_unix(sudo:session): session opened for user root by (uid=0)
