-- Logs begin at Thu 2022-08-25 01:17:56 IST, end at Thu 2022-08-25 01:19:11 IST. --
Aug 25 01:17:56 datacore-PowerEdge-R740 sudo[2204409]: pam_unix(sudo:session): session closed for user root
Aug 25 01:17:56 datacore-PowerEdge-R740 cinder-volume[2204100]: DEBUG oslo_concurrency.processutils [None req-3955998a-c85e-4632-bf56-c79450d01f74 None None] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o size,data_percent --separator : --nosuffix /dev/stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool" returned: 0 in 0.711s {{(pid=2204100) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Aug 25 01:17:56 datacore-PowerEdge-R740 cinder-volume[2204100]: DEBUG oslo_concurrency.processutils [None req-3955998a-c85e-4632-bf56-c79450d01f74 None None] Running cmd (subprocess): env LC_ALL=C lvm version {{(pid=2204100) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Aug 25 01:17:56 datacore-PowerEdge-R740 cinder-volume[2204100]: DEBUG oslo_concurrency.processutils [None req-3955998a-c85e-4632-bf56-c79450d01f74 None None] CMD "env LC_ALL=C lvm version" returned: 0 in 0.016s {{(pid=2204100) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Aug 25 01:17:56 datacore-PowerEdge-R740 cinder-volume[2204100]: DEBUG oslo_concurrency.processutils [None req-3955998a-c85e-4632-bf56-c79450d01f74 None None] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool {{(pid=2204100) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Aug 25 01:17:56 datacore-PowerEdge-R740 sudo[2204429]:    stack : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/local/bin/cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool
Aug 25 01:17:56 datacore-PowerEdge-R740 sudo[2204429]: pam_unix(sudo:session): session opened for user root by (uid=0)
Aug 25 01:17:57 datacore-PowerEdge-R740 sudo[2204429]: pam_unix(sudo:session): session closed for user root
Aug 25 01:17:57 datacore-PowerEdge-R740 cinder-volume[2204100]: DEBUG oslo_concurrency.processutils [None req-3955998a-c85e-4632-bf56-c79450d01f74 None None] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool" returned: 0 in 0.611s {{(pid=2204100) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Aug 25 01:17:57 datacore-PowerEdge-R740 cinder-volume[2204100]: INFO cinder.volume.drivers.lvm [None req-3955998a-c85e-4632-bf56-c79450d01f74 None None] Enabling LVM thin provisioning by default because a thin pool exists.
Aug 25 01:17:57 datacore-PowerEdge-R740 cinder-volume[2204100]: DEBUG oslo_concurrency.processutils [None req-3955998a-c85e-4632-bf56-c79450d01f74 None None] Running cmd (subprocess): env LC_ALL=C lvm version {{(pid=2204100) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Aug 25 01:17:57 datacore-PowerEdge-R740 cinder-volume[2204100]: DEBUG oslo_concurrency.processutils [None req-3955998a-c85e-4632-bf56-c79450d01f74 None None] CMD "env LC_ALL=C lvm version" returned: 0 in 0.016s {{(pid=2204100) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Aug 25 01:17:57 datacore-PowerEdge-R740 cinder-volume[2204100]: DEBUG oslo_concurrency.processutils [None req-3955998a-c85e-4632-bf56-c79450d01f74 None None] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool {{(pid=2204100) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Aug 25 01:17:57 datacore-PowerEdge-R740 sudo[2204434]:    stack : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/local/bin/cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool
Aug 25 01:17:57 datacore-PowerEdge-R740 sudo[2204434]: pam_unix(sudo:session): session opened for user root by (uid=0)
Aug 25 01:17:57 datacore-PowerEdge-R740 sudo[2204434]: pam_unix(sudo:session): session closed for user root
Aug 25 01:17:57 datacore-PowerEdge-R740 cinder-volume[2204100]: DEBUG oslo_concurrency.processutils [None req-3955998a-c85e-4632-bf56-c79450d01f74 None None] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool" returned: 0 in 0.613s {{(pid=2204100) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Aug 25 01:17:57 datacore-PowerEdge-R740 cinder-volume[2204100]: DEBUG cinder.volume.drivers.lvm [None req-3955998a-c85e-4632-bf56-c79450d01f74 None None] Updating volume stats {{(pid=2204100) _update_volume_stats /opt/stack/cinder/cinder/volume/drivers/lvm.py:213}}
Aug 25 01:17:57 datacore-PowerEdge-R740 cinder-volume[2204100]: DEBUG oslo_concurrency.processutils [None req-3955998a-c85e-4632-bf56-c79450d01f74 None None] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix stack-volumes-lvmdriver-1 {{(pid=2204100) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Aug 25 01:17:57 datacore-PowerEdge-R740 sudo[2204442]:    stack : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/local/bin/cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix stack-volumes-lvmdriver-1
Aug 25 01:17:57 datacore-PowerEdge-R740 sudo[2204442]: pam_unix(sudo:session): session opened for user root by (uid=0)
Aug 25 01:17:58 datacore-PowerEdge-R740 sudo[2204442]: pam_unix(sudo:session): session closed for user root
Aug 25 01:17:58 datacore-PowerEdge-R740 cinder-volume[2204100]: DEBUG oslo_concurrency.processutils [None req-3955998a-c85e-4632-bf56-c79450d01f74 None None] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix stack-volumes-lvmdriver-1" returned: 0 in 0.640s {{(pid=2204100) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Aug 25 01:17:58 datacore-PowerEdge-R740 cinder-volume[2204100]: DEBUG oslo_concurrency.processutils [None req-3955998a-c85e-4632-bf56-c79450d01f74 None None] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1 {{(pid=2204100) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Aug 25 01:17:58 datacore-PowerEdge-R740 sudo[2204446]:    stack : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/local/bin/cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1
Aug 25 01:17:58 datacore-PowerEdge-R740 sudo[2204446]: pam_unix(sudo:session): session opened for user root by (uid=0)
Aug 25 01:17:59 datacore-PowerEdge-R740 sudo[2204446]: pam_unix(sudo:session): session closed for user root
Aug 25 01:17:59 datacore-PowerEdge-R740 cinder-volume[2204100]: DEBUG oslo_concurrency.processutils [None req-3955998a-c85e-4632-bf56-c79450d01f74 None None] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1" returned: 0 in 0.634s {{(pid=2204100) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Aug 25 01:17:59 datacore-PowerEdge-R740 cinder-volume[2204100]: DEBUG oslo_concurrency.processutils [None req-3955998a-c85e-4632-bf56-c79450d01f74 None None] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o size,data_percent --separator : --nosuffix /dev/stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool {{(pid=2204100) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Aug 25 01:17:59 datacore-PowerEdge-R740 sudo[2204554]:    stack : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/local/bin/cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o size,data_percent --separator : --nosuffix /dev/stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool
Aug 25 01:17:59 datacore-PowerEdge-R740 sudo[2204554]: pam_unix(sudo:session): session opened for user root by (uid=0)
Aug 25 01:17:59 datacore-PowerEdge-R740 cinder-volume[2203887]: DEBUG dbcounter [-] [2203887] Writing DB stats cinder:SELECT=16,cinder:UPDATE=1 {{(pid=2203887) stat_writer /usr/local/lib/python3.8/dist-packages/dbcounter.py:114}}
Aug 25 01:17:59 datacore-PowerEdge-R740 sudo[2204554]: pam_unix(sudo:session): session closed for user root
Aug 25 01:17:59 datacore-PowerEdge-R740 cinder-volume[2204100]: DEBUG oslo_concurrency.processutils [None req-3955998a-c85e-4632-bf56-c79450d01f74 None None] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o size,data_percent --separator : --nosuffix /dev/stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool" returned: 0 in 0.655s {{(pid=2204100) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Aug 25 01:17:59 datacore-PowerEdge-R740 cinder-volume[2204100]: DEBUG oslo_concurrency.processutils [None req-3955998a-c85e-4632-bf56-c79450d01f74 None None] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1 {{(pid=2204100) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Aug 25 01:17:59 datacore-PowerEdge-R740 sudo[2204562]:    stack : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/local/bin/cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1
Aug 25 01:17:59 datacore-PowerEdge-R740 sudo[2204562]: pam_unix(sudo:session): session opened for user root by (uid=0)
Aug 25 01:18:00 datacore-PowerEdge-R740 sudo[2204562]: pam_unix(sudo:session): session closed for user root
Aug 25 01:18:00 datacore-PowerEdge-R740 cinder-volume[2204100]: DEBUG oslo_concurrency.processutils [None req-3955998a-c85e-4632-bf56-c79450d01f74 None None] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1" returned: 0 in 0.635s {{(pid=2204100) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Aug 25 01:18:00 datacore-PowerEdge-R740 cinder-volume[2204100]: INFO cinder.volume.driver [None req-3955998a-c85e-4632-bf56-c79450d01f74 None None] Driver hasn't implemented _init_vendor_properties()
Aug 25 01:18:00 datacore-PowerEdge-R740 cinder-volume[2204100]: DEBUG cinder.volume.driver [None req-3955998a-c85e-4632-bf56-c79450d01f74 None None] Initialized capabilities list: {'volume_backend_name': 'lvmdriver-1', 'vendor_name': 'Open Source', 'driver_version': '3.0.0', 'storage_protocol': 'iSCSI', 'pools': [{'pool_name': 'lvmdriver-1', 'total_capacity_gb': 28.5, 'free_capacity_gb': 28.5, 'reserved_percentage': 0, 'location_info': 'LVMVolumeDriver:datacore-PowerEdge-R740:stack-volumes-lvmdriver-1:thin:0', 'QoS_support': False, 'provisioned_capacity_gb': 0.0, 'max_over_subscription_ratio': '20.0', 'thin_provisioning_support': True, 'thick_provisioning_support': False, 'total_volumes': 1, 'filter_function': None, 'goodness_function': None, 'multiattach': True, 'backend_state': 'up'}], 'shared_targets': False, 'sparse_copy_volume': True, 'properties': {'thin_provisioning': {'title': 'Thin Provisioning', 'description': 'Sets thin provisioning.', 'type': 'boolean'}, 'compression': {'title': 'Compression', 'description': 'Enables compression.', 'type': 'boolean'}, 'qos': {'title': 'QoS', 'description': 'Enables QoS.', 'type': 'boolean'}, 'replication_enabled': {'title': 'Replication', 'description': 'Enables replication.', 'type': 'boolean'}}}. {{(pid=2204100) init_capabilities /opt/stack/cinder/cinder/volume/driver.py:811}}
Aug 25 01:18:00 datacore-PowerEdge-R740 cinder-volume[2204100]: DEBUG oslo_db.sqlalchemy.engines [None req-3955998a-c85e-4632-bf56-c79450d01f74 None None] MySQL server mode set to STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_ENGINE_SUBSTITUTION {{(pid=2204100) _check_effective_sql_mode /usr/local/lib/python3.8/dist-packages/oslo_db/sqlalchemy/engines.py:314}}
Aug 25 01:18:00 datacore-PowerEdge-R740 cinder-volume[2204100]: DEBUG dbcounter [-] [2204100] Writer thread running {{(pid=2204100) stat_writer /usr/local/lib/python3.8/dist-packages/dbcounter.py:99}}
Aug 25 01:18:00 datacore-PowerEdge-R740 cinder-volume[2204100]: DEBUG cinder.db.sqlalchemy.api [None req-3955998a-c85e-4632-bf56-c79450d01f74 None None] Building query based on filter {{(pid=2204100) _process_snaps_filters /opt/stack/cinder/cinder/db/sqlalchemy/api.py:3378}}
Aug 25 01:18:00 datacore-PowerEdge-R740 cinder-volume[2204100]: DEBUG cinder.image.image_utils [None req-3955998a-c85e-4632-bf56-c79450d01f74 None None] Configuration image_conversion_dir is None or the path doesn't exist. {{(pid=2204100) cleanup_temporary_file /opt/stack/cinder/cinder/image/image_utils.py:955}}
Aug 25 01:18:00 datacore-PowerEdge-R740 cinder-volume[2204100]: DEBUG cinder.volume.drivers.lvm [None req-3955998a-c85e-4632-bf56-c79450d01f74 None None] Updating volume stats {{(pid=2204100) _update_volume_stats /opt/stack/cinder/cinder/volume/drivers/lvm.py:213}}
Aug 25 01:18:00 datacore-PowerEdge-R740 cinder-volume[2204100]: DEBUG oslo_concurrency.processutils [None req-3955998a-c85e-4632-bf56-c79450d01f74 None None] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix stack-volumes-lvmdriver-1 {{(pid=2204100) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Aug 25 01:18:00 datacore-PowerEdge-R740 cinder-volume[2204100]: INFO cinder.keymgr.migration [None req-c6b39b67-c087-45cf-b3cd-7ff38c8f990b None None] Not migrating encryption keys because the ConfKeyManager is still in use.
Aug 25 01:18:00 datacore-PowerEdge-R740 sudo[2204581]:    stack : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/local/bin/cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix stack-volumes-lvmdriver-1
Aug 25 01:18:00 datacore-PowerEdge-R740 sudo[2204581]: pam_unix(sudo:session): session opened for user root by (uid=0)
Aug 25 01:18:01 datacore-PowerEdge-R740 sudo[2204581]: pam_unix(sudo:session): session closed for user root
Aug 25 01:18:01 datacore-PowerEdge-R740 cinder-volume[2204100]: DEBUG oslo_concurrency.processutils [None req-3955998a-c85e-4632-bf56-c79450d01f74 None None] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix stack-volumes-lvmdriver-1" returned: 0 in 0.625s {{(pid=2204100) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Aug 25 01:18:01 datacore-PowerEdge-R740 cinder-volume[2204100]: DEBUG oslo_concurrency.processutils [None req-3955998a-c85e-4632-bf56-c79450d01f74 None None] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1 {{(pid=2204100) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Aug 25 01:18:01 datacore-PowerEdge-R740 sudo[2204590]:    stack : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/local/bin/cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1
Aug 25 01:18:01 datacore-PowerEdge-R740 sudo[2204590]: pam_unix(sudo:session): session opened for user root by (uid=0)
Aug 25 01:18:01 datacore-PowerEdge-R740 sudo[2204590]: pam_unix(sudo:session): session closed for user root
Aug 25 01:18:01 datacore-PowerEdge-R740 cinder-volume[2204100]: DEBUG oslo_concurrency.processutils [None req-3955998a-c85e-4632-bf56-c79450d01f74 None None] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1" returned: 0 in 0.696s {{(pid=2204100) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Aug 25 01:18:01 datacore-PowerEdge-R740 cinder-volume[2204100]: DEBUG oslo_concurrency.processutils [None req-3955998a-c85e-4632-bf56-c79450d01f74 None None] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o size,data_percent --separator : --nosuffix /dev/stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool {{(pid=2204100) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Aug 25 01:18:01 datacore-PowerEdge-R740 sudo[2204598]:    stack : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/local/bin/cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o size,data_percent --separator : --nosuffix /dev/stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool
Aug 25 01:18:01 datacore-PowerEdge-R740 sudo[2204598]: pam_unix(sudo:session): session opened for user root by (uid=0)
Aug 25 01:18:02 datacore-PowerEdge-R740 sudo[2204598]: pam_unix(sudo:session): session closed for user root
Aug 25 01:18:02 datacore-PowerEdge-R740 cinder-volume[2204100]: DEBUG oslo_concurrency.processutils [None req-3955998a-c85e-4632-bf56-c79450d01f74 None None] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o size,data_percent --separator : --nosuffix /dev/stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool" returned: 0 in 0.650s {{(pid=2204100) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Aug 25 01:18:02 datacore-PowerEdge-R740 cinder-volume[2204100]: DEBUG oslo_concurrency.processutils [None req-3955998a-c85e-4632-bf56-c79450d01f74 None None] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1 {{(pid=2204100) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Aug 25 01:18:02 datacore-PowerEdge-R740 sudo[2204610]:    stack : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/local/bin/cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1
Aug 25 01:18:02 datacore-PowerEdge-R740 sudo[2204610]: pam_unix(sudo:session): session opened for user root by (uid=0)
Aug 25 01:18:03 datacore-PowerEdge-R740 sudo[2204610]: pam_unix(sudo:session): session closed for user root
Aug 25 01:18:03 datacore-PowerEdge-R740 cinder-volume[2204100]: DEBUG oslo_concurrency.processutils [None req-3955998a-c85e-4632-bf56-c79450d01f74 None None] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1" returned: 0 in 0.624s {{(pid=2204100) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Aug 25 01:18:03 datacore-PowerEdge-R740 cinder-volume[2204100]: DEBUG cinder.manager [None req-3955998a-c85e-4632-bf56-c79450d01f74 None None] Notifying Schedulers of capabilities ... {{(pid=2204100) _publish_service_capabilities /opt/stack/cinder/cinder/manager.py:202}}
Aug 25 01:18:03 datacore-PowerEdge-R740 cinder-volume[2204100]: INFO cinder.volume.manager [None req-3955998a-c85e-4632-bf56-c79450d01f74 None None] Driver initialization completed successfully.
Aug 25 01:18:03 datacore-PowerEdge-R740 cinder-volume[2204100]: INFO cinder.manager [None req-3955998a-c85e-4632-bf56-c79450d01f74 None None] Initiating service 2 cleanup
Aug 25 01:18:03 datacore-PowerEdge-R740 cinder-volume[2204100]: INFO cinder.manager [None req-3955998a-c85e-4632-bf56-c79450d01f74 None None] Service 2 cleanup completed.
Aug 25 01:18:03 datacore-PowerEdge-R740 cinder-volume[2204100]: DEBUG cinder.service [None req-3955998a-c85e-4632-bf56-c79450d01f74 None None] Creating RPC server for service cinder-volume {{(pid=2204100) start /opt/stack/cinder/cinder/service.py:231}}
Aug 25 01:18:03 datacore-PowerEdge-R740 cinder-volume[2204100]: DEBUG cinder.service [None req-3955998a-c85e-4632-bf56-c79450d01f74 None None] Pinning object versions for RPC server serializer to 1.39 {{(pid=2204100) start /opt/stack/cinder/cinder/service.py:237}}
Aug 25 01:18:03 datacore-PowerEdge-R740 cinder-volume[2204100]: INFO cinder.volume.manager [None req-3955998a-c85e-4632-bf56-c79450d01f74 None None] Initializing RPC dependent components of volume driver LVMVolumeDriver (3.0.0)
Aug 25 01:18:03 datacore-PowerEdge-R740 cinder-volume[2204100]: DEBUG cinder.volume.drivers.lvm [None req-3955998a-c85e-4632-bf56-c79450d01f74 None None] Updating volume stats {{(pid=2204100) _update_volume_stats /opt/stack/cinder/cinder/volume/drivers/lvm.py:213}}
Aug 25 01:18:03 datacore-PowerEdge-R740 cinder-volume[2204100]: DEBUG oslo_concurrency.processutils [None req-3955998a-c85e-4632-bf56-c79450d01f74 None None] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix stack-volumes-lvmdriver-1 {{(pid=2204100) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Aug 25 01:18:03 datacore-PowerEdge-R740 sudo[2204622]:    stack : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/local/bin/cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix stack-volumes-lvmdriver-1
Aug 25 01:18:03 datacore-PowerEdge-R740 sudo[2204622]: pam_unix(sudo:session): session opened for user root by (uid=0)
Aug 25 01:18:03 datacore-PowerEdge-R740 sudo[2204622]: pam_unix(sudo:session): session closed for user root
Aug 25 01:18:03 datacore-PowerEdge-R740 cinder-volume[2204100]: DEBUG oslo_concurrency.processutils [None req-3955998a-c85e-4632-bf56-c79450d01f74 None None] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix stack-volumes-lvmdriver-1" returned: 0 in 0.649s {{(pid=2204100) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Aug 25 01:18:03 datacore-PowerEdge-R740 cinder-volume[2204100]: DEBUG oslo_concurrency.processutils [None req-3955998a-c85e-4632-bf56-c79450d01f74 None None] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1 {{(pid=2204100) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Aug 25 01:18:03 datacore-PowerEdge-R740 sudo[2204641]:    stack : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/local/bin/cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1
Aug 25 01:18:03 datacore-PowerEdge-R740 sudo[2204641]: pam_unix(sudo:session): session opened for user root by (uid=0)
Aug 25 01:18:04 datacore-PowerEdge-R740 sudo[2204641]: pam_unix(sudo:session): session closed for user root
Aug 25 01:18:04 datacore-PowerEdge-R740 cinder-volume[2204100]: DEBUG oslo_concurrency.processutils [None req-3955998a-c85e-4632-bf56-c79450d01f74 None None] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1" returned: 0 in 0.619s {{(pid=2204100) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Aug 25 01:18:04 datacore-PowerEdge-R740 cinder-volume[2204100]: DEBUG oslo_concurrency.processutils [None req-3955998a-c85e-4632-bf56-c79450d01f74 None None] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o size,data_percent --separator : --nosuffix /dev/stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool {{(pid=2204100) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Aug 25 01:18:04 datacore-PowerEdge-R740 sudo[2204660]:    stack : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/local/bin/cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o size,data_percent --separator : --nosuffix /dev/stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool
Aug 25 01:18:04 datacore-PowerEdge-R740 sudo[2204660]: pam_unix(sudo:session): session opened for user root by (uid=0)
Aug 25 01:18:05 datacore-PowerEdge-R740 sudo[2204660]: pam_unix(sudo:session): session closed for user root
Aug 25 01:18:05 datacore-PowerEdge-R740 cinder-volume[2204100]: DEBUG oslo_concurrency.processutils [None req-3955998a-c85e-4632-bf56-c79450d01f74 None None] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o size,data_percent --separator : --nosuffix /dev/stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool" returned: 0 in 0.669s {{(pid=2204100) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Aug 25 01:18:05 datacore-PowerEdge-R740 cinder-volume[2204100]: DEBUG oslo_concurrency.processutils [None req-3955998a-c85e-4632-bf56-c79450d01f74 None None] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1 {{(pid=2204100) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Aug 25 01:18:05 datacore-PowerEdge-R740 sudo[2204665]:    stack : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/local/bin/cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1
Aug 25 01:18:05 datacore-PowerEdge-R740 sudo[2204665]: pam_unix(sudo:session): session opened for user root by (uid=0)
Aug 25 01:18:05 datacore-PowerEdge-R740 sudo[2204665]: pam_unix(sudo:session): session closed for user root
Aug 25 01:18:05 datacore-PowerEdge-R740 cinder-volume[2204100]: DEBUG oslo_concurrency.processutils [None req-3955998a-c85e-4632-bf56-c79450d01f74 None None] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1" returned: 0 in 0.616s {{(pid=2204100) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Aug 25 01:18:05 datacore-PowerEdge-R740 cinder-volume[2204100]: INFO cinder.volume.manager [None req-3955998a-c85e-4632-bf56-c79450d01f74 None None] Driver post RPC initialization completed successfully.
Aug 25 01:18:08 datacore-PowerEdge-R740 systemd[1]: Stopping Devstack devstack@c-vol.service...
Aug 25 01:18:08 datacore-PowerEdge-R740 cinder-volume[2203887]: INFO oslo_service.service [None req-06c1619b-ece0-49b8-be70-91e9b81e467a None None] Caught SIGTERM, stopping children
Aug 25 01:18:08 datacore-PowerEdge-R740 cinder-volume[2203887]: DEBUG oslo_concurrency.lockutils [None req-06c1619b-ece0-49b8-be70-91e9b81e467a None None] Acquiring lock "singleton_lock" {{(pid=2203887) lock /usr/local/lib/python3.8/dist-packages/oslo_concurrency/lockutils.py:293}}
Aug 25 01:18:08 datacore-PowerEdge-R740 cinder-volume[2203887]: DEBUG oslo_concurrency.lockutils [None req-06c1619b-ece0-49b8-be70-91e9b81e467a None None] Acquired lock "singleton_lock" {{(pid=2203887) lock /usr/local/lib/python3.8/dist-packages/oslo_concurrency/lockutils.py:296}}
Aug 25 01:18:08 datacore-PowerEdge-R740 cinder-volume[2203887]: DEBUG oslo_concurrency.lockutils [None req-06c1619b-ece0-49b8-be70-91e9b81e467a None None] Releasing lock "singleton_lock" {{(pid=2203887) lock /usr/local/lib/python3.8/dist-packages/oslo_concurrency/lockutils.py:314}}
Aug 25 01:18:08 datacore-PowerEdge-R740 cinder-volume[2203887]: DEBUG oslo_service.service [None req-06c1619b-ece0-49b8-be70-91e9b81e467a None None] Stop services. {{(pid=2203887) stop /usr/local/lib/python3.8/dist-packages/oslo_service/service.py:695}}
Aug 25 01:18:08 datacore-PowerEdge-R740 cinder-volume[2203887]: DEBUG oslo_service.service [None req-06c1619b-ece0-49b8-be70-91e9b81e467a None None] Killing children. {{(pid=2203887) stop /usr/local/lib/python3.8/dist-packages/oslo_service/service.py:700}}
Aug 25 01:18:08 datacore-PowerEdge-R740 cinder-volume[2203887]: INFO oslo_service.service [None req-06c1619b-ece0-49b8-be70-91e9b81e467a None None] Waiting on 1 children to exit
Aug 25 01:18:09 datacore-PowerEdge-R740 cinder-volume[2204100]: DEBUG oslo_concurrency.lockutils [None req-06c1619b-ece0-49b8-be70-91e9b81e467a None None] Acquiring lock "singleton_lock" {{(pid=2204100) lock /usr/local/lib/python3.8/dist-packages/oslo_concurrency/lockutils.py:293}}
Aug 25 01:18:09 datacore-PowerEdge-R740 cinder-volume[2204100]: DEBUG oslo_concurrency.lockutils [None req-06c1619b-ece0-49b8-be70-91e9b81e467a None None] Acquired lock "singleton_lock" {{(pid=2204100) lock /usr/local/lib/python3.8/dist-packages/oslo_concurrency/lockutils.py:296}}
Aug 25 01:18:09 datacore-PowerEdge-R740 cinder-volume[2204100]: DEBUG oslo_concurrency.lockutils [None req-06c1619b-ece0-49b8-be70-91e9b81e467a None None] Releasing lock "singleton_lock" {{(pid=2204100) lock /usr/local/lib/python3.8/dist-packages/oslo_concurrency/lockutils.py:314}}
Aug 25 01:18:09 datacore-PowerEdge-R740 cinder-volume[2204100]: WARNING amqp [None req-06c1619b-ece0-49b8-be70-91e9b81e467a None None] Received method (60, 30) during closing channel 1. This method will be ignored
Aug 25 01:18:09 datacore-PowerEdge-R740 cinder-volume[2204100]: WARNING amqp [None req-06c1619b-ece0-49b8-be70-91e9b81e467a None None] Received method (60, 30) during closing channel 1. This method will be ignored
Aug 25 01:18:09 datacore-PowerEdge-R740 cinder-volume[2203887]: INFO oslo_service.service [None req-06c1619b-ece0-49b8-be70-91e9b81e467a None None] Child 2204100 exited with status 0
Aug 25 01:18:09 datacore-PowerEdge-R740 cinder-volume[2203887]: /usr/lib/python3/dist-packages/secretstorage/dhcrypto.py:15: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
Aug 25 01:18:09 datacore-PowerEdge-R740 cinder-volume[2203887]:   from cryptography.utils import int_from_bytes
Aug 25 01:18:09 datacore-PowerEdge-R740 cinder-volume[2203887]: /usr/lib/python3/dist-packages/secretstorage/util.py:19: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
Aug 25 01:18:09 datacore-PowerEdge-R740 cinder-volume[2203887]:   from cryptography.utils import int_from_bytes
Aug 25 01:18:09 datacore-PowerEdge-R740 cinder-volume[2203887]: /opt/stack/cinder/cinder/db/sqlalchemy/models.py:152: SAWarning: implicitly coercing SELECT object to scalar subquery; please use the .scalar_subquery() method to produce a scalar subquery.
Aug 25 01:18:09 datacore-PowerEdge-R740 cinder-volume[2203887]:   last_heartbeat = column_property(
Aug 25 01:18:09 datacore-PowerEdge-R740 cinder-volume[2203887]: /opt/stack/cinder/cinder/db/sqlalchemy/models.py:160: SAWarning: implicitly coercing SELECT object to scalar subquery; please use the .scalar_subquery() method to produce a scalar subquery.
Aug 25 01:18:09 datacore-PowerEdge-R740 cinder-volume[2203887]:   num_hosts = column_property(
Aug 25 01:18:09 datacore-PowerEdge-R740 cinder-volume[2203887]: /opt/stack/cinder/cinder/db/sqlalchemy/models.py:169: SAWarning: implicitly coercing SELECT object to scalar subquery; please use the .scalar_subquery() method to produce a scalar subquery.
Aug 25 01:18:09 datacore-PowerEdge-R740 cinder-volume[2203887]:   num_down_hosts = column_property(
Aug 25 01:18:09 datacore-PowerEdge-R740 systemd[1]: devstack@c-vol.service: Succeeded.
Aug 25 01:18:09 datacore-PowerEdge-R740 systemd[1]: Stopped Devstack devstack@c-vol.service.
Aug 25 01:18:09 datacore-PowerEdge-R740 systemd[1]: Started Devstack devstack@c-vol.service.
Aug 25 01:18:11 datacore-PowerEdge-R740 cinder-volume[2204769]: DEBUG oslo_concurrency.lockutils [-] Acquiring lock "singleton_lock" {{(pid=2204769) lock /usr/local/lib/python3.8/dist-packages/oslo_concurrency/lockutils.py:293}}
Aug 25 01:18:11 datacore-PowerEdge-R740 cinder-volume[2204769]: DEBUG oslo_concurrency.lockutils [-] Acquired lock "singleton_lock" {{(pid=2204769) lock /usr/local/lib/python3.8/dist-packages/oslo_concurrency/lockutils.py:296}}
Aug 25 01:18:11 datacore-PowerEdge-R740 cinder-volume[2204769]: DEBUG oslo_concurrency.lockutils [-] Releasing lock "singleton_lock" {{(pid=2204769) lock /usr/local/lib/python3.8/dist-packages/oslo_concurrency/lockutils.py:314}}
Aug 25 01:18:11 datacore-PowerEdge-R740 cinder-volume[2204769]: INFO dbcounter [None req-f0ebbe6e-8ea1-4ec3-a80a-9a35e56a2637 None None] Registered counter for database cinder
Aug 25 01:18:11 datacore-PowerEdge-R740 cinder-volume[2204769]: DEBUG oslo_db.sqlalchemy.engines [None req-f0ebbe6e-8ea1-4ec3-a80a-9a35e56a2637 None None] MySQL server mode set to STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_ENGINE_SUBSTITUTION {{(pid=2204769) _check_effective_sql_mode /usr/local/lib/python3.8/dist-packages/oslo_db/sqlalchemy/engines.py:314}}
Aug 25 01:18:11 datacore-PowerEdge-R740 cinder-volume[2204769]: DEBUG dbcounter [-] [2204769] Writer thread running {{(pid=2204769) stat_writer /usr/local/lib/python3.8/dist-packages/dbcounter.py:99}}
Aug 25 01:18:11 datacore-PowerEdge-R740 cinder-volume[2204769]: INFO cinder.rpc [None req-f0ebbe6e-8ea1-4ec3-a80a-9a35e56a2637 None None] Automatically selected cinder-scheduler objects version 1.39 as minimum service version.
Aug 25 01:18:11 datacore-PowerEdge-R740 cinder-volume[2204769]: INFO cinder.rpc [None req-f0ebbe6e-8ea1-4ec3-a80a-9a35e56a2637 None None] Automatically selected cinder-scheduler RPC version 3.12 as minimum service version.
Aug 25 01:18:11 datacore-PowerEdge-R740 cinder-volume[2204769]: DEBUG oslo_db.sqlalchemy.engines [None req-f0ebbe6e-8ea1-4ec3-a80a-9a35e56a2637 None None] MySQL server mode set to STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_ENGINE_SUBSTITUTION {{(pid=2204769) _check_effective_sql_mode /usr/local/lib/python3.8/dist-packages/oslo_db/sqlalchemy/engines.py:314}}
Aug 25 01:18:11 datacore-PowerEdge-R740 cinder-volume[2204769]: INFO cinder.volume.manager [None req-f0ebbe6e-8ea1-4ec3-a80a-9a35e56a2637 None None] Determined volume DB was empty at startup.
Aug 25 01:18:11 datacore-PowerEdge-R740 cinder-volume[2204769]: DEBUG cinder.volume.manager [None req-f0ebbe6e-8ea1-4ec3-a80a-9a35e56a2637 None None] Cinder Volume DB check: vol_db_empty=True {{(pid=2204769) __init__ /opt/stack/cinder/cinder/volume/manager.py:286}}
Aug 25 01:18:11 datacore-PowerEdge-R740 cinder-volume[2204769]: INFO cinder.volume.manager [None req-f0ebbe6e-8ea1-4ec3-a80a-9a35e56a2637 None None] Service not found for updating active_backend_id, assuming default for driver init.
Aug 25 01:18:11 datacore-PowerEdge-R740 cinder-volume[2204769]: WARNING stevedore.named [None req-f0ebbe6e-8ea1-4ec3-a80a-9a35e56a2637 None None] Could not load cinder.keymgr.conf_key_mgr.ConfKeyManager
Aug 25 01:18:11 datacore-PowerEdge-R740 cinder-volume[2204769]: WARNING castellan.key_manager [None req-f0ebbe6e-8ea1-4ec3-a80a-9a35e56a2637 None None] Deprecation Warning : cinder.keymgr.conf_key_mgr.ConfKeyManager is not a stevedore based driver, trying to load it as a class: stevedore.exception.NoMatches: No 'castellan.drivers' driver found, looking for 'cinder.keymgr.conf_key_mgr.ConfKeyManager'
Aug 25 01:18:11 datacore-PowerEdge-R740 cinder-volume[2204769]: WARNING cinder.keymgr.conf_key_mgr [None req-f0ebbe6e-8ea1-4ec3-a80a-9a35e56a2637 None None] This key manager is insecure and is not recommended for production deployments: stevedore.exception.NoMatches: No 'castellan.drivers' driver found, looking for 'cinder.keymgr.conf_key_mgr.ConfKeyManager'
Aug 25 01:18:11 datacore-PowerEdge-R740 cinder-volume[2204769]: ERROR cinder.cmd.volume [None req-f0ebbe6e-8ea1-4ec3-a80a-9a35e56a2637 None None] Volume service hostgroup@datacore_iscsi1 failed to start.: ModuleNotFoundError: No module named 'cinder.volume.drivers.datacore.iscsi'
Aug 25 01:18:11 datacore-PowerEdge-R740 cinder-volume[2204769]: ERROR cinder.cmd.volume Traceback (most recent call last):
Aug 25 01:18:11 datacore-PowerEdge-R740 cinder-volume[2204769]: ERROR cinder.cmd.volume   File "/opt/stack/cinder/cinder/cmd/volume.py", line 99, in _launch_service
Aug 25 01:18:11 datacore-PowerEdge-R740 cinder-volume[2204769]: ERROR cinder.cmd.volume     server = service.Service.create(host=host,
Aug 25 01:18:11 datacore-PowerEdge-R740 cinder-volume[2204769]: ERROR cinder.cmd.volume   File "/opt/stack/cinder/cinder/service.py", line 394, in create
Aug 25 01:18:11 datacore-PowerEdge-R740 cinder-volume[2204769]: ERROR cinder.cmd.volume     service_obj = cls(host, binary, topic, manager,
Aug 25 01:18:11 datacore-PowerEdge-R740 cinder-volume[2204769]: ERROR cinder.cmd.volume   File "/opt/stack/cinder/cinder/service.py", line 152, in __init__
Aug 25 01:18:11 datacore-PowerEdge-R740 cinder-volume[2204769]: ERROR cinder.cmd.volume     self.manager = manager_class(host=self.host,
Aug 25 01:18:11 datacore-PowerEdge-R740 cinder-volume[2204769]: ERROR cinder.cmd.volume   File "/opt/stack/cinder/cinder/volume/manager.py", line 309, in __init__
Aug 25 01:18:11 datacore-PowerEdge-R740 cinder-volume[2204769]: ERROR cinder.cmd.volume     self.driver = importutils.import_object(
Aug 25 01:18:11 datacore-PowerEdge-R740 cinder-volume[2204769]: ERROR cinder.cmd.volume   File "/usr/local/lib/python3.8/dist-packages/oslo_utils/importutils.py", line 44, in import_object
Aug 25 01:18:11 datacore-PowerEdge-R740 cinder-volume[2204769]: ERROR cinder.cmd.volume     return import_class(import_str)(*args, **kwargs)
Aug 25 01:18:11 datacore-PowerEdge-R740 cinder-volume[2204769]: ERROR cinder.cmd.volume   File "/usr/local/lib/python3.8/dist-packages/oslo_utils/importutils.py", line 30, in import_class
Aug 25 01:18:11 datacore-PowerEdge-R740 cinder-volume[2204769]: ERROR cinder.cmd.volume     __import__(mod_str)
Aug 25 01:18:11 datacore-PowerEdge-R740 cinder-volume[2204769]: ERROR cinder.cmd.volume ModuleNotFoundError: No module named 'cinder.volume.drivers.datacore.iscsi'
Aug 25 01:18:11 datacore-PowerEdge-R740 cinder-volume[2204769]: ERROR cinder.cmd.volume 
Aug 25 01:18:11 datacore-PowerEdge-R740 cinder-volume[2204769]: ERROR cinder.cmd.volume [None req-f0ebbe6e-8ea1-4ec3-a80a-9a35e56a2637 None None] No volume service(s) started successfully, terminating.
Aug 25 01:18:11 datacore-PowerEdge-R740 cinder-volume[2204769]: /usr/lib/python3/dist-packages/secretstorage/dhcrypto.py:15: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
Aug 25 01:18:11 datacore-PowerEdge-R740 cinder-volume[2204769]:   from cryptography.utils import int_from_bytes
Aug 25 01:18:11 datacore-PowerEdge-R740 cinder-volume[2204769]: /usr/lib/python3/dist-packages/secretstorage/util.py:19: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
Aug 25 01:18:11 datacore-PowerEdge-R740 cinder-volume[2204769]:   from cryptography.utils import int_from_bytes
Aug 25 01:18:11 datacore-PowerEdge-R740 cinder-volume[2204769]: /opt/stack/cinder/cinder/db/sqlalchemy/models.py:152: SAWarning: implicitly coercing SELECT object to scalar subquery; please use the .scalar_subquery() method to produce a scalar subquery.
Aug 25 01:18:11 datacore-PowerEdge-R740 cinder-volume[2204769]:   last_heartbeat = column_property(
Aug 25 01:18:11 datacore-PowerEdge-R740 cinder-volume[2204769]: /opt/stack/cinder/cinder/db/sqlalchemy/models.py:160: SAWarning: implicitly coercing SELECT object to scalar subquery; please use the .scalar_subquery() method to produce a scalar subquery.
Aug 25 01:18:11 datacore-PowerEdge-R740 cinder-volume[2204769]:   num_hosts = column_property(
Aug 25 01:18:11 datacore-PowerEdge-R740 cinder-volume[2204769]: /opt/stack/cinder/cinder/db/sqlalchemy/models.py:169: SAWarning: implicitly coercing SELECT object to scalar subquery; please use the .scalar_subquery() method to produce a scalar subquery.
Aug 25 01:18:11 datacore-PowerEdge-R740 cinder-volume[2204769]:   num_down_hosts = column_property(
Aug 25 01:18:12 datacore-PowerEdge-R740 systemd[1]: devstack@c-vol.service: Main process exited, code=exited, status=1/FAILURE
Aug 25 01:18:12 datacore-PowerEdge-R740 systemd[1]: devstack@c-vol.service: Failed with result 'exit-code'.
