-- Logs begin at Mon 2022-08-22 23:40:07 IST, end at Mon 2022-08-22 23:41:23 IST. --
Aug 22 23:40:07 datacore-PowerEdge-R740 sudo[4072050]: pam_unix(sudo:session): session closed for user root
Aug 22 23:40:07 datacore-PowerEdge-R740 cinder-volume[4072005]: DEBUG oslo_concurrency.processutils [None req-698fe57b-06b8-445c-ac88-ac94d48361b0 None None] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool" returned: 0 in 1.146s {{(pid=4072005) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Aug 22 23:40:07 datacore-PowerEdge-R740 cinder-volume[4072005]: DEBUG oslo_concurrency.processutils [None req-698fe57b-06b8-445c-ac88-ac94d48361b0 None None] Running cmd (subprocess): env LC_ALL=C lvm version {{(pid=4072005) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Aug 22 23:40:07 datacore-PowerEdge-R740 cinder-volume[4072005]: DEBUG oslo_concurrency.processutils [None req-698fe57b-06b8-445c-ac88-ac94d48361b0 None None] CMD "env LC_ALL=C lvm version" returned: 0 in 0.021s {{(pid=4072005) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Aug 22 23:40:07 datacore-PowerEdge-R740 cinder-volume[4072005]: DEBUG oslo_concurrency.processutils [None req-698fe57b-06b8-445c-ac88-ac94d48361b0 None None] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf lvchange -a y --yes -K stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool {{(pid=4072005) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Aug 22 23:40:07 datacore-PowerEdge-R740 sudo[4072097]:    stack : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/local/bin/cinder-rootwrap /etc/cinder/rootwrap.conf lvchange -a y --yes -K stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool
Aug 22 23:40:07 datacore-PowerEdge-R740 sudo[4072097]: pam_unix(sudo:session): session opened for user root by (uid=0)
Aug 22 23:40:08 datacore-PowerEdge-R740 sudo[4072097]: pam_unix(sudo:session): session closed for user root
Aug 22 23:40:08 datacore-PowerEdge-R740 cinder-volume[4072005]: DEBUG oslo_concurrency.processutils [None req-698fe57b-06b8-445c-ac88-ac94d48361b0 None None] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf lvchange -a y --yes -K stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool" returned: 0 in 1.018s {{(pid=4072005) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Aug 22 23:40:08 datacore-PowerEdge-R740 cinder-volume[4072005]: DEBUG oslo_concurrency.processutils [None req-698fe57b-06b8-445c-ac88-ac94d48361b0 None None] Running cmd (subprocess): env LC_ALL=C lvm version {{(pid=4072005) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Aug 22 23:40:08 datacore-PowerEdge-R740 cinder-volume[4072005]: DEBUG oslo_concurrency.processutils [None req-698fe57b-06b8-445c-ac88-ac94d48361b0 None None] CMD "env LC_ALL=C lvm version" returned: 0 in 0.019s {{(pid=4072005) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Aug 22 23:40:08 datacore-PowerEdge-R740 cinder-volume[4072005]: DEBUG oslo_concurrency.processutils [None req-698fe57b-06b8-445c-ac88-ac94d48361b0 None None] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C pvs --noheadings --unit=g -o vg_name,name,size,free --separator | --nosuffix --ignoreskippedcluster {{(pid=4072005) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Aug 22 23:40:09 datacore-PowerEdge-R740 sudo[4072209]:    stack : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/local/bin/cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C pvs --noheadings --unit=g -o vg_name,name,size,free --separator | --nosuffix --ignoreskippedcluster
Aug 22 23:40:09 datacore-PowerEdge-R740 sudo[4072209]: pam_unix(sudo:session): session opened for user root by (uid=0)
Aug 22 23:40:09 datacore-PowerEdge-R740 sudo[4072209]: pam_unix(sudo:session): session closed for user root
Aug 22 23:40:09 datacore-PowerEdge-R740 cinder-volume[4072005]: DEBUG oslo_concurrency.processutils [None req-698fe57b-06b8-445c-ac88-ac94d48361b0 None None] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C pvs --noheadings --unit=g -o vg_name,name,size,free --separator | --nosuffix --ignoreskippedcluster" returned: 0 in 0.722s {{(pid=4072005) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Aug 22 23:40:09 datacore-PowerEdge-R740 cinder-volume[4072005]: DEBUG oslo_concurrency.processutils [None req-698fe57b-06b8-445c-ac88-ac94d48361b0 None None] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix stack-volumes-lvmdriver-1 {{(pid=4072005) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Aug 22 23:40:09 datacore-PowerEdge-R740 sudo[4072275]:    stack : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/local/bin/cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix stack-volumes-lvmdriver-1
Aug 22 23:40:09 datacore-PowerEdge-R740 sudo[4072275]: pam_unix(sudo:session): session opened for user root by (uid=0)
Aug 22 23:40:10 datacore-PowerEdge-R740 sudo[4072275]: pam_unix(sudo:session): session closed for user root
Aug 22 23:40:10 datacore-PowerEdge-R740 cinder-volume[4072005]: DEBUG oslo_concurrency.processutils [None req-698fe57b-06b8-445c-ac88-ac94d48361b0 None None] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix stack-volumes-lvmdriver-1" returned: 0 in 0.687s {{(pid=4072005) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Aug 22 23:40:10 datacore-PowerEdge-R740 cinder-volume[4072005]: DEBUG oslo_concurrency.processutils [None req-698fe57b-06b8-445c-ac88-ac94d48361b0 None None] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix stack-volumes-lvmdriver-1 {{(pid=4072005) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Aug 22 23:40:10 datacore-PowerEdge-R740 sudo[4072308]:    stack : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/local/bin/cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix stack-volumes-lvmdriver-1
Aug 22 23:40:10 datacore-PowerEdge-R740 sudo[4072308]: pam_unix(sudo:session): session opened for user root by (uid=0)
Aug 22 23:40:11 datacore-PowerEdge-R740 sudo[4072308]: pam_unix(sudo:session): session closed for user root
Aug 22 23:40:11 datacore-PowerEdge-R740 cinder-volume[4072005]: DEBUG oslo_concurrency.processutils [None req-698fe57b-06b8-445c-ac88-ac94d48361b0 None None] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix stack-volumes-lvmdriver-1" returned: 0 in 0.668s {{(pid=4072005) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Aug 22 23:40:11 datacore-PowerEdge-R740 cinder-volume[4072005]: DEBUG oslo_concurrency.processutils [None req-698fe57b-06b8-445c-ac88-ac94d48361b0 None None] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1 {{(pid=4072005) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Aug 22 23:40:11 datacore-PowerEdge-R740 sudo[4072320]:    stack : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/local/bin/cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1
Aug 22 23:40:11 datacore-PowerEdge-R740 sudo[4072320]: pam_unix(sudo:session): session opened for user root by (uid=0)
Aug 22 23:40:11 datacore-PowerEdge-R740 sudo[4072320]: pam_unix(sudo:session): session closed for user root
Aug 22 23:40:11 datacore-PowerEdge-R740 cinder-volume[4072005]: DEBUG oslo_concurrency.processutils [None req-698fe57b-06b8-445c-ac88-ac94d48361b0 None None] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1" returned: 0 in 0.685s {{(pid=4072005) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Aug 22 23:40:11 datacore-PowerEdge-R740 cinder-volume[4072005]: DEBUG oslo_concurrency.processutils [None req-698fe57b-06b8-445c-ac88-ac94d48361b0 None None] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o size,data_percent --separator : --nosuffix /dev/stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool {{(pid=4072005) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Aug 22 23:40:11 datacore-PowerEdge-R740 sudo[4072337]:    stack : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/local/bin/cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o size,data_percent --separator : --nosuffix /dev/stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool
Aug 22 23:40:11 datacore-PowerEdge-R740 sudo[4072337]: pam_unix(sudo:session): session opened for user root by (uid=0)
Aug 22 23:40:12 datacore-PowerEdge-R740 sudo[4072337]: pam_unix(sudo:session): session closed for user root
Aug 22 23:40:12 datacore-PowerEdge-R740 cinder-volume[4072005]: DEBUG oslo_concurrency.processutils [None req-698fe57b-06b8-445c-ac88-ac94d48361b0 None None] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o size,data_percent --separator : --nosuffix /dev/stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool" returned: 0 in 0.693s {{(pid=4072005) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Aug 22 23:40:12 datacore-PowerEdge-R740 cinder-volume[4072005]: DEBUG oslo_concurrency.processutils [None req-698fe57b-06b8-445c-ac88-ac94d48361b0 None None] Running cmd (subprocess): env LC_ALL=C lvm version {{(pid=4072005) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Aug 22 23:40:12 datacore-PowerEdge-R740 cinder-volume[4072005]: DEBUG oslo_concurrency.processutils [None req-698fe57b-06b8-445c-ac88-ac94d48361b0 None None] CMD "env LC_ALL=C lvm version" returned: 0 in 0.016s {{(pid=4072005) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Aug 22 23:40:12 datacore-PowerEdge-R740 cinder-volume[4072005]: DEBUG oslo_concurrency.processutils [None req-698fe57b-06b8-445c-ac88-ac94d48361b0 None None] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool {{(pid=4072005) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Aug 22 23:40:12 datacore-PowerEdge-R740 sudo[4072448]:    stack : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/local/bin/cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool
Aug 22 23:40:12 datacore-PowerEdge-R740 sudo[4072448]: pam_unix(sudo:session): session opened for user root by (uid=0)
Aug 22 23:40:13 datacore-PowerEdge-R740 sudo[4072448]: pam_unix(sudo:session): session closed for user root
Aug 22 23:40:13 datacore-PowerEdge-R740 cinder-volume[4072005]: DEBUG oslo_concurrency.processutils [None req-698fe57b-06b8-445c-ac88-ac94d48361b0 None None] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool" returned: 0 in 0.641s {{(pid=4072005) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Aug 22 23:40:13 datacore-PowerEdge-R740 cinder-volume[4072005]: INFO cinder.volume.drivers.lvm [None req-698fe57b-06b8-445c-ac88-ac94d48361b0 None None] Enabling LVM thin provisioning by default because a thin pool exists.
Aug 22 23:40:13 datacore-PowerEdge-R740 cinder-volume[4072005]: DEBUG oslo_concurrency.processutils [None req-698fe57b-06b8-445c-ac88-ac94d48361b0 None None] Running cmd (subprocess): env LC_ALL=C lvm version {{(pid=4072005) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Aug 22 23:40:13 datacore-PowerEdge-R740 cinder-volume[4072005]: DEBUG oslo_concurrency.processutils [None req-698fe57b-06b8-445c-ac88-ac94d48361b0 None None] CMD "env LC_ALL=C lvm version" returned: 0 in 0.014s {{(pid=4072005) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Aug 22 23:40:13 datacore-PowerEdge-R740 cinder-volume[4072005]: DEBUG oslo_concurrency.processutils [None req-698fe57b-06b8-445c-ac88-ac94d48361b0 None None] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool {{(pid=4072005) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Aug 22 23:40:13 datacore-PowerEdge-R740 sudo[4072453]:    stack : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/local/bin/cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool
Aug 22 23:40:13 datacore-PowerEdge-R740 sudo[4072453]: pam_unix(sudo:session): session opened for user root by (uid=0)
Aug 22 23:40:13 datacore-PowerEdge-R740 sudo[4072453]: pam_unix(sudo:session): session closed for user root
Aug 22 23:40:13 datacore-PowerEdge-R740 cinder-volume[4072005]: DEBUG oslo_concurrency.processutils [None req-698fe57b-06b8-445c-ac88-ac94d48361b0 None None] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool" returned: 0 in 0.622s {{(pid=4072005) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Aug 22 23:40:13 datacore-PowerEdge-R740 cinder-volume[4072005]: DEBUG cinder.volume.drivers.lvm [None req-698fe57b-06b8-445c-ac88-ac94d48361b0 None None] Updating volume stats {{(pid=4072005) _update_volume_stats /opt/stack/cinder/cinder/volume/drivers/lvm.py:213}}
Aug 22 23:40:13 datacore-PowerEdge-R740 cinder-volume[4072005]: DEBUG oslo_concurrency.processutils [None req-698fe57b-06b8-445c-ac88-ac94d48361b0 None None] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix stack-volumes-lvmdriver-1 {{(pid=4072005) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Aug 22 23:40:13 datacore-PowerEdge-R740 sudo[4072470]:    stack : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/local/bin/cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix stack-volumes-lvmdriver-1
Aug 22 23:40:13 datacore-PowerEdge-R740 sudo[4072470]: pam_unix(sudo:session): session opened for user root by (uid=0)
Aug 22 23:40:14 datacore-PowerEdge-R740 sudo[4072470]: pam_unix(sudo:session): session closed for user root
Aug 22 23:40:14 datacore-PowerEdge-R740 cinder-volume[4072005]: DEBUG oslo_concurrency.processutils [None req-698fe57b-06b8-445c-ac88-ac94d48361b0 None None] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix stack-volumes-lvmdriver-1" returned: 0 in 0.640s {{(pid=4072005) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Aug 22 23:40:14 datacore-PowerEdge-R740 cinder-volume[4072005]: DEBUG oslo_concurrency.processutils [None req-698fe57b-06b8-445c-ac88-ac94d48361b0 None None] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1 {{(pid=4072005) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Aug 22 23:40:14 datacore-PowerEdge-R740 sudo[4072476]:    stack : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/local/bin/cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1
Aug 22 23:40:14 datacore-PowerEdge-R740 sudo[4072476]: pam_unix(sudo:session): session opened for user root by (uid=0)
Aug 22 23:40:15 datacore-PowerEdge-R740 sudo[4072476]: pam_unix(sudo:session): session closed for user root
Aug 22 23:40:15 datacore-PowerEdge-R740 cinder-volume[4072005]: DEBUG oslo_concurrency.processutils [None req-698fe57b-06b8-445c-ac88-ac94d48361b0 None None] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1" returned: 0 in 0.670s {{(pid=4072005) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Aug 22 23:40:15 datacore-PowerEdge-R740 cinder-volume[4072005]: DEBUG oslo_concurrency.processutils [None req-698fe57b-06b8-445c-ac88-ac94d48361b0 None None] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o size,data_percent --separator : --nosuffix /dev/stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool {{(pid=4072005) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Aug 22 23:40:15 datacore-PowerEdge-R740 sudo[4072484]:    stack : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/local/bin/cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o size,data_percent --separator : --nosuffix /dev/stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool
Aug 22 23:40:15 datacore-PowerEdge-R740 sudo[4072484]: pam_unix(sudo:session): session opened for user root by (uid=0)
Aug 22 23:40:15 datacore-PowerEdge-R740 cinder-volume[4071783]: DEBUG dbcounter [-] [4071783] Writing DB stats cinder:SELECT=16,cinder:UPDATE=1 {{(pid=4071783) stat_writer /usr/local/lib/python3.8/dist-packages/dbcounter.py:114}}
Aug 22 23:40:16 datacore-PowerEdge-R740 sudo[4072484]: pam_unix(sudo:session): session closed for user root
Aug 22 23:40:16 datacore-PowerEdge-R740 cinder-volume[4072005]: DEBUG oslo_concurrency.processutils [None req-698fe57b-06b8-445c-ac88-ac94d48361b0 None None] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o size,data_percent --separator : --nosuffix /dev/stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool" returned: 0 in 1.323s {{(pid=4072005) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Aug 22 23:40:16 datacore-PowerEdge-R740 cinder-volume[4072005]: DEBUG oslo_concurrency.processutils [None req-698fe57b-06b8-445c-ac88-ac94d48361b0 None None] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1 {{(pid=4072005) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Aug 22 23:40:16 datacore-PowerEdge-R740 sudo[4072499]:    stack : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/local/bin/cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1
Aug 22 23:40:16 datacore-PowerEdge-R740 sudo[4072499]: pam_unix(sudo:session): session opened for user root by (uid=0)
Aug 22 23:40:17 datacore-PowerEdge-R740 sudo[4072499]: pam_unix(sudo:session): session closed for user root
Aug 22 23:40:17 datacore-PowerEdge-R740 cinder-volume[4072005]: DEBUG oslo_concurrency.processutils [None req-698fe57b-06b8-445c-ac88-ac94d48361b0 None None] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1" returned: 0 in 0.670s {{(pid=4072005) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Aug 22 23:40:17 datacore-PowerEdge-R740 cinder-volume[4072005]: INFO cinder.volume.driver [None req-698fe57b-06b8-445c-ac88-ac94d48361b0 None None] Driver hasn't implemented _init_vendor_properties()
Aug 22 23:40:17 datacore-PowerEdge-R740 cinder-volume[4072005]: DEBUG cinder.volume.driver [None req-698fe57b-06b8-445c-ac88-ac94d48361b0 None None] Initialized capabilities list: {'volume_backend_name': 'lvmdriver-1', 'vendor_name': 'Open Source', 'driver_version': '3.0.0', 'storage_protocol': 'iSCSI', 'pools': [{'pool_name': 'lvmdriver-1', 'total_capacity_gb': 28.5, 'free_capacity_gb': 28.5, 'reserved_percentage': 0, 'location_info': 'LVMVolumeDriver:datacore-PowerEdge-R740:stack-volumes-lvmdriver-1:thin:0', 'QoS_support': False, 'provisioned_capacity_gb': 0.0, 'max_over_subscription_ratio': '20.0', 'thin_provisioning_support': True, 'thick_provisioning_support': False, 'total_volumes': 1, 'filter_function': None, 'goodness_function': None, 'multiattach': True, 'backend_state': 'up'}], 'shared_targets': False, 'sparse_copy_volume': True, 'properties': {'thin_provisioning': {'title': 'Thin Provisioning', 'description': 'Sets thin provisioning.', 'type': 'boolean'}, 'compression': {'title': 'Compression', 'description': 'Enables compression.', 'type': 'boolean'}, 'qos': {'title': 'QoS', 'description': 'Enables QoS.', 'type': 'boolean'}, 'replication_enabled': {'title': 'Replication', 'description': 'Enables replication.', 'type': 'boolean'}}}. {{(pid=4072005) init_capabilities /opt/stack/cinder/cinder/volume/driver.py:811}}
Aug 22 23:40:17 datacore-PowerEdge-R740 cinder-volume[4072005]: DEBUG oslo_db.sqlalchemy.engines [None req-698fe57b-06b8-445c-ac88-ac94d48361b0 None None] MySQL server mode set to STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_ENGINE_SUBSTITUTION {{(pid=4072005) _check_effective_sql_mode /usr/local/lib/python3.8/dist-packages/oslo_db/sqlalchemy/engines.py:314}}
Aug 22 23:40:17 datacore-PowerEdge-R740 cinder-volume[4072005]: DEBUG dbcounter [-] [4072005] Writer thread running {{(pid=4072005) stat_writer /usr/local/lib/python3.8/dist-packages/dbcounter.py:99}}
Aug 22 23:40:17 datacore-PowerEdge-R740 cinder-volume[4072005]: DEBUG cinder.db.sqlalchemy.api [None req-698fe57b-06b8-445c-ac88-ac94d48361b0 None None] Building query based on filter {{(pid=4072005) _process_snaps_filters /opt/stack/cinder/cinder/db/sqlalchemy/api.py:3378}}
Aug 22 23:40:17 datacore-PowerEdge-R740 cinder-volume[4072005]: DEBUG cinder.image.image_utils [None req-698fe57b-06b8-445c-ac88-ac94d48361b0 None None] Configuration image_conversion_dir is None or the path doesn't exist. {{(pid=4072005) cleanup_temporary_file /opt/stack/cinder/cinder/image/image_utils.py:955}}
Aug 22 23:40:17 datacore-PowerEdge-R740 cinder-volume[4072005]: DEBUG cinder.volume.drivers.lvm [None req-698fe57b-06b8-445c-ac88-ac94d48361b0 None None] Updating volume stats {{(pid=4072005) _update_volume_stats /opt/stack/cinder/cinder/volume/drivers/lvm.py:213}}
Aug 22 23:40:17 datacore-PowerEdge-R740 cinder-volume[4072005]: DEBUG oslo_concurrency.processutils [None req-698fe57b-06b8-445c-ac88-ac94d48361b0 None None] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix stack-volumes-lvmdriver-1 {{(pid=4072005) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Aug 22 23:40:17 datacore-PowerEdge-R740 sudo[4072522]:    stack : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/local/bin/cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix stack-volumes-lvmdriver-1
Aug 22 23:40:17 datacore-PowerEdge-R740 sudo[4072522]: pam_unix(sudo:session): session opened for user root by (uid=0)
Aug 22 23:40:17 datacore-PowerEdge-R740 cinder-volume[4072005]: INFO cinder.keymgr.migration [None req-082cc42b-1d19-42de-b65a-b894cccdcbbf None None] Not migrating encryption keys because the ConfKeyManager is still in use.
Aug 22 23:40:17 datacore-PowerEdge-R740 sudo[4072522]: pam_unix(sudo:session): session closed for user root
Aug 22 23:40:17 datacore-PowerEdge-R740 cinder-volume[4072005]: DEBUG oslo_concurrency.processutils [None req-698fe57b-06b8-445c-ac88-ac94d48361b0 None None] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix stack-volumes-lvmdriver-1" returned: 0 in 0.635s {{(pid=4072005) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Aug 22 23:40:17 datacore-PowerEdge-R740 cinder-volume[4072005]: DEBUG oslo_concurrency.processutils [None req-698fe57b-06b8-445c-ac88-ac94d48361b0 None None] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1 {{(pid=4072005) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Aug 22 23:40:17 datacore-PowerEdge-R740 sudo[4072532]:    stack : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/local/bin/cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1
Aug 22 23:40:17 datacore-PowerEdge-R740 sudo[4072532]: pam_unix(sudo:session): session opened for user root by (uid=0)
Aug 22 23:40:18 datacore-PowerEdge-R740 sudo[4072532]: pam_unix(sudo:session): session closed for user root
Aug 22 23:40:18 datacore-PowerEdge-R740 cinder-volume[4072005]: DEBUG oslo_concurrency.processutils [None req-698fe57b-06b8-445c-ac88-ac94d48361b0 None None] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1" returned: 0 in 0.670s {{(pid=4072005) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Aug 22 23:40:18 datacore-PowerEdge-R740 cinder-volume[4072005]: DEBUG oslo_concurrency.processutils [None req-698fe57b-06b8-445c-ac88-ac94d48361b0 None None] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o size,data_percent --separator : --nosuffix /dev/stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool {{(pid=4072005) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Aug 22 23:40:18 datacore-PowerEdge-R740 sudo[4072544]:    stack : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/local/bin/cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o size,data_percent --separator : --nosuffix /dev/stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool
Aug 22 23:40:18 datacore-PowerEdge-R740 sudo[4072544]: pam_unix(sudo:session): session opened for user root by (uid=0)
Aug 22 23:40:19 datacore-PowerEdge-R740 sudo[4072544]: pam_unix(sudo:session): session closed for user root
Aug 22 23:40:19 datacore-PowerEdge-R740 cinder-volume[4072005]: DEBUG oslo_concurrency.processutils [None req-698fe57b-06b8-445c-ac88-ac94d48361b0 None None] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o size,data_percent --separator : --nosuffix /dev/stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool" returned: 0 in 0.638s {{(pid=4072005) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Aug 22 23:40:19 datacore-PowerEdge-R740 cinder-volume[4072005]: DEBUG oslo_concurrency.processutils [None req-698fe57b-06b8-445c-ac88-ac94d48361b0 None None] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1 {{(pid=4072005) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Aug 22 23:40:19 datacore-PowerEdge-R740 sudo[4072557]:    stack : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/local/bin/cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1
Aug 22 23:40:19 datacore-PowerEdge-R740 sudo[4072557]: pam_unix(sudo:session): session opened for user root by (uid=0)
Aug 22 23:40:19 datacore-PowerEdge-R740 sudo[4072557]: pam_unix(sudo:session): session closed for user root
Aug 22 23:40:19 datacore-PowerEdge-R740 cinder-volume[4072005]: DEBUG oslo_concurrency.processutils [None req-698fe57b-06b8-445c-ac88-ac94d48361b0 None None] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1" returned: 0 in 0.655s {{(pid=4072005) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Aug 22 23:40:19 datacore-PowerEdge-R740 cinder-volume[4072005]: DEBUG cinder.manager [None req-698fe57b-06b8-445c-ac88-ac94d48361b0 None None] Notifying Schedulers of capabilities ... {{(pid=4072005) _publish_service_capabilities /opt/stack/cinder/cinder/manager.py:202}}
Aug 22 23:40:19 datacore-PowerEdge-R740 cinder-volume[4072005]: INFO cinder.volume.manager [None req-698fe57b-06b8-445c-ac88-ac94d48361b0 None None] Driver initialization completed successfully.
Aug 22 23:40:19 datacore-PowerEdge-R740 cinder-volume[4072005]: INFO cinder.manager [None req-698fe57b-06b8-445c-ac88-ac94d48361b0 None None] Initiating service 2 cleanup
Aug 22 23:40:19 datacore-PowerEdge-R740 cinder-volume[4072005]: INFO cinder.manager [None req-698fe57b-06b8-445c-ac88-ac94d48361b0 None None] Service 2 cleanup completed.
Aug 22 23:40:19 datacore-PowerEdge-R740 cinder-volume[4072005]: DEBUG cinder.service [None req-698fe57b-06b8-445c-ac88-ac94d48361b0 None None] Creating RPC server for service cinder-volume {{(pid=4072005) start /opt/stack/cinder/cinder/service.py:231}}
Aug 22 23:40:19 datacore-PowerEdge-R740 cinder-volume[4072005]: DEBUG cinder.service [None req-698fe57b-06b8-445c-ac88-ac94d48361b0 None None] Pinning object versions for RPC server serializer to 1.39 {{(pid=4072005) start /opt/stack/cinder/cinder/service.py:237}}
Aug 22 23:40:19 datacore-PowerEdge-R740 cinder-volume[4072005]: INFO cinder.volume.manager [None req-698fe57b-06b8-445c-ac88-ac94d48361b0 None None] Initializing RPC dependent components of volume driver LVMVolumeDriver (3.0.0)
Aug 22 23:40:19 datacore-PowerEdge-R740 cinder-volume[4072005]: DEBUG cinder.volume.drivers.lvm [None req-698fe57b-06b8-445c-ac88-ac94d48361b0 None None] Updating volume stats {{(pid=4072005) _update_volume_stats /opt/stack/cinder/cinder/volume/drivers/lvm.py:213}}
Aug 22 23:40:19 datacore-PowerEdge-R740 cinder-volume[4072005]: DEBUG oslo_concurrency.processutils [None req-698fe57b-06b8-445c-ac88-ac94d48361b0 None None] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix stack-volumes-lvmdriver-1 {{(pid=4072005) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Aug 22 23:40:19 datacore-PowerEdge-R740 sudo[4072567]:    stack : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/local/bin/cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix stack-volumes-lvmdriver-1
Aug 22 23:40:19 datacore-PowerEdge-R740 sudo[4072567]: pam_unix(sudo:session): session opened for user root by (uid=0)
Aug 22 23:40:20 datacore-PowerEdge-R740 sudo[4072567]: pam_unix(sudo:session): session closed for user root
Aug 22 23:40:20 datacore-PowerEdge-R740 cinder-volume[4072005]: DEBUG oslo_concurrency.processutils [None req-698fe57b-06b8-445c-ac88-ac94d48361b0 None None] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix stack-volumes-lvmdriver-1" returned: 0 in 0.646s {{(pid=4072005) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Aug 22 23:40:20 datacore-PowerEdge-R740 cinder-volume[4072005]: DEBUG oslo_concurrency.processutils [None req-698fe57b-06b8-445c-ac88-ac94d48361b0 None None] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1 {{(pid=4072005) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Aug 22 23:40:20 datacore-PowerEdge-R740 sudo[4072593]:    stack : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/local/bin/cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1
Aug 22 23:40:20 datacore-PowerEdge-R740 sudo[4072593]: pam_unix(sudo:session): session opened for user root by (uid=0)
Aug 22 23:40:21 datacore-PowerEdge-R740 sudo[4072593]: pam_unix(sudo:session): session closed for user root
Aug 22 23:40:21 datacore-PowerEdge-R740 cinder-volume[4072005]: DEBUG oslo_concurrency.processutils [None req-698fe57b-06b8-445c-ac88-ac94d48361b0 None None] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1" returned: 0 in 0.620s {{(pid=4072005) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Aug 22 23:40:21 datacore-PowerEdge-R740 cinder-volume[4072005]: DEBUG oslo_concurrency.processutils [None req-698fe57b-06b8-445c-ac88-ac94d48361b0 None None] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o size,data_percent --separator : --nosuffix /dev/stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool {{(pid=4072005) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Aug 22 23:40:21 datacore-PowerEdge-R740 sudo[4072598]:    stack : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/local/bin/cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o size,data_percent --separator : --nosuffix /dev/stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool
Aug 22 23:40:21 datacore-PowerEdge-R740 sudo[4072598]: pam_unix(sudo:session): session opened for user root by (uid=0)
Aug 22 23:40:21 datacore-PowerEdge-R740 systemd[1]: Stopping Devstack devstack@c-vol.service...
Aug 22 23:40:21 datacore-PowerEdge-R740 cinder-volume[4071783]: INFO oslo_service.service [None req-44c7b55f-d1fb-4cd9-bbf7-5cea2642e01c None None] Caught SIGTERM, stopping children
Aug 22 23:40:21 datacore-PowerEdge-R740 cinder-volume[4071783]: DEBUG oslo_concurrency.lockutils [None req-44c7b55f-d1fb-4cd9-bbf7-5cea2642e01c None None] Acquiring lock "singleton_lock" {{(pid=4071783) lock /usr/local/lib/python3.8/dist-packages/oslo_concurrency/lockutils.py:293}}
Aug 22 23:40:21 datacore-PowerEdge-R740 cinder-volume[4071783]: DEBUG oslo_concurrency.lockutils [None req-44c7b55f-d1fb-4cd9-bbf7-5cea2642e01c None None] Acquired lock "singleton_lock" {{(pid=4071783) lock /usr/local/lib/python3.8/dist-packages/oslo_concurrency/lockutils.py:296}}
Aug 22 23:40:21 datacore-PowerEdge-R740 cinder-volume[4071783]: DEBUG oslo_concurrency.lockutils [None req-44c7b55f-d1fb-4cd9-bbf7-5cea2642e01c None None] Releasing lock "singleton_lock" {{(pid=4071783) lock /usr/local/lib/python3.8/dist-packages/oslo_concurrency/lockutils.py:314}}
Aug 22 23:40:21 datacore-PowerEdge-R740 cinder-volume[4071783]: DEBUG oslo_service.service [None req-44c7b55f-d1fb-4cd9-bbf7-5cea2642e01c None None] Stop services. {{(pid=4071783) stop /usr/local/lib/python3.8/dist-packages/oslo_service/service.py:695}}
Aug 22 23:40:21 datacore-PowerEdge-R740 cinder-volume[4071783]: DEBUG oslo_service.service [None req-44c7b55f-d1fb-4cd9-bbf7-5cea2642e01c None None] Killing children. {{(pid=4071783) stop /usr/local/lib/python3.8/dist-packages/oslo_service/service.py:700}}
Aug 22 23:40:21 datacore-PowerEdge-R740 cinder-volume[4071783]: INFO oslo_service.service [None req-44c7b55f-d1fb-4cd9-bbf7-5cea2642e01c None None] Waiting on 1 children to exit
Aug 22 23:40:21 datacore-PowerEdge-R740 cinder-volume[4072005]: DEBUG oslo_concurrency.lockutils [None req-44c7b55f-d1fb-4cd9-bbf7-5cea2642e01c None None] Acquiring lock "singleton_lock" {{(pid=4072005) lock /usr/local/lib/python3.8/dist-packages/oslo_concurrency/lockutils.py:293}}
Aug 22 23:40:21 datacore-PowerEdge-R740 cinder-volume[4072005]: DEBUG oslo_concurrency.lockutils [None req-44c7b55f-d1fb-4cd9-bbf7-5cea2642e01c None None] Acquired lock "singleton_lock" {{(pid=4072005) lock /usr/local/lib/python3.8/dist-packages/oslo_concurrency/lockutils.py:296}}
Aug 22 23:40:21 datacore-PowerEdge-R740 cinder-volume[4072005]: DEBUG oslo_concurrency.lockutils [None req-44c7b55f-d1fb-4cd9-bbf7-5cea2642e01c None None] Releasing lock "singleton_lock" {{(pid=4072005) lock /usr/local/lib/python3.8/dist-packages/oslo_concurrency/lockutils.py:314}}
Aug 22 23:40:21 datacore-PowerEdge-R740 cinder-volume[4072005]: WARNING amqp [None req-44c7b55f-d1fb-4cd9-bbf7-5cea2642e01c None None] Received method (60, 30) during closing channel 1. This method will be ignored
Aug 22 23:40:21 datacore-PowerEdge-R740 cinder-volume[4072005]: WARNING amqp [None req-44c7b55f-d1fb-4cd9-bbf7-5cea2642e01c None None] Received method (60, 30) during closing channel 1. This method will be ignored
Aug 22 23:40:21 datacore-PowerEdge-R740 cinder-volume[4071783]: INFO oslo_service.service [None req-44c7b55f-d1fb-4cd9-bbf7-5cea2642e01c None None] Child 4072005 exited with status 0
Aug 22 23:40:21 datacore-PowerEdge-R740 cinder-volume[4071783]: /usr/lib/python3/dist-packages/secretstorage/dhcrypto.py:15: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
Aug 22 23:40:21 datacore-PowerEdge-R740 cinder-volume[4071783]:   from cryptography.utils import int_from_bytes
Aug 22 23:40:21 datacore-PowerEdge-R740 cinder-volume[4071783]: /usr/lib/python3/dist-packages/secretstorage/util.py:19: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
Aug 22 23:40:21 datacore-PowerEdge-R740 cinder-volume[4071783]:   from cryptography.utils import int_from_bytes
Aug 22 23:40:21 datacore-PowerEdge-R740 cinder-volume[4071783]: /opt/stack/cinder/cinder/db/sqlalchemy/models.py:152: SAWarning: implicitly coercing SELECT object to scalar subquery; please use the .scalar_subquery() method to produce a scalar subquery.
Aug 22 23:40:21 datacore-PowerEdge-R740 cinder-volume[4071783]:   last_heartbeat = column_property(
Aug 22 23:40:21 datacore-PowerEdge-R740 cinder-volume[4071783]: /opt/stack/cinder/cinder/db/sqlalchemy/models.py:160: SAWarning: implicitly coercing SELECT object to scalar subquery; please use the .scalar_subquery() method to produce a scalar subquery.
Aug 22 23:40:21 datacore-PowerEdge-R740 cinder-volume[4071783]:   num_hosts = column_property(
Aug 22 23:40:21 datacore-PowerEdge-R740 cinder-volume[4071783]: /opt/stack/cinder/cinder/db/sqlalchemy/models.py:169: SAWarning: implicitly coercing SELECT object to scalar subquery; please use the .scalar_subquery() method to produce a scalar subquery.
Aug 22 23:40:21 datacore-PowerEdge-R740 cinder-volume[4071783]:   num_down_hosts = column_property(
Aug 22 23:40:21 datacore-PowerEdge-R740 sudo[4072598]: pam_unix(sudo:session): session closed for user root
Aug 22 23:40:21 datacore-PowerEdge-R740 systemd[1]: devstack@c-vol.service: Succeeded.
Aug 22 23:40:21 datacore-PowerEdge-R740 systemd[1]: Stopped Devstack devstack@c-vol.service.
Aug 22 23:40:21 datacore-PowerEdge-R740 systemd[1]: Started Devstack devstack@c-vol.service.
Aug 22 23:40:23 datacore-PowerEdge-R740 cinder-volume[4072634]: DEBUG oslo_concurrency.lockutils [-] Acquiring lock "singleton_lock" {{(pid=4072634) lock /usr/local/lib/python3.8/dist-packages/oslo_concurrency/lockutils.py:293}}
Aug 22 23:40:23 datacore-PowerEdge-R740 cinder-volume[4072634]: DEBUG oslo_concurrency.lockutils [-] Acquired lock "singleton_lock" {{(pid=4072634) lock /usr/local/lib/python3.8/dist-packages/oslo_concurrency/lockutils.py:296}}
Aug 22 23:40:23 datacore-PowerEdge-R740 cinder-volume[4072634]: DEBUG oslo_concurrency.lockutils [-] Releasing lock "singleton_lock" {{(pid=4072634) lock /usr/local/lib/python3.8/dist-packages/oslo_concurrency/lockutils.py:314}}
Aug 22 23:40:24 datacore-PowerEdge-R740 cinder-volume[4072634]: INFO dbcounter [None req-76701be0-e9bf-46af-892a-b4cef94d83f3 None None] Registered counter for database cinder
Aug 22 23:40:24 datacore-PowerEdge-R740 cinder-volume[4072634]: DEBUG oslo_db.sqlalchemy.engines [None req-76701be0-e9bf-46af-892a-b4cef94d83f3 None None] MySQL server mode set to STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_ENGINE_SUBSTITUTION {{(pid=4072634) _check_effective_sql_mode /usr/local/lib/python3.8/dist-packages/oslo_db/sqlalchemy/engines.py:314}}
Aug 22 23:40:24 datacore-PowerEdge-R740 cinder-volume[4072634]: DEBUG dbcounter [-] [4072634] Writer thread running {{(pid=4072634) stat_writer /usr/local/lib/python3.8/dist-packages/dbcounter.py:99}}
Aug 22 23:40:24 datacore-PowerEdge-R740 cinder-volume[4072634]: INFO cinder.rpc [None req-76701be0-e9bf-46af-892a-b4cef94d83f3 None None] Automatically selected cinder-scheduler objects version 1.39 as minimum service version.
Aug 22 23:40:24 datacore-PowerEdge-R740 cinder-volume[4072634]: INFO cinder.rpc [None req-76701be0-e9bf-46af-892a-b4cef94d83f3 None None] Automatically selected cinder-scheduler RPC version 3.12 as minimum service version.
Aug 22 23:40:24 datacore-PowerEdge-R740 cinder-volume[4072634]: DEBUG oslo_db.sqlalchemy.engines [None req-76701be0-e9bf-46af-892a-b4cef94d83f3 None None] MySQL server mode set to STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_ENGINE_SUBSTITUTION {{(pid=4072634) _check_effective_sql_mode /usr/local/lib/python3.8/dist-packages/oslo_db/sqlalchemy/engines.py:314}}
Aug 22 23:40:24 datacore-PowerEdge-R740 cinder-volume[4072634]: INFO cinder.volume.manager [None req-76701be0-e9bf-46af-892a-b4cef94d83f3 None None] Determined volume DB was empty at startup.
Aug 22 23:40:24 datacore-PowerEdge-R740 cinder-volume[4072634]: DEBUG cinder.volume.manager [None req-76701be0-e9bf-46af-892a-b4cef94d83f3 None None] Cinder Volume DB check: vol_db_empty=True {{(pid=4072634) __init__ /opt/stack/cinder/cinder/volume/manager.py:286}}
Aug 22 23:40:24 datacore-PowerEdge-R740 cinder-volume[4072634]: INFO cinder.volume.manager [None req-76701be0-e9bf-46af-892a-b4cef94d83f3 None None] Service not found for updating active_backend_id, assuming default for driver init.
Aug 22 23:40:24 datacore-PowerEdge-R740 cinder-volume[4072634]: WARNING stevedore.named [None req-76701be0-e9bf-46af-892a-b4cef94d83f3 None None] Could not load cinder.keymgr.conf_key_mgr.ConfKeyManager
Aug 22 23:40:24 datacore-PowerEdge-R740 cinder-volume[4072634]: WARNING castellan.key_manager [None req-76701be0-e9bf-46af-892a-b4cef94d83f3 None None] Deprecation Warning : cinder.keymgr.conf_key_mgr.ConfKeyManager is not a stevedore based driver, trying to load it as a class: stevedore.exception.NoMatches: No 'castellan.drivers' driver found, looking for 'cinder.keymgr.conf_key_mgr.ConfKeyManager'
Aug 22 23:40:24 datacore-PowerEdge-R740 cinder-volume[4072634]: WARNING cinder.keymgr.conf_key_mgr [None req-76701be0-e9bf-46af-892a-b4cef94d83f3 None None] This key manager is insecure and is not recommended for production deployments: stevedore.exception.NoMatches: No 'castellan.drivers' driver found, looking for 'cinder.keymgr.conf_key_mgr.ConfKeyManager'
Aug 22 23:40:24 datacore-PowerEdge-R740 cinder-volume[4072634]: ERROR cinder.cmd.volume [None req-76701be0-e9bf-46af-892a-b4cef94d83f3 None None] Volume service hostgroup@datacore_iscsi1 failed to start.: ModuleNotFoundError: No module named 'cinder.volume.drivers.datacore.iscsi'
Aug 22 23:40:24 datacore-PowerEdge-R740 cinder-volume[4072634]: ERROR cinder.cmd.volume Traceback (most recent call last):
Aug 22 23:40:24 datacore-PowerEdge-R740 cinder-volume[4072634]: ERROR cinder.cmd.volume   File "/opt/stack/cinder/cinder/cmd/volume.py", line 99, in _launch_service
Aug 22 23:40:24 datacore-PowerEdge-R740 cinder-volume[4072634]: ERROR cinder.cmd.volume     server = service.Service.create(host=host,
Aug 22 23:40:24 datacore-PowerEdge-R740 cinder-volume[4072634]: ERROR cinder.cmd.volume   File "/opt/stack/cinder/cinder/service.py", line 394, in create
Aug 22 23:40:24 datacore-PowerEdge-R740 cinder-volume[4072634]: ERROR cinder.cmd.volume     service_obj = cls(host, binary, topic, manager,
Aug 22 23:40:24 datacore-PowerEdge-R740 cinder-volume[4072634]: ERROR cinder.cmd.volume   File "/opt/stack/cinder/cinder/service.py", line 152, in __init__
Aug 22 23:40:24 datacore-PowerEdge-R740 cinder-volume[4072634]: ERROR cinder.cmd.volume     self.manager = manager_class(host=self.host,
Aug 22 23:40:24 datacore-PowerEdge-R740 cinder-volume[4072634]: ERROR cinder.cmd.volume   File "/opt/stack/cinder/cinder/volume/manager.py", line 309, in __init__
Aug 22 23:40:24 datacore-PowerEdge-R740 cinder-volume[4072634]: ERROR cinder.cmd.volume     self.driver = importutils.import_object(
Aug 22 23:40:24 datacore-PowerEdge-R740 cinder-volume[4072634]: ERROR cinder.cmd.volume   File "/usr/local/lib/python3.8/dist-packages/oslo_utils/importutils.py", line 44, in import_object
Aug 22 23:40:24 datacore-PowerEdge-R740 cinder-volume[4072634]: ERROR cinder.cmd.volume     return import_class(import_str)(*args, **kwargs)
Aug 22 23:40:24 datacore-PowerEdge-R740 cinder-volume[4072634]: ERROR cinder.cmd.volume   File "/usr/local/lib/python3.8/dist-packages/oslo_utils/importutils.py", line 30, in import_class
Aug 22 23:40:24 datacore-PowerEdge-R740 cinder-volume[4072634]: ERROR cinder.cmd.volume     __import__(mod_str)
Aug 22 23:40:24 datacore-PowerEdge-R740 cinder-volume[4072634]: ERROR cinder.cmd.volume ModuleNotFoundError: No module named 'cinder.volume.drivers.datacore.iscsi'
Aug 22 23:40:24 datacore-PowerEdge-R740 cinder-volume[4072634]: ERROR cinder.cmd.volume 
Aug 22 23:40:24 datacore-PowerEdge-R740 cinder-volume[4072634]: ERROR cinder.cmd.volume [None req-76701be0-e9bf-46af-892a-b4cef94d83f3 None None] No volume service(s) started successfully, terminating.
Aug 22 23:40:24 datacore-PowerEdge-R740 cinder-volume[4072634]: /usr/lib/python3/dist-packages/secretstorage/dhcrypto.py:15: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
Aug 22 23:40:24 datacore-PowerEdge-R740 cinder-volume[4072634]:   from cryptography.utils import int_from_bytes
Aug 22 23:40:24 datacore-PowerEdge-R740 cinder-volume[4072634]: /usr/lib/python3/dist-packages/secretstorage/util.py:19: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
Aug 22 23:40:24 datacore-PowerEdge-R740 cinder-volume[4072634]:   from cryptography.utils import int_from_bytes
Aug 22 23:40:24 datacore-PowerEdge-R740 cinder-volume[4072634]: /opt/stack/cinder/cinder/db/sqlalchemy/models.py:152: SAWarning: implicitly coercing SELECT object to scalar subquery; please use the .scalar_subquery() method to produce a scalar subquery.
Aug 22 23:40:24 datacore-PowerEdge-R740 cinder-volume[4072634]:   last_heartbeat = column_property(
Aug 22 23:40:24 datacore-PowerEdge-R740 cinder-volume[4072634]: /opt/stack/cinder/cinder/db/sqlalchemy/models.py:160: SAWarning: implicitly coercing SELECT object to scalar subquery; please use the .scalar_subquery() method to produce a scalar subquery.
Aug 22 23:40:24 datacore-PowerEdge-R740 cinder-volume[4072634]:   num_hosts = column_property(
Aug 22 23:40:24 datacore-PowerEdge-R740 cinder-volume[4072634]: /opt/stack/cinder/cinder/db/sqlalchemy/models.py:169: SAWarning: implicitly coercing SELECT object to scalar subquery; please use the .scalar_subquery() method to produce a scalar subquery.
Aug 22 23:40:24 datacore-PowerEdge-R740 cinder-volume[4072634]:   num_down_hosts = column_property(
Aug 22 23:40:24 datacore-PowerEdge-R740 systemd[1]: devstack@c-vol.service: Main process exited, code=exited, status=1/FAILURE
Aug 22 23:40:24 datacore-PowerEdge-R740 systemd[1]: devstack@c-vol.service: Failed with result 'exit-code'.
