-- Logs begin at Thu 2022-07-28 04:50:48 IST, end at Thu 2022-07-28 04:52:05 IST. --
Jul 28 04:50:49 datacore-PowerEdge-R740 sudo[2390409]: pam_unix(sudo:session): session closed for user root
Jul 28 04:50:49 datacore-PowerEdge-R740 cinder-volume[2390317]: DEBUG oslo_concurrency.processutils [None req-79c1cb99-2aa0-4436-8cf4-c69442ea939c None None] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf lvchange -a y --yes -K stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool" returned: 0 in 0.887s {{(pid=2390317) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Jul 28 04:50:49 datacore-PowerEdge-R740 cinder-volume[2390317]: DEBUG oslo_concurrency.processutils [None req-79c1cb99-2aa0-4436-8cf4-c69442ea939c None None] Running cmd (subprocess): env LC_ALL=C lvm version {{(pid=2390317) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Jul 28 04:50:49 datacore-PowerEdge-R740 cinder-volume[2390317]: DEBUG oslo_concurrency.processutils [None req-79c1cb99-2aa0-4436-8cf4-c69442ea939c None None] CMD "env LC_ALL=C lvm version" returned: 0 in 0.017s {{(pid=2390317) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Jul 28 04:50:49 datacore-PowerEdge-R740 cinder-volume[2390317]: DEBUG oslo_concurrency.processutils [None req-79c1cb99-2aa0-4436-8cf4-c69442ea939c None None] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C pvs --noheadings --unit=g -o vg_name,name,size,free --separator | --nosuffix --ignoreskippedcluster {{(pid=2390317) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Jul 28 04:50:49 datacore-PowerEdge-R740 sudo[2390493]:    stack : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/local/bin/cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C pvs --noheadings --unit=g -o vg_name,name,size,free --separator | --nosuffix --ignoreskippedcluster
Jul 28 04:50:49 datacore-PowerEdge-R740 sudo[2390493]: pam_unix(sudo:session): session opened for user root by (uid=0)
Jul 28 04:50:50 datacore-PowerEdge-R740 sudo[2390493]: pam_unix(sudo:session): session closed for user root
Jul 28 04:50:50 datacore-PowerEdge-R740 cinder-volume[2390317]: DEBUG oslo_concurrency.processutils [None req-79c1cb99-2aa0-4436-8cf4-c69442ea939c None None] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C pvs --noheadings --unit=g -o vg_name,name,size,free --separator | --nosuffix --ignoreskippedcluster" returned: 0 in 0.812s {{(pid=2390317) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Jul 28 04:50:50 datacore-PowerEdge-R740 cinder-volume[2390317]: DEBUG oslo_concurrency.processutils [None req-79c1cb99-2aa0-4436-8cf4-c69442ea939c None None] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix stack-volumes-lvmdriver-1 {{(pid=2390317) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Jul 28 04:50:50 datacore-PowerEdge-R740 sudo[2390584]:    stack : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/local/bin/cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix stack-volumes-lvmdriver-1
Jul 28 04:50:50 datacore-PowerEdge-R740 sudo[2390584]: pam_unix(sudo:session): session opened for user root by (uid=0)
Jul 28 04:50:50 datacore-PowerEdge-R740 sudo[2390584]: pam_unix(sudo:session): session closed for user root
Jul 28 04:50:50 datacore-PowerEdge-R740 cinder-volume[2390317]: DEBUG oslo_concurrency.processutils [None req-79c1cb99-2aa0-4436-8cf4-c69442ea939c None None] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix stack-volumes-lvmdriver-1" returned: 0 in 0.661s {{(pid=2390317) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Jul 28 04:50:50 datacore-PowerEdge-R740 cinder-volume[2390317]: DEBUG oslo_concurrency.processutils [None req-79c1cb99-2aa0-4436-8cf4-c69442ea939c None None] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix stack-volumes-lvmdriver-1 {{(pid=2390317) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Jul 28 04:50:50 datacore-PowerEdge-R740 sudo[2390613]:    stack : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/local/bin/cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix stack-volumes-lvmdriver-1
Jul 28 04:50:50 datacore-PowerEdge-R740 sudo[2390613]: pam_unix(sudo:session): session opened for user root by (uid=0)
Jul 28 04:50:51 datacore-PowerEdge-R740 sudo[2390613]: pam_unix(sudo:session): session closed for user root
Jul 28 04:50:51 datacore-PowerEdge-R740 cinder-volume[2390317]: DEBUG oslo_concurrency.processutils [None req-79c1cb99-2aa0-4436-8cf4-c69442ea939c None None] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix stack-volumes-lvmdriver-1" returned: 0 in 0.711s {{(pid=2390317) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Jul 28 04:50:51 datacore-PowerEdge-R740 cinder-volume[2390317]: DEBUG oslo_concurrency.processutils [None req-79c1cb99-2aa0-4436-8cf4-c69442ea939c None None] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1 {{(pid=2390317) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Jul 28 04:50:51 datacore-PowerEdge-R740 sudo[2390738]:    stack : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/local/bin/cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1
Jul 28 04:50:51 datacore-PowerEdge-R740 sudo[2390738]: pam_unix(sudo:session): session opened for user root by (uid=0)
Jul 28 04:50:52 datacore-PowerEdge-R740 sudo[2390738]: pam_unix(sudo:session): session closed for user root
Jul 28 04:50:52 datacore-PowerEdge-R740 cinder-volume[2390317]: DEBUG oslo_concurrency.processutils [None req-79c1cb99-2aa0-4436-8cf4-c69442ea939c None None] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1" returned: 0 in 0.646s {{(pid=2390317) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Jul 28 04:50:52 datacore-PowerEdge-R740 cinder-volume[2390317]: DEBUG oslo_concurrency.processutils [None req-79c1cb99-2aa0-4436-8cf4-c69442ea939c None None] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o size,data_percent --separator : --nosuffix /dev/stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool {{(pid=2390317) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Jul 28 04:50:52 datacore-PowerEdge-R740 sudo[2390742]:    stack : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/local/bin/cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o size,data_percent --separator : --nosuffix /dev/stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool
Jul 28 04:50:52 datacore-PowerEdge-R740 sudo[2390742]: pam_unix(sudo:session): session opened for user root by (uid=0)
Jul 28 04:50:52 datacore-PowerEdge-R740 sudo[2390742]: pam_unix(sudo:session): session closed for user root
Jul 28 04:50:52 datacore-PowerEdge-R740 cinder-volume[2390317]: DEBUG oslo_concurrency.processutils [None req-79c1cb99-2aa0-4436-8cf4-c69442ea939c None None] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o size,data_percent --separator : --nosuffix /dev/stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool" returned: 0 in 0.627s {{(pid=2390317) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Jul 28 04:50:52 datacore-PowerEdge-R740 cinder-volume[2390317]: DEBUG oslo_concurrency.processutils [None req-79c1cb99-2aa0-4436-8cf4-c69442ea939c None None] Running cmd (subprocess): env LC_ALL=C lvm version {{(pid=2390317) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Jul 28 04:50:52 datacore-PowerEdge-R740 cinder-volume[2390317]: DEBUG oslo_concurrency.processutils [None req-79c1cb99-2aa0-4436-8cf4-c69442ea939c None None] CMD "env LC_ALL=C lvm version" returned: 0 in 0.020s {{(pid=2390317) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Jul 28 04:50:52 datacore-PowerEdge-R740 cinder-volume[2390317]: DEBUG oslo_concurrency.processutils [None req-79c1cb99-2aa0-4436-8cf4-c69442ea939c None None] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool {{(pid=2390317) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Jul 28 04:50:52 datacore-PowerEdge-R740 sudo[2390749]:    stack : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/local/bin/cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool
Jul 28 04:50:52 datacore-PowerEdge-R740 sudo[2390749]: pam_unix(sudo:session): session opened for user root by (uid=0)
Jul 28 04:50:53 datacore-PowerEdge-R740 sudo[2390749]: pam_unix(sudo:session): session closed for user root
Jul 28 04:50:53 datacore-PowerEdge-R740 cinder-volume[2390317]: DEBUG oslo_concurrency.processutils [None req-79c1cb99-2aa0-4436-8cf4-c69442ea939c None None] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool" returned: 0 in 0.609s {{(pid=2390317) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Jul 28 04:50:53 datacore-PowerEdge-R740 cinder-volume[2390317]: INFO cinder.volume.drivers.lvm [None req-79c1cb99-2aa0-4436-8cf4-c69442ea939c None None] Enabling LVM thin provisioning by default because a thin pool exists.
Jul 28 04:50:53 datacore-PowerEdge-R740 cinder-volume[2390317]: DEBUG oslo_concurrency.processutils [None req-79c1cb99-2aa0-4436-8cf4-c69442ea939c None None] Running cmd (subprocess): env LC_ALL=C lvm version {{(pid=2390317) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Jul 28 04:50:53 datacore-PowerEdge-R740 cinder-volume[2390317]: DEBUG oslo_concurrency.processutils [None req-79c1cb99-2aa0-4436-8cf4-c69442ea939c None None] CMD "env LC_ALL=C lvm version" returned: 0 in 0.018s {{(pid=2390317) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Jul 28 04:50:53 datacore-PowerEdge-R740 cinder-volume[2390317]: DEBUG oslo_concurrency.processutils [None req-79c1cb99-2aa0-4436-8cf4-c69442ea939c None None] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool {{(pid=2390317) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Jul 28 04:50:53 datacore-PowerEdge-R740 sudo[2390754]:    stack : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/local/bin/cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool
Jul 28 04:50:53 datacore-PowerEdge-R740 sudo[2390754]: pam_unix(sudo:session): session opened for user root by (uid=0)
Jul 28 04:50:54 datacore-PowerEdge-R740 sudo[2390754]: pam_unix(sudo:session): session closed for user root
Jul 28 04:50:54 datacore-PowerEdge-R740 cinder-volume[2390317]: DEBUG oslo_concurrency.processutils [None req-79c1cb99-2aa0-4436-8cf4-c69442ea939c None None] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool" returned: 0 in 0.623s {{(pid=2390317) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Jul 28 04:50:54 datacore-PowerEdge-R740 cinder-volume[2390317]: DEBUG cinder.volume.drivers.lvm [None req-79c1cb99-2aa0-4436-8cf4-c69442ea939c None None] Updating volume stats {{(pid=2390317) _update_volume_stats /opt/stack/cinder/cinder/volume/drivers/lvm.py:213}}
Jul 28 04:50:54 datacore-PowerEdge-R740 cinder-volume[2390317]: DEBUG oslo_concurrency.processutils [None req-79c1cb99-2aa0-4436-8cf4-c69442ea939c None None] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix stack-volumes-lvmdriver-1 {{(pid=2390317) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Jul 28 04:50:54 datacore-PowerEdge-R740 sudo[2390758]:    stack : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/local/bin/cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix stack-volumes-lvmdriver-1
Jul 28 04:50:54 datacore-PowerEdge-R740 sudo[2390758]: pam_unix(sudo:session): session opened for user root by (uid=0)
Jul 28 04:50:54 datacore-PowerEdge-R740 sudo[2390758]: pam_unix(sudo:session): session closed for user root
Jul 28 04:50:54 datacore-PowerEdge-R740 cinder-volume[2390317]: DEBUG oslo_concurrency.processutils [None req-79c1cb99-2aa0-4436-8cf4-c69442ea939c None None] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix stack-volumes-lvmdriver-1" returned: 0 in 0.646s {{(pid=2390317) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Jul 28 04:50:54 datacore-PowerEdge-R740 cinder-volume[2390317]: DEBUG oslo_concurrency.processutils [None req-79c1cb99-2aa0-4436-8cf4-c69442ea939c None None] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1 {{(pid=2390317) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Jul 28 04:50:54 datacore-PowerEdge-R740 sudo[2390773]:    stack : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/local/bin/cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1
Jul 28 04:50:54 datacore-PowerEdge-R740 sudo[2390773]: pam_unix(sudo:session): session opened for user root by (uid=0)
Jul 28 04:50:55 datacore-PowerEdge-R740 sudo[2390773]: pam_unix(sudo:session): session closed for user root
Jul 28 04:50:55 datacore-PowerEdge-R740 cinder-volume[2390317]: DEBUG oslo_concurrency.processutils [None req-79c1cb99-2aa0-4436-8cf4-c69442ea939c None None] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1" returned: 0 in 0.619s {{(pid=2390317) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Jul 28 04:50:55 datacore-PowerEdge-R740 cinder-volume[2390317]: DEBUG oslo_concurrency.processutils [None req-79c1cb99-2aa0-4436-8cf4-c69442ea939c None None] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o size,data_percent --separator : --nosuffix /dev/stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool {{(pid=2390317) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Jul 28 04:50:55 datacore-PowerEdge-R740 sudo[2390777]:    stack : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/local/bin/cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o size,data_percent --separator : --nosuffix /dev/stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool
Jul 28 04:50:55 datacore-PowerEdge-R740 sudo[2390777]: pam_unix(sudo:session): session opened for user root by (uid=0)
Jul 28 04:50:56 datacore-PowerEdge-R740 sudo[2390777]: pam_unix(sudo:session): session closed for user root
Jul 28 04:50:56 datacore-PowerEdge-R740 cinder-volume[2390317]: DEBUG oslo_concurrency.processutils [None req-79c1cb99-2aa0-4436-8cf4-c69442ea939c None None] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o size,data_percent --separator : --nosuffix /dev/stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool" returned: 0 in 0.627s {{(pid=2390317) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Jul 28 04:50:56 datacore-PowerEdge-R740 cinder-volume[2390317]: DEBUG oslo_concurrency.processutils [None req-79c1cb99-2aa0-4436-8cf4-c69442ea939c None None] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1 {{(pid=2390317) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Jul 28 04:50:56 datacore-PowerEdge-R740 sudo[2390789]:    stack : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/local/bin/cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1
Jul 28 04:50:56 datacore-PowerEdge-R740 sudo[2390789]: pam_unix(sudo:session): session opened for user root by (uid=0)
Jul 28 04:50:56 datacore-PowerEdge-R740 cinder-volume[2390103]: DEBUG dbcounter [-] [2390103] Writing DB stats cinder:SELECT=16,cinder:UPDATE=1 {{(pid=2390103) stat_writer /usr/local/lib/python3.8/dist-packages/dbcounter.py:114}}
Jul 28 04:50:56 datacore-PowerEdge-R740 sudo[2390789]: pam_unix(sudo:session): session closed for user root
Jul 28 04:50:56 datacore-PowerEdge-R740 cinder-volume[2390317]: DEBUG oslo_concurrency.processutils [None req-79c1cb99-2aa0-4436-8cf4-c69442ea939c None None] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1" returned: 0 in 0.650s {{(pid=2390317) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Jul 28 04:50:56 datacore-PowerEdge-R740 cinder-volume[2390317]: INFO cinder.volume.driver [None req-79c1cb99-2aa0-4436-8cf4-c69442ea939c None None] Driver hasn't implemented _init_vendor_properties()
Jul 28 04:50:56 datacore-PowerEdge-R740 cinder-volume[2390317]: DEBUG cinder.volume.driver [None req-79c1cb99-2aa0-4436-8cf4-c69442ea939c None None] Initialized capabilities list: {'volume_backend_name': 'lvmdriver-1', 'vendor_name': 'Open Source', 'driver_version': '3.0.0', 'storage_protocol': 'iSCSI', 'pools': [{'pool_name': 'lvmdriver-1', 'total_capacity_gb': 28.5, 'free_capacity_gb': 28.5, 'reserved_percentage': 0, 'location_info': 'LVMVolumeDriver:datacore-PowerEdge-R740:stack-volumes-lvmdriver-1:thin:0', 'QoS_support': False, 'provisioned_capacity_gb': 0.0, 'max_over_subscription_ratio': '20.0', 'thin_provisioning_support': True, 'thick_provisioning_support': False, 'total_volumes': 1, 'filter_function': None, 'goodness_function': None, 'multiattach': True, 'backend_state': 'up'}], 'shared_targets': False, 'sparse_copy_volume': True, 'properties': {'thin_provisioning': {'title': 'Thin Provisioning', 'description': 'Sets thin provisioning.', 'type': 'boolean'}, 'compression': {'title': 'Compression', 'description': 'Enables compression.', 'type': 'boolean'}, 'qos': {'title': 'QoS', 'description': 'Enables QoS.', 'type': 'boolean'}, 'replication_enabled': {'title': 'Replication', 'description': 'Enables replication.', 'type': 'boolean'}}}. {{(pid=2390317) init_capabilities /opt/stack/cinder/cinder/volume/driver.py:812}}
Jul 28 04:50:56 datacore-PowerEdge-R740 cinder-volume[2390317]: DEBUG oslo_db.sqlalchemy.engines [None req-79c1cb99-2aa0-4436-8cf4-c69442ea939c None None] MySQL server mode set to STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_ENGINE_SUBSTITUTION {{(pid=2390317) _check_effective_sql_mode /usr/local/lib/python3.8/dist-packages/oslo_db/sqlalchemy/engines.py:314}}
Jul 28 04:50:56 datacore-PowerEdge-R740 cinder-volume[2390317]: DEBUG dbcounter [-] [2390317] Writer thread running {{(pid=2390317) stat_writer /usr/local/lib/python3.8/dist-packages/dbcounter.py:99}}
Jul 28 04:50:56 datacore-PowerEdge-R740 cinder-volume[2390317]: DEBUG cinder.db.sqlalchemy.api [None req-79c1cb99-2aa0-4436-8cf4-c69442ea939c None None] Building query based on filter {{(pid=2390317) _process_snaps_filters /opt/stack/cinder/cinder/db/sqlalchemy/api.py:3878}}
Jul 28 04:50:56 datacore-PowerEdge-R740 cinder-volume[2390317]: DEBUG cinder.image.image_utils [None req-79c1cb99-2aa0-4436-8cf4-c69442ea939c None None] Configuration image_conversion_dir is None or the path doesn't exist. {{(pid=2390317) cleanup_temporary_file /opt/stack/cinder/cinder/image/image_utils.py:991}}
Jul 28 04:50:56 datacore-PowerEdge-R740 cinder-volume[2390317]: DEBUG cinder.volume.drivers.lvm [None req-79c1cb99-2aa0-4436-8cf4-c69442ea939c None None] Updating volume stats {{(pid=2390317) _update_volume_stats /opt/stack/cinder/cinder/volume/drivers/lvm.py:213}}
Jul 28 04:50:56 datacore-PowerEdge-R740 cinder-volume[2390317]: DEBUG oslo_concurrency.processutils [None req-79c1cb99-2aa0-4436-8cf4-c69442ea939c None None] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix stack-volumes-lvmdriver-1 {{(pid=2390317) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Jul 28 04:50:56 datacore-PowerEdge-R740 sudo[2390800]:    stack : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/local/bin/cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix stack-volumes-lvmdriver-1
Jul 28 04:50:56 datacore-PowerEdge-R740 sudo[2390800]: pam_unix(sudo:session): session opened for user root by (uid=0)
Jul 28 04:50:56 datacore-PowerEdge-R740 cinder-volume[2390317]: INFO cinder.keymgr.migration [None req-0511dd74-d94d-473c-9a4a-6a06a609de8c None None] Not migrating encryption keys because the ConfKeyManager is still in use.
Jul 28 04:50:57 datacore-PowerEdge-R740 sudo[2390800]: pam_unix(sudo:session): session closed for user root
Jul 28 04:50:57 datacore-PowerEdge-R740 cinder-volume[2390317]: DEBUG oslo_concurrency.processutils [None req-79c1cb99-2aa0-4436-8cf4-c69442ea939c None None] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix stack-volumes-lvmdriver-1" returned: 0 in 0.650s {{(pid=2390317) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Jul 28 04:50:57 datacore-PowerEdge-R740 cinder-volume[2390317]: DEBUG oslo_concurrency.processutils [None req-79c1cb99-2aa0-4436-8cf4-c69442ea939c None None] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1 {{(pid=2390317) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Jul 28 04:50:57 datacore-PowerEdge-R740 sudo[2390810]:    stack : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/local/bin/cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1
Jul 28 04:50:57 datacore-PowerEdge-R740 sudo[2390810]: pam_unix(sudo:session): session opened for user root by (uid=0)
Jul 28 04:50:58 datacore-PowerEdge-R740 sudo[2390810]: pam_unix(sudo:session): session closed for user root
Jul 28 04:50:58 datacore-PowerEdge-R740 cinder-volume[2390317]: DEBUG oslo_concurrency.processutils [None req-79c1cb99-2aa0-4436-8cf4-c69442ea939c None None] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1" returned: 0 in 0.663s {{(pid=2390317) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Jul 28 04:50:58 datacore-PowerEdge-R740 cinder-volume[2390317]: DEBUG oslo_concurrency.processutils [None req-79c1cb99-2aa0-4436-8cf4-c69442ea939c None None] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o size,data_percent --separator : --nosuffix /dev/stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool {{(pid=2390317) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Jul 28 04:50:58 datacore-PowerEdge-R740 sudo[2390818]:    stack : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/local/bin/cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o size,data_percent --separator : --nosuffix /dev/stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool
Jul 28 04:50:58 datacore-PowerEdge-R740 sudo[2390818]: pam_unix(sudo:session): session opened for user root by (uid=0)
Jul 28 04:50:58 datacore-PowerEdge-R740 sudo[2390818]: pam_unix(sudo:session): session closed for user root
Jul 28 04:50:58 datacore-PowerEdge-R740 cinder-volume[2390317]: DEBUG oslo_concurrency.processutils [None req-79c1cb99-2aa0-4436-8cf4-c69442ea939c None None] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o size,data_percent --separator : --nosuffix /dev/stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool" returned: 0 in 0.678s {{(pid=2390317) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Jul 28 04:50:58 datacore-PowerEdge-R740 cinder-volume[2390317]: DEBUG oslo_concurrency.processutils [None req-79c1cb99-2aa0-4436-8cf4-c69442ea939c None None] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1 {{(pid=2390317) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Jul 28 04:50:58 datacore-PowerEdge-R740 sudo[2390843]:    stack : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/local/bin/cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1
Jul 28 04:50:58 datacore-PowerEdge-R740 sudo[2390843]: pam_unix(sudo:session): session opened for user root by (uid=0)
Jul 28 04:50:59 datacore-PowerEdge-R740 sudo[2390843]: pam_unix(sudo:session): session closed for user root
Jul 28 04:50:59 datacore-PowerEdge-R740 cinder-volume[2390317]: DEBUG oslo_concurrency.processutils [None req-79c1cb99-2aa0-4436-8cf4-c69442ea939c None None] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1" returned: 0 in 0.662s {{(pid=2390317) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Jul 28 04:50:59 datacore-PowerEdge-R740 cinder-volume[2390317]: DEBUG cinder.manager [None req-79c1cb99-2aa0-4436-8cf4-c69442ea939c None None] Notifying Schedulers of capabilities ... {{(pid=2390317) _publish_service_capabilities /opt/stack/cinder/cinder/manager.py:202}}
Jul 28 04:50:59 datacore-PowerEdge-R740 cinder-volume[2390317]: INFO cinder.volume.manager [None req-79c1cb99-2aa0-4436-8cf4-c69442ea939c None None] Driver initialization completed successfully.
Jul 28 04:50:59 datacore-PowerEdge-R740 cinder-volume[2390317]: INFO cinder.manager [None req-79c1cb99-2aa0-4436-8cf4-c69442ea939c None None] Initiating service 2 cleanup
Jul 28 04:50:59 datacore-PowerEdge-R740 cinder-volume[2390317]: INFO cinder.manager [None req-79c1cb99-2aa0-4436-8cf4-c69442ea939c None None] Service 2 cleanup completed.
Jul 28 04:50:59 datacore-PowerEdge-R740 cinder-volume[2390317]: DEBUG cinder.service [None req-79c1cb99-2aa0-4436-8cf4-c69442ea939c None None] Creating RPC server for service cinder-volume {{(pid=2390317) start /opt/stack/cinder/cinder/service.py:231}}
Jul 28 04:50:59 datacore-PowerEdge-R740 cinder-volume[2390317]: DEBUG cinder.service [None req-79c1cb99-2aa0-4436-8cf4-c69442ea939c None None] Pinning object versions for RPC server serializer to 1.39 {{(pid=2390317) start /opt/stack/cinder/cinder/service.py:237}}
Jul 28 04:50:59 datacore-PowerEdge-R740 cinder-volume[2390317]: INFO cinder.volume.manager [None req-79c1cb99-2aa0-4436-8cf4-c69442ea939c None None] Initializing RPC dependent components of volume driver LVMVolumeDriver (3.0.0)
Jul 28 04:50:59 datacore-PowerEdge-R740 cinder-volume[2390317]: DEBUG cinder.volume.drivers.lvm [None req-79c1cb99-2aa0-4436-8cf4-c69442ea939c None None] Updating volume stats {{(pid=2390317) _update_volume_stats /opt/stack/cinder/cinder/volume/drivers/lvm.py:213}}
Jul 28 04:50:59 datacore-PowerEdge-R740 cinder-volume[2390317]: DEBUG oslo_concurrency.processutils [None req-79c1cb99-2aa0-4436-8cf4-c69442ea939c None None] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix stack-volumes-lvmdriver-1 {{(pid=2390317) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Jul 28 04:50:59 datacore-PowerEdge-R740 sudo[2390857]:    stack : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/local/bin/cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix stack-volumes-lvmdriver-1
Jul 28 04:50:59 datacore-PowerEdge-R740 sudo[2390857]: pam_unix(sudo:session): session opened for user root by (uid=0)
Jul 28 04:51:00 datacore-PowerEdge-R740 sudo[2390857]: pam_unix(sudo:session): session closed for user root
Jul 28 04:51:00 datacore-PowerEdge-R740 cinder-volume[2390317]: DEBUG oslo_concurrency.processutils [None req-79c1cb99-2aa0-4436-8cf4-c69442ea939c None None] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix stack-volumes-lvmdriver-1" returned: 0 in 0.651s {{(pid=2390317) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Jul 28 04:51:00 datacore-PowerEdge-R740 cinder-volume[2390317]: DEBUG oslo_concurrency.processutils [None req-79c1cb99-2aa0-4436-8cf4-c69442ea939c None None] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1 {{(pid=2390317) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Jul 28 04:51:00 datacore-PowerEdge-R740 sudo[2390869]:    stack : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/local/bin/cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1
Jul 28 04:51:00 datacore-PowerEdge-R740 sudo[2390869]: pam_unix(sudo:session): session opened for user root by (uid=0)
Jul 28 04:51:00 datacore-PowerEdge-R740 sudo[2390869]: pam_unix(sudo:session): session closed for user root
Jul 28 04:51:00 datacore-PowerEdge-R740 cinder-volume[2390317]: DEBUG oslo_concurrency.processutils [None req-79c1cb99-2aa0-4436-8cf4-c69442ea939c None None] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1" returned: 0 in 0.661s {{(pid=2390317) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Jul 28 04:51:00 datacore-PowerEdge-R740 cinder-volume[2390317]: DEBUG oslo_concurrency.processutils [None req-79c1cb99-2aa0-4436-8cf4-c69442ea939c None None] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o size,data_percent --separator : --nosuffix /dev/stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool {{(pid=2390317) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Jul 28 04:51:00 datacore-PowerEdge-R740 sudo[2390876]:    stack : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/local/bin/cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o size,data_percent --separator : --nosuffix /dev/stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool
Jul 28 04:51:00 datacore-PowerEdge-R740 sudo[2390876]: pam_unix(sudo:session): session opened for user root by (uid=0)
Jul 28 04:51:01 datacore-PowerEdge-R740 sudo[2390876]: pam_unix(sudo:session): session closed for user root
Jul 28 04:51:01 datacore-PowerEdge-R740 cinder-volume[2390317]: DEBUG oslo_concurrency.processutils [None req-79c1cb99-2aa0-4436-8cf4-c69442ea939c None None] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o size,data_percent --separator : --nosuffix /dev/stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool" returned: 0 in 0.653s {{(pid=2390317) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Jul 28 04:51:01 datacore-PowerEdge-R740 cinder-volume[2390317]: DEBUG oslo_concurrency.processutils [None req-79c1cb99-2aa0-4436-8cf4-c69442ea939c None None] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1 {{(pid=2390317) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Jul 28 04:51:01 datacore-PowerEdge-R740 sudo[2390911]:    stack : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/local/bin/cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1
Jul 28 04:51:01 datacore-PowerEdge-R740 sudo[2390911]: pam_unix(sudo:session): session opened for user root by (uid=0)
Jul 28 04:51:02 datacore-PowerEdge-R740 sudo[2390911]: pam_unix(sudo:session): session closed for user root
Jul 28 04:51:02 datacore-PowerEdge-R740 cinder-volume[2390317]: DEBUG oslo_concurrency.processutils [None req-79c1cb99-2aa0-4436-8cf4-c69442ea939c None None] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1" returned: 0 in 0.652s {{(pid=2390317) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Jul 28 04:51:02 datacore-PowerEdge-R740 cinder-volume[2390317]: INFO cinder.volume.manager [None req-79c1cb99-2aa0-4436-8cf4-c69442ea939c None None] Driver post RPC initialization completed successfully.
Jul 28 04:51:03 datacore-PowerEdge-R740 systemd[1]: Stopping Devstack devstack@c-vol.service...
Jul 28 04:51:03 datacore-PowerEdge-R740 cinder-volume[2390103]: INFO oslo_service.service [None req-9e731860-c897-40e5-aed6-2481dcb272a0 None None] Caught SIGTERM, stopping children
Jul 28 04:51:03 datacore-PowerEdge-R740 cinder-volume[2390103]: DEBUG oslo_concurrency.lockutils [None req-9e731860-c897-40e5-aed6-2481dcb272a0 None None] Acquired lock "singleton_lock" {{(pid=2390103) lock /usr/local/lib/python3.8/dist-packages/oslo_concurrency/lockutils.py:294}}
Jul 28 04:51:03 datacore-PowerEdge-R740 cinder-volume[2390103]: DEBUG oslo_concurrency.lockutils [None req-9e731860-c897-40e5-aed6-2481dcb272a0 None None] Releasing lock "singleton_lock" {{(pid=2390103) lock /usr/local/lib/python3.8/dist-packages/oslo_concurrency/lockutils.py:312}}
Jul 28 04:51:03 datacore-PowerEdge-R740 cinder-volume[2390103]: DEBUG oslo_service.service [None req-9e731860-c897-40e5-aed6-2481dcb272a0 None None] Stop services. {{(pid=2390103) stop /usr/local/lib/python3.8/dist-packages/oslo_service/service.py:695}}
Jul 28 04:51:03 datacore-PowerEdge-R740 cinder-volume[2390103]: DEBUG oslo_service.service [None req-9e731860-c897-40e5-aed6-2481dcb272a0 None None] Killing children. {{(pid=2390103) stop /usr/local/lib/python3.8/dist-packages/oslo_service/service.py:700}}
Jul 28 04:51:03 datacore-PowerEdge-R740 cinder-volume[2390103]: INFO oslo_service.service [None req-9e731860-c897-40e5-aed6-2481dcb272a0 None None] Waiting on 1 children to exit
Jul 28 04:51:03 datacore-PowerEdge-R740 cinder-volume[2390317]: DEBUG oslo_concurrency.lockutils [None req-9e731860-c897-40e5-aed6-2481dcb272a0 None None] Acquired lock "singleton_lock" {{(pid=2390317) lock /usr/local/lib/python3.8/dist-packages/oslo_concurrency/lockutils.py:294}}
Jul 28 04:51:03 datacore-PowerEdge-R740 cinder-volume[2390317]: DEBUG oslo_concurrency.lockutils [None req-9e731860-c897-40e5-aed6-2481dcb272a0 None None] Releasing lock "singleton_lock" {{(pid=2390317) lock /usr/local/lib/python3.8/dist-packages/oslo_concurrency/lockutils.py:312}}
Jul 28 04:51:03 datacore-PowerEdge-R740 cinder-volume[2390317]: WARNING amqp [None req-9e731860-c897-40e5-aed6-2481dcb272a0 None None] Received method (60, 30) during closing channel 1. This method will be ignored
Jul 28 04:51:03 datacore-PowerEdge-R740 cinder-volume[2390317]: WARNING amqp [None req-9e731860-c897-40e5-aed6-2481dcb272a0 None None] Received method (60, 30) during closing channel 1. This method will be ignored
Jul 28 04:51:03 datacore-PowerEdge-R740 cinder-volume[2390103]: INFO oslo_service.service [None req-9e731860-c897-40e5-aed6-2481dcb272a0 None None] Child 2390317 exited with status 0
Jul 28 04:51:03 datacore-PowerEdge-R740 cinder-volume[2390103]: /usr/lib/python3/dist-packages/secretstorage/dhcrypto.py:15: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
Jul 28 04:51:03 datacore-PowerEdge-R740 cinder-volume[2390103]:   from cryptography.utils import int_from_bytes
Jul 28 04:51:03 datacore-PowerEdge-R740 cinder-volume[2390103]: /usr/lib/python3/dist-packages/secretstorage/util.py:19: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
Jul 28 04:51:03 datacore-PowerEdge-R740 cinder-volume[2390103]:   from cryptography.utils import int_from_bytes
Jul 28 04:51:03 datacore-PowerEdge-R740 cinder-volume[2390103]: /opt/stack/cinder/cinder/db/sqlalchemy/models.py:152: SAWarning: implicitly coercing SELECT object to scalar subquery; please use the .scalar_subquery() method to produce a scalar subquery.
Jul 28 04:51:03 datacore-PowerEdge-R740 cinder-volume[2390103]:   last_heartbeat = column_property(
Jul 28 04:51:03 datacore-PowerEdge-R740 cinder-volume[2390103]: /opt/stack/cinder/cinder/db/sqlalchemy/models.py:160: SAWarning: implicitly coercing SELECT object to scalar subquery; please use the .scalar_subquery() method to produce a scalar subquery.
Jul 28 04:51:03 datacore-PowerEdge-R740 cinder-volume[2390103]:   num_hosts = column_property(
Jul 28 04:51:03 datacore-PowerEdge-R740 cinder-volume[2390103]: /opt/stack/cinder/cinder/db/sqlalchemy/models.py:169: SAWarning: implicitly coercing SELECT object to scalar subquery; please use the .scalar_subquery() method to produce a scalar subquery.
Jul 28 04:51:03 datacore-PowerEdge-R740 cinder-volume[2390103]:   num_down_hosts = column_property(
Jul 28 04:51:03 datacore-PowerEdge-R740 systemd[1]: devstack@c-vol.service: Succeeded.
Jul 28 04:51:03 datacore-PowerEdge-R740 systemd[1]: Stopped Devstack devstack@c-vol.service.
Jul 28 04:51:03 datacore-PowerEdge-R740 systemd[1]: Started Devstack devstack@c-vol.service.
Jul 28 04:51:05 datacore-PowerEdge-R740 cinder-volume[2390956]: DEBUG oslo_concurrency.lockutils [-] Acquired lock "singleton_lock" {{(pid=2390956) lock /usr/local/lib/python3.8/dist-packages/oslo_concurrency/lockutils.py:294}}
Jul 28 04:51:05 datacore-PowerEdge-R740 cinder-volume[2390956]: DEBUG oslo_concurrency.lockutils [-] Releasing lock "singleton_lock" {{(pid=2390956) lock /usr/local/lib/python3.8/dist-packages/oslo_concurrency/lockutils.py:312}}
Jul 28 04:51:06 datacore-PowerEdge-R740 cinder-volume[2390956]: INFO dbcounter [None req-7fa71e86-3edb-424a-86ae-4cc0275dbb50 None None] Registered counter for database cinder
Jul 28 04:51:06 datacore-PowerEdge-R740 cinder-volume[2390956]: DEBUG oslo_db.sqlalchemy.engines [None req-7fa71e86-3edb-424a-86ae-4cc0275dbb50 None None] MySQL server mode set to STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_ENGINE_SUBSTITUTION {{(pid=2390956) _check_effective_sql_mode /usr/local/lib/python3.8/dist-packages/oslo_db/sqlalchemy/engines.py:314}}
Jul 28 04:51:06 datacore-PowerEdge-R740 cinder-volume[2390956]: DEBUG dbcounter [-] [2390956] Writer thread running {{(pid=2390956) stat_writer /usr/local/lib/python3.8/dist-packages/dbcounter.py:99}}
Jul 28 04:51:06 datacore-PowerEdge-R740 cinder-volume[2390956]: INFO cinder.rpc [None req-7fa71e86-3edb-424a-86ae-4cc0275dbb50 None None] Automatically selected cinder-scheduler objects version 1.39 as minimum service version.
Jul 28 04:51:06 datacore-PowerEdge-R740 cinder-volume[2390956]: INFO cinder.rpc [None req-7fa71e86-3edb-424a-86ae-4cc0275dbb50 None None] Automatically selected cinder-scheduler RPC version 3.12 as minimum service version.
Jul 28 04:51:06 datacore-PowerEdge-R740 cinder-volume[2390956]: DEBUG oslo_db.sqlalchemy.engines [None req-7fa71e86-3edb-424a-86ae-4cc0275dbb50 None None] MySQL server mode set to STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_ENGINE_SUBSTITUTION {{(pid=2390956) _check_effective_sql_mode /usr/local/lib/python3.8/dist-packages/oslo_db/sqlalchemy/engines.py:314}}
Jul 28 04:51:06 datacore-PowerEdge-R740 cinder-volume[2390956]: INFO cinder.volume.manager [None req-7fa71e86-3edb-424a-86ae-4cc0275dbb50 None None] Determined volume DB was empty at startup.
Jul 28 04:51:06 datacore-PowerEdge-R740 cinder-volume[2390956]: DEBUG cinder.volume.manager [None req-7fa71e86-3edb-424a-86ae-4cc0275dbb50 None None] Cinder Volume DB check: vol_db_empty=True {{(pid=2390956) __init__ /opt/stack/cinder/cinder/volume/manager.py:290}}
Jul 28 04:51:06 datacore-PowerEdge-R740 cinder-volume[2390956]: INFO cinder.volume.manager [None req-7fa71e86-3edb-424a-86ae-4cc0275dbb50 None None] Service not found for updating active_backend_id, assuming default for driver init.
Jul 28 04:51:06 datacore-PowerEdge-R740 cinder-volume[2390956]: WARNING stevedore.named [None req-7fa71e86-3edb-424a-86ae-4cc0275dbb50 None None] Could not load cinder.keymgr.conf_key_mgr.ConfKeyManager
Jul 28 04:51:06 datacore-PowerEdge-R740 cinder-volume[2390956]: WARNING castellan.key_manager [None req-7fa71e86-3edb-424a-86ae-4cc0275dbb50 None None] Deprecation Warning : cinder.keymgr.conf_key_mgr.ConfKeyManager is not a stevedore based driver, trying to load it as a class: stevedore.exception.NoMatches: No 'castellan.drivers' driver found, looking for 'cinder.keymgr.conf_key_mgr.ConfKeyManager'
Jul 28 04:51:06 datacore-PowerEdge-R740 cinder-volume[2390956]: WARNING cinder.keymgr.conf_key_mgr [None req-7fa71e86-3edb-424a-86ae-4cc0275dbb50 None None] This key manager is insecure and is not recommended for production deployments: stevedore.exception.NoMatches: No 'castellan.drivers' driver found, looking for 'cinder.keymgr.conf_key_mgr.ConfKeyManager'
Jul 28 04:51:06 datacore-PowerEdge-R740 cinder-volume[2390956]: ERROR cinder.cmd.volume [None req-7fa71e86-3edb-424a-86ae-4cc0275dbb50 None None] Volume service hostgroup@datacore_iscsi1 failed to start.: ModuleNotFoundError: No module named 'cinder.volume.drivers.datacore.iscsi'
Jul 28 04:51:06 datacore-PowerEdge-R740 cinder-volume[2390956]: ERROR cinder.cmd.volume Traceback (most recent call last):
Jul 28 04:51:06 datacore-PowerEdge-R740 cinder-volume[2390956]: ERROR cinder.cmd.volume   File "/opt/stack/cinder/cinder/cmd/volume.py", line 99, in _launch_service
Jul 28 04:51:06 datacore-PowerEdge-R740 cinder-volume[2390956]: ERROR cinder.cmd.volume     server = service.Service.create(host=host,
Jul 28 04:51:06 datacore-PowerEdge-R740 cinder-volume[2390956]: ERROR cinder.cmd.volume   File "/opt/stack/cinder/cinder/service.py", line 394, in create
Jul 28 04:51:06 datacore-PowerEdge-R740 cinder-volume[2390956]: ERROR cinder.cmd.volume     service_obj = cls(host, binary, topic, manager,
Jul 28 04:51:06 datacore-PowerEdge-R740 cinder-volume[2390956]: ERROR cinder.cmd.volume   File "/opt/stack/cinder/cinder/service.py", line 152, in __init__
Jul 28 04:51:06 datacore-PowerEdge-R740 cinder-volume[2390956]: ERROR cinder.cmd.volume     self.manager = manager_class(host=self.host,
Jul 28 04:51:06 datacore-PowerEdge-R740 cinder-volume[2390956]: ERROR cinder.cmd.volume   File "/opt/stack/cinder/cinder/volume/manager.py", line 313, in __init__
Jul 28 04:51:06 datacore-PowerEdge-R740 cinder-volume[2390956]: ERROR cinder.cmd.volume     self.driver = importutils.import_object(
Jul 28 04:51:06 datacore-PowerEdge-R740 cinder-volume[2390956]: ERROR cinder.cmd.volume   File "/usr/local/lib/python3.8/dist-packages/oslo_utils/importutils.py", line 44, in import_object
Jul 28 04:51:06 datacore-PowerEdge-R740 cinder-volume[2390956]: ERROR cinder.cmd.volume     return import_class(import_str)(*args, **kwargs)
Jul 28 04:51:06 datacore-PowerEdge-R740 cinder-volume[2390956]: ERROR cinder.cmd.volume   File "/usr/local/lib/python3.8/dist-packages/oslo_utils/importutils.py", line 30, in import_class
Jul 28 04:51:06 datacore-PowerEdge-R740 cinder-volume[2390956]: ERROR cinder.cmd.volume     __import__(mod_str)
Jul 28 04:51:06 datacore-PowerEdge-R740 cinder-volume[2390956]: ERROR cinder.cmd.volume ModuleNotFoundError: No module named 'cinder.volume.drivers.datacore.iscsi'
Jul 28 04:51:06 datacore-PowerEdge-R740 cinder-volume[2390956]: ERROR cinder.cmd.volume 
Jul 28 04:51:06 datacore-PowerEdge-R740 cinder-volume[2390956]: ERROR cinder.cmd.volume [None req-7fa71e86-3edb-424a-86ae-4cc0275dbb50 None None] No volume service(s) started successfully, terminating.
Jul 28 04:51:06 datacore-PowerEdge-R740 cinder-volume[2390956]: /usr/lib/python3/dist-packages/secretstorage/dhcrypto.py:15: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
Jul 28 04:51:06 datacore-PowerEdge-R740 cinder-volume[2390956]:   from cryptography.utils import int_from_bytes
Jul 28 04:51:06 datacore-PowerEdge-R740 cinder-volume[2390956]: /usr/lib/python3/dist-packages/secretstorage/util.py:19: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
Jul 28 04:51:06 datacore-PowerEdge-R740 cinder-volume[2390956]:   from cryptography.utils import int_from_bytes
Jul 28 04:51:06 datacore-PowerEdge-R740 cinder-volume[2390956]: /opt/stack/cinder/cinder/db/sqlalchemy/models.py:152: SAWarning: implicitly coercing SELECT object to scalar subquery; please use the .scalar_subquery() method to produce a scalar subquery.
Jul 28 04:51:06 datacore-PowerEdge-R740 cinder-volume[2390956]:   last_heartbeat = column_property(
Jul 28 04:51:06 datacore-PowerEdge-R740 cinder-volume[2390956]: /opt/stack/cinder/cinder/db/sqlalchemy/models.py:160: SAWarning: implicitly coercing SELECT object to scalar subquery; please use the .scalar_subquery() method to produce a scalar subquery.
Jul 28 04:51:06 datacore-PowerEdge-R740 cinder-volume[2390956]:   num_hosts = column_property(
Jul 28 04:51:06 datacore-PowerEdge-R740 cinder-volume[2390956]: /opt/stack/cinder/cinder/db/sqlalchemy/models.py:169: SAWarning: implicitly coercing SELECT object to scalar subquery; please use the .scalar_subquery() method to produce a scalar subquery.
Jul 28 04:51:06 datacore-PowerEdge-R740 cinder-volume[2390956]:   num_down_hosts = column_property(
Jul 28 04:51:07 datacore-PowerEdge-R740 systemd[1]: devstack@c-vol.service: Main process exited, code=exited, status=1/FAILURE
Jul 28 04:51:07 datacore-PowerEdge-R740 systemd[1]: devstack@c-vol.service: Failed with result 'exit-code'.
