-- Logs begin at Mon 2022-08-22 17:36:57 IST, end at Mon 2022-08-22 17:38:13 IST. --
Aug 22 17:36:57 datacore-PowerEdge-R740 sudo[3296213]: pam_unix(sudo:session): session closed for user root
Aug 22 17:36:57 datacore-PowerEdge-R740 cinder-volume[3295994]: DEBUG oslo_concurrency.processutils [None req-afcd071b-36c5-415f-9bfb-3fe85d1dc253 None None] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix stack-volumes-lvmdriver-1" returned: 0 in 0.689s {{(pid=3295994) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Aug 22 17:36:57 datacore-PowerEdge-R740 cinder-volume[3295994]: DEBUG oslo_concurrency.processutils [None req-afcd071b-36c5-415f-9bfb-3fe85d1dc253 None None] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix stack-volumes-lvmdriver-1 {{(pid=3295994) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Aug 22 17:36:57 datacore-PowerEdge-R740 sudo[3296280]:    stack : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/local/bin/cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix stack-volumes-lvmdriver-1
Aug 22 17:36:57 datacore-PowerEdge-R740 sudo[3296280]: pam_unix(sudo:session): session opened for user root by (uid=0)
Aug 22 17:36:58 datacore-PowerEdge-R740 sudo[3296280]: pam_unix(sudo:session): session closed for user root
Aug 22 17:36:58 datacore-PowerEdge-R740 cinder-volume[3295994]: DEBUG oslo_concurrency.processutils [None req-afcd071b-36c5-415f-9bfb-3fe85d1dc253 None None] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix stack-volumes-lvmdriver-1" returned: 0 in 0.642s {{(pid=3295994) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Aug 22 17:36:58 datacore-PowerEdge-R740 cinder-volume[3295994]: DEBUG oslo_concurrency.processutils [None req-afcd071b-36c5-415f-9bfb-3fe85d1dc253 None None] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1 {{(pid=3295994) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Aug 22 17:36:58 datacore-PowerEdge-R740 sudo[3296290]:    stack : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/local/bin/cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1
Aug 22 17:36:58 datacore-PowerEdge-R740 sudo[3296290]: pam_unix(sudo:session): session opened for user root by (uid=0)
Aug 22 17:36:59 datacore-PowerEdge-R740 sudo[3296290]: pam_unix(sudo:session): session closed for user root
Aug 22 17:36:59 datacore-PowerEdge-R740 cinder-volume[3295994]: DEBUG oslo_concurrency.processutils [None req-afcd071b-36c5-415f-9bfb-3fe85d1dc253 None None] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1" returned: 0 in 0.745s {{(pid=3295994) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Aug 22 17:36:59 datacore-PowerEdge-R740 cinder-volume[3295994]: DEBUG oslo_concurrency.processutils [None req-afcd071b-36c5-415f-9bfb-3fe85d1dc253 None None] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o size,data_percent --separator : --nosuffix /dev/stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool {{(pid=3295994) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Aug 22 17:36:59 datacore-PowerEdge-R740 sudo[3296331]:    stack : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/local/bin/cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o size,data_percent --separator : --nosuffix /dev/stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool
Aug 22 17:36:59 datacore-PowerEdge-R740 sudo[3296331]: pam_unix(sudo:session): session opened for user root by (uid=0)
Aug 22 17:36:59 datacore-PowerEdge-R740 sudo[3296331]: pam_unix(sudo:session): session closed for user root
Aug 22 17:36:59 datacore-PowerEdge-R740 cinder-volume[3295994]: DEBUG oslo_concurrency.processutils [None req-afcd071b-36c5-415f-9bfb-3fe85d1dc253 None None] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o size,data_percent --separator : --nosuffix /dev/stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool" returned: 0 in 0.698s {{(pid=3295994) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Aug 22 17:36:59 datacore-PowerEdge-R740 cinder-volume[3295994]: DEBUG oslo_concurrency.processutils [None req-afcd071b-36c5-415f-9bfb-3fe85d1dc253 None None] Running cmd (subprocess): env LC_ALL=C lvm version {{(pid=3295994) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Aug 22 17:36:59 datacore-PowerEdge-R740 cinder-volume[3295994]: DEBUG oslo_concurrency.processutils [None req-afcd071b-36c5-415f-9bfb-3fe85d1dc253 None None] CMD "env LC_ALL=C lvm version" returned: 0 in 0.020s {{(pid=3295994) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Aug 22 17:36:59 datacore-PowerEdge-R740 cinder-volume[3295994]: DEBUG oslo_concurrency.processutils [None req-afcd071b-36c5-415f-9bfb-3fe85d1dc253 None None] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool {{(pid=3295994) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Aug 22 17:37:00 datacore-PowerEdge-R740 sudo[3296337]:    stack : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/local/bin/cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool
Aug 22 17:37:00 datacore-PowerEdge-R740 sudo[3296337]: pam_unix(sudo:session): session opened for user root by (uid=0)
Aug 22 17:37:00 datacore-PowerEdge-R740 sudo[3296337]: pam_unix(sudo:session): session closed for user root
Aug 22 17:37:00 datacore-PowerEdge-R740 cinder-volume[3295994]: DEBUG oslo_concurrency.processutils [None req-afcd071b-36c5-415f-9bfb-3fe85d1dc253 None None] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool" returned: 0 in 0.635s {{(pid=3295994) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Aug 22 17:37:00 datacore-PowerEdge-R740 cinder-volume[3295994]: INFO cinder.volume.drivers.lvm [None req-afcd071b-36c5-415f-9bfb-3fe85d1dc253 None None] Enabling LVM thin provisioning by default because a thin pool exists.
Aug 22 17:37:00 datacore-PowerEdge-R740 cinder-volume[3295994]: DEBUG oslo_concurrency.processutils [None req-afcd071b-36c5-415f-9bfb-3fe85d1dc253 None None] Running cmd (subprocess): env LC_ALL=C lvm version {{(pid=3295994) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Aug 22 17:37:00 datacore-PowerEdge-R740 cinder-volume[3295994]: DEBUG oslo_concurrency.processutils [None req-afcd071b-36c5-415f-9bfb-3fe85d1dc253 None None] CMD "env LC_ALL=C lvm version" returned: 0 in 0.020s {{(pid=3295994) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Aug 22 17:37:00 datacore-PowerEdge-R740 cinder-volume[3295994]: DEBUG oslo_concurrency.processutils [None req-afcd071b-36c5-415f-9bfb-3fe85d1dc253 None None] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool {{(pid=3295994) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Aug 22 17:37:00 datacore-PowerEdge-R740 sudo[3296342]:    stack : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/local/bin/cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool
Aug 22 17:37:00 datacore-PowerEdge-R740 sudo[3296342]: pam_unix(sudo:session): session opened for user root by (uid=0)
Aug 22 17:37:01 datacore-PowerEdge-R740 sudo[3296342]: pam_unix(sudo:session): session closed for user root
Aug 22 17:37:01 datacore-PowerEdge-R740 cinder-volume[3295994]: DEBUG oslo_concurrency.processutils [None req-afcd071b-36c5-415f-9bfb-3fe85d1dc253 None None] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool" returned: 0 in 0.628s {{(pid=3295994) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Aug 22 17:37:01 datacore-PowerEdge-R740 cinder-volume[3295994]: DEBUG cinder.volume.drivers.lvm [None req-afcd071b-36c5-415f-9bfb-3fe85d1dc253 None None] Updating volume stats {{(pid=3295994) _update_volume_stats /opt/stack/cinder/cinder/volume/drivers/lvm.py:213}}
Aug 22 17:37:01 datacore-PowerEdge-R740 cinder-volume[3295994]: DEBUG oslo_concurrency.processutils [None req-afcd071b-36c5-415f-9bfb-3fe85d1dc253 None None] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix stack-volumes-lvmdriver-1 {{(pid=3295994) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Aug 22 17:37:01 datacore-PowerEdge-R740 sudo[3296348]:    stack : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/local/bin/cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix stack-volumes-lvmdriver-1
Aug 22 17:37:01 datacore-PowerEdge-R740 sudo[3296348]: pam_unix(sudo:session): session opened for user root by (uid=0)
Aug 22 17:37:01 datacore-PowerEdge-R740 sudo[3296348]: pam_unix(sudo:session): session closed for user root
Aug 22 17:37:01 datacore-PowerEdge-R740 cinder-volume[3295994]: DEBUG oslo_concurrency.processutils [None req-afcd071b-36c5-415f-9bfb-3fe85d1dc253 None None] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix stack-volumes-lvmdriver-1" returned: 0 in 0.645s {{(pid=3295994) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Aug 22 17:37:01 datacore-PowerEdge-R740 cinder-volume[3295994]: DEBUG oslo_concurrency.processutils [None req-afcd071b-36c5-415f-9bfb-3fe85d1dc253 None None] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1 {{(pid=3295994) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Aug 22 17:37:01 datacore-PowerEdge-R740 sudo[3296352]:    stack : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/local/bin/cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1
Aug 22 17:37:01 datacore-PowerEdge-R740 sudo[3296352]: pam_unix(sudo:session): session opened for user root by (uid=0)
Aug 22 17:37:02 datacore-PowerEdge-R740 sudo[3296352]: pam_unix(sudo:session): session closed for user root
Aug 22 17:37:02 datacore-PowerEdge-R740 cinder-volume[3295994]: DEBUG oslo_concurrency.processutils [None req-afcd071b-36c5-415f-9bfb-3fe85d1dc253 None None] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1" returned: 0 in 0.621s {{(pid=3295994) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Aug 22 17:37:02 datacore-PowerEdge-R740 cinder-volume[3295994]: DEBUG oslo_concurrency.processutils [None req-afcd071b-36c5-415f-9bfb-3fe85d1dc253 None None] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o size,data_percent --separator : --nosuffix /dev/stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool {{(pid=3295994) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Aug 22 17:37:02 datacore-PowerEdge-R740 sudo[3296368]:    stack : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/local/bin/cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o size,data_percent --separator : --nosuffix /dev/stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool
Aug 22 17:37:02 datacore-PowerEdge-R740 sudo[3296368]: pam_unix(sudo:session): session opened for user root by (uid=0)
Aug 22 17:37:02 datacore-PowerEdge-R740 cinder-volume[3295785]: DEBUG dbcounter [-] [3295785] Writing DB stats cinder:SELECT=16,cinder:UPDATE=1 {{(pid=3295785) stat_writer /usr/local/lib/python3.8/dist-packages/dbcounter.py:114}}
Aug 22 17:37:03 datacore-PowerEdge-R740 sudo[3296368]: pam_unix(sudo:session): session closed for user root
Aug 22 17:37:03 datacore-PowerEdge-R740 cinder-volume[3295994]: DEBUG oslo_concurrency.processutils [None req-afcd071b-36c5-415f-9bfb-3fe85d1dc253 None None] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o size,data_percent --separator : --nosuffix /dev/stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool" returned: 0 in 0.645s {{(pid=3295994) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Aug 22 17:37:03 datacore-PowerEdge-R740 cinder-volume[3295994]: DEBUG oslo_concurrency.processutils [None req-afcd071b-36c5-415f-9bfb-3fe85d1dc253 None None] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1 {{(pid=3295994) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Aug 22 17:37:03 datacore-PowerEdge-R740 sudo[3296375]:    stack : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/local/bin/cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1
Aug 22 17:37:03 datacore-PowerEdge-R740 sudo[3296375]: pam_unix(sudo:session): session opened for user root by (uid=0)
Aug 22 17:37:03 datacore-PowerEdge-R740 sudo[3296375]: pam_unix(sudo:session): session closed for user root
Aug 22 17:37:03 datacore-PowerEdge-R740 cinder-volume[3295994]: DEBUG oslo_concurrency.processutils [None req-afcd071b-36c5-415f-9bfb-3fe85d1dc253 None None] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1" returned: 0 in 0.627s {{(pid=3295994) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Aug 22 17:37:03 datacore-PowerEdge-R740 cinder-volume[3295994]: INFO cinder.volume.driver [None req-afcd071b-36c5-415f-9bfb-3fe85d1dc253 None None] Driver hasn't implemented _init_vendor_properties()
Aug 22 17:37:03 datacore-PowerEdge-R740 cinder-volume[3295994]: DEBUG cinder.volume.driver [None req-afcd071b-36c5-415f-9bfb-3fe85d1dc253 None None] Initialized capabilities list: {'volume_backend_name': 'lvmdriver-1', 'vendor_name': 'Open Source', 'driver_version': '3.0.0', 'storage_protocol': 'iSCSI', 'pools': [{'pool_name': 'lvmdriver-1', 'total_capacity_gb': 28.5, 'free_capacity_gb': 28.5, 'reserved_percentage': 0, 'location_info': 'LVMVolumeDriver:datacore-PowerEdge-R740:stack-volumes-lvmdriver-1:thin:0', 'QoS_support': False, 'provisioned_capacity_gb': 0.0, 'max_over_subscription_ratio': '20.0', 'thin_provisioning_support': True, 'thick_provisioning_support': False, 'total_volumes': 1, 'filter_function': None, 'goodness_function': None, 'multiattach': True, 'backend_state': 'up'}], 'shared_targets': False, 'sparse_copy_volume': True, 'properties': {'thin_provisioning': {'title': 'Thin Provisioning', 'description': 'Sets thin provisioning.', 'type': 'boolean'}, 'compression': {'title': 'Compression', 'description': 'Enables compression.', 'type': 'boolean'}, 'qos': {'title': 'QoS', 'description': 'Enables QoS.', 'type': 'boolean'}, 'replication_enabled': {'title': 'Replication', 'description': 'Enables replication.', 'type': 'boolean'}}}. {{(pid=3295994) init_capabilities /opt/stack/cinder/cinder/volume/driver.py:812}}
Aug 22 17:37:03 datacore-PowerEdge-R740 cinder-volume[3295994]: DEBUG oslo_db.sqlalchemy.engines [None req-afcd071b-36c5-415f-9bfb-3fe85d1dc253 None None] MySQL server mode set to STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_ENGINE_SUBSTITUTION {{(pid=3295994) _check_effective_sql_mode /usr/local/lib/python3.8/dist-packages/oslo_db/sqlalchemy/engines.py:314}}
Aug 22 17:37:03 datacore-PowerEdge-R740 cinder-volume[3295994]: DEBUG dbcounter [-] [3295994] Writer thread running {{(pid=3295994) stat_writer /usr/local/lib/python3.8/dist-packages/dbcounter.py:99}}
Aug 22 17:37:03 datacore-PowerEdge-R740 cinder-volume[3295994]: DEBUG cinder.db.sqlalchemy.api [None req-afcd071b-36c5-415f-9bfb-3fe85d1dc253 None None] Building query based on filter {{(pid=3295994) _process_snaps_filters /opt/stack/cinder/cinder/db/sqlalchemy/api.py:3878}}
Aug 22 17:37:03 datacore-PowerEdge-R740 cinder-volume[3295994]: DEBUG cinder.image.image_utils [None req-afcd071b-36c5-415f-9bfb-3fe85d1dc253 None None] Configuration image_conversion_dir is None or the path doesn't exist. {{(pid=3295994) cleanup_temporary_file /opt/stack/cinder/cinder/image/image_utils.py:991}}
Aug 22 17:37:03 datacore-PowerEdge-R740 cinder-volume[3295994]: DEBUG cinder.volume.drivers.lvm [None req-afcd071b-36c5-415f-9bfb-3fe85d1dc253 None None] Updating volume stats {{(pid=3295994) _update_volume_stats /opt/stack/cinder/cinder/volume/drivers/lvm.py:213}}
Aug 22 17:37:03 datacore-PowerEdge-R740 cinder-volume[3295994]: DEBUG oslo_concurrency.processutils [None req-afcd071b-36c5-415f-9bfb-3fe85d1dc253 None None] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix stack-volumes-lvmdriver-1 {{(pid=3295994) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Aug 22 17:37:03 datacore-PowerEdge-R740 sudo[3296382]:    stack : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/local/bin/cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix stack-volumes-lvmdriver-1
Aug 22 17:37:03 datacore-PowerEdge-R740 sudo[3296382]: pam_unix(sudo:session): session opened for user root by (uid=0)
Aug 22 17:37:03 datacore-PowerEdge-R740 cinder-volume[3295994]: INFO cinder.keymgr.migration [None req-d5ee03da-f514-4646-82cc-8547724acb51 None None] Not migrating encryption keys because the ConfKeyManager is still in use.
Aug 22 17:37:04 datacore-PowerEdge-R740 sudo[3296382]: pam_unix(sudo:session): session closed for user root
Aug 22 17:37:04 datacore-PowerEdge-R740 cinder-volume[3295994]: DEBUG oslo_concurrency.processutils [None req-afcd071b-36c5-415f-9bfb-3fe85d1dc253 None None] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix stack-volumes-lvmdriver-1" returned: 0 in 0.645s {{(pid=3295994) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Aug 22 17:37:04 datacore-PowerEdge-R740 cinder-volume[3295994]: DEBUG oslo_concurrency.processutils [None req-afcd071b-36c5-415f-9bfb-3fe85d1dc253 None None] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1 {{(pid=3295994) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Aug 22 17:37:04 datacore-PowerEdge-R740 sudo[3296394]:    stack : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/local/bin/cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1
Aug 22 17:37:04 datacore-PowerEdge-R740 sudo[3296394]: pam_unix(sudo:session): session opened for user root by (uid=0)
Aug 22 17:37:05 datacore-PowerEdge-R740 sudo[3296394]: pam_unix(sudo:session): session closed for user root
Aug 22 17:37:05 datacore-PowerEdge-R740 cinder-volume[3295994]: DEBUG oslo_concurrency.processutils [None req-afcd071b-36c5-415f-9bfb-3fe85d1dc253 None None] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1" returned: 0 in 0.634s {{(pid=3295994) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Aug 22 17:37:05 datacore-PowerEdge-R740 cinder-volume[3295994]: DEBUG oslo_concurrency.processutils [None req-afcd071b-36c5-415f-9bfb-3fe85d1dc253 None None] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o size,data_percent --separator : --nosuffix /dev/stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool {{(pid=3295994) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Aug 22 17:37:05 datacore-PowerEdge-R740 sudo[3296403]:    stack : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/local/bin/cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o size,data_percent --separator : --nosuffix /dev/stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool
Aug 22 17:37:05 datacore-PowerEdge-R740 sudo[3296403]: pam_unix(sudo:session): session opened for user root by (uid=0)
Aug 22 17:37:05 datacore-PowerEdge-R740 sudo[3296403]: pam_unix(sudo:session): session closed for user root
Aug 22 17:37:05 datacore-PowerEdge-R740 cinder-volume[3295994]: DEBUG oslo_concurrency.processutils [None req-afcd071b-36c5-415f-9bfb-3fe85d1dc253 None None] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o size,data_percent --separator : --nosuffix /dev/stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool" returned: 0 in 0.683s {{(pid=3295994) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Aug 22 17:37:05 datacore-PowerEdge-R740 cinder-volume[3295994]: DEBUG oslo_concurrency.processutils [None req-afcd071b-36c5-415f-9bfb-3fe85d1dc253 None None] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1 {{(pid=3295994) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Aug 22 17:37:05 datacore-PowerEdge-R740 sudo[3296415]:    stack : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/local/bin/cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1
Aug 22 17:37:05 datacore-PowerEdge-R740 sudo[3296415]: pam_unix(sudo:session): session opened for user root by (uid=0)
Aug 22 17:37:06 datacore-PowerEdge-R740 sudo[3296415]: pam_unix(sudo:session): session closed for user root
Aug 22 17:37:06 datacore-PowerEdge-R740 cinder-volume[3295994]: DEBUG oslo_concurrency.processutils [None req-afcd071b-36c5-415f-9bfb-3fe85d1dc253 None None] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1" returned: 0 in 0.652s {{(pid=3295994) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Aug 22 17:37:06 datacore-PowerEdge-R740 cinder-volume[3295994]: DEBUG cinder.manager [None req-afcd071b-36c5-415f-9bfb-3fe85d1dc253 None None] Notifying Schedulers of capabilities ... {{(pid=3295994) _publish_service_capabilities /opt/stack/cinder/cinder/manager.py:202}}
Aug 22 17:37:06 datacore-PowerEdge-R740 cinder-volume[3295994]: INFO cinder.volume.manager [None req-afcd071b-36c5-415f-9bfb-3fe85d1dc253 None None] Driver initialization completed successfully.
Aug 22 17:37:06 datacore-PowerEdge-R740 cinder-volume[3295994]: INFO cinder.manager [None req-afcd071b-36c5-415f-9bfb-3fe85d1dc253 None None] Initiating service 2 cleanup
Aug 22 17:37:06 datacore-PowerEdge-R740 cinder-volume[3295994]: INFO cinder.manager [None req-afcd071b-36c5-415f-9bfb-3fe85d1dc253 None None] Service 2 cleanup completed.
Aug 22 17:37:06 datacore-PowerEdge-R740 cinder-volume[3295994]: DEBUG cinder.service [None req-afcd071b-36c5-415f-9bfb-3fe85d1dc253 None None] Creating RPC server for service cinder-volume {{(pid=3295994) start /opt/stack/cinder/cinder/service.py:238}}
Aug 22 17:37:06 datacore-PowerEdge-R740 cinder-volume[3295994]: DEBUG cinder.service [None req-afcd071b-36c5-415f-9bfb-3fe85d1dc253 None None] Pinning object versions for RPC server serializer to 1.39 {{(pid=3295994) start /opt/stack/cinder/cinder/service.py:244}}
Aug 22 17:37:06 datacore-PowerEdge-R740 cinder-volume[3295994]: INFO cinder.volume.manager [None req-afcd071b-36c5-415f-9bfb-3fe85d1dc253 None None] Initializing RPC dependent components of volume driver LVMVolumeDriver (3.0.0)
Aug 22 17:37:06 datacore-PowerEdge-R740 cinder-volume[3295994]: DEBUG cinder.volume.drivers.lvm [None req-afcd071b-36c5-415f-9bfb-3fe85d1dc253 None None] Updating volume stats {{(pid=3295994) _update_volume_stats /opt/stack/cinder/cinder/volume/drivers/lvm.py:213}}
Aug 22 17:37:06 datacore-PowerEdge-R740 cinder-volume[3295994]: DEBUG oslo_concurrency.processutils [None req-afcd071b-36c5-415f-9bfb-3fe85d1dc253 None None] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix stack-volumes-lvmdriver-1 {{(pid=3295994) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Aug 22 17:37:06 datacore-PowerEdge-R740 sudo[3296433]:    stack : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/local/bin/cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix stack-volumes-lvmdriver-1
Aug 22 17:37:06 datacore-PowerEdge-R740 sudo[3296433]: pam_unix(sudo:session): session opened for user root by (uid=0)
Aug 22 17:37:07 datacore-PowerEdge-R740 sudo[3296433]: pam_unix(sudo:session): session closed for user root
Aug 22 17:37:07 datacore-PowerEdge-R740 cinder-volume[3295994]: DEBUG oslo_concurrency.processutils [None req-afcd071b-36c5-415f-9bfb-3fe85d1dc253 None None] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix stack-volumes-lvmdriver-1" returned: 0 in 0.632s {{(pid=3295994) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Aug 22 17:37:07 datacore-PowerEdge-R740 cinder-volume[3295994]: DEBUG oslo_concurrency.processutils [None req-afcd071b-36c5-415f-9bfb-3fe85d1dc253 None None] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1 {{(pid=3295994) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Aug 22 17:37:07 datacore-PowerEdge-R740 sudo[3296459]:    stack : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/local/bin/cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1
Aug 22 17:37:07 datacore-PowerEdge-R740 sudo[3296459]: pam_unix(sudo:session): session opened for user root by (uid=0)
Aug 22 17:37:07 datacore-PowerEdge-R740 sudo[3296459]: pam_unix(sudo:session): session closed for user root
Aug 22 17:37:07 datacore-PowerEdge-R740 cinder-volume[3295994]: DEBUG oslo_concurrency.processutils [None req-afcd071b-36c5-415f-9bfb-3fe85d1dc253 None None] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1" returned: 0 in 0.632s {{(pid=3295994) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Aug 22 17:37:07 datacore-PowerEdge-R740 cinder-volume[3295994]: DEBUG oslo_concurrency.processutils [None req-afcd071b-36c5-415f-9bfb-3fe85d1dc253 None None] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o size,data_percent --separator : --nosuffix /dev/stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool {{(pid=3295994) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Aug 22 17:37:07 datacore-PowerEdge-R740 sudo[3296463]:    stack : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/local/bin/cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o size,data_percent --separator : --nosuffix /dev/stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool
Aug 22 17:37:07 datacore-PowerEdge-R740 sudo[3296463]: pam_unix(sudo:session): session opened for user root by (uid=0)
Aug 22 17:37:08 datacore-PowerEdge-R740 sudo[3296463]: pam_unix(sudo:session): session closed for user root
Aug 22 17:37:08 datacore-PowerEdge-R740 cinder-volume[3295994]: DEBUG oslo_concurrency.processutils [None req-afcd071b-36c5-415f-9bfb-3fe85d1dc253 None None] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o size,data_percent --separator : --nosuffix /dev/stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool" returned: 0 in 0.640s {{(pid=3295994) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Aug 22 17:37:08 datacore-PowerEdge-R740 cinder-volume[3295994]: DEBUG oslo_concurrency.processutils [None req-afcd071b-36c5-415f-9bfb-3fe85d1dc253 None None] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1 {{(pid=3295994) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Aug 22 17:37:08 datacore-PowerEdge-R740 sudo[3296472]:    stack : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/local/bin/cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1
Aug 22 17:37:08 datacore-PowerEdge-R740 sudo[3296472]: pam_unix(sudo:session): session opened for user root by (uid=0)
Aug 22 17:37:09 datacore-PowerEdge-R740 sudo[3296472]: pam_unix(sudo:session): session closed for user root
Aug 22 17:37:09 datacore-PowerEdge-R740 cinder-volume[3295994]: DEBUG oslo_concurrency.processutils [None req-afcd071b-36c5-415f-9bfb-3fe85d1dc253 None None] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1" returned: 0 in 0.678s {{(pid=3295994) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Aug 22 17:37:09 datacore-PowerEdge-R740 cinder-volume[3295994]: INFO cinder.volume.manager [None req-afcd071b-36c5-415f-9bfb-3fe85d1dc253 None None] Driver post RPC initialization completed successfully.
Aug 22 17:37:11 datacore-PowerEdge-R740 systemd[1]: Stopping Devstack devstack@c-vol.service...
Aug 22 17:37:11 datacore-PowerEdge-R740 cinder-volume[3295785]: INFO oslo_service.service [None req-1ceabe8b-8f5e-42f4-9bf6-8e5ee5557daa None None] Caught SIGTERM, stopping children
Aug 22 17:37:11 datacore-PowerEdge-R740 cinder-volume[3295785]: DEBUG oslo_concurrency.lockutils [None req-1ceabe8b-8f5e-42f4-9bf6-8e5ee5557daa None None] Acquiring lock "singleton_lock" {{(pid=3295785) lock /usr/local/lib/python3.8/dist-packages/oslo_concurrency/lockutils.py:293}}
Aug 22 17:37:11 datacore-PowerEdge-R740 cinder-volume[3295785]: DEBUG oslo_concurrency.lockutils [None req-1ceabe8b-8f5e-42f4-9bf6-8e5ee5557daa None None] Acquired lock "singleton_lock" {{(pid=3295785) lock /usr/local/lib/python3.8/dist-packages/oslo_concurrency/lockutils.py:296}}
Aug 22 17:37:11 datacore-PowerEdge-R740 cinder-volume[3295785]: DEBUG oslo_concurrency.lockutils [None req-1ceabe8b-8f5e-42f4-9bf6-8e5ee5557daa None None] Releasing lock "singleton_lock" {{(pid=3295785) lock /usr/local/lib/python3.8/dist-packages/oslo_concurrency/lockutils.py:314}}
Aug 22 17:37:11 datacore-PowerEdge-R740 cinder-volume[3295785]: DEBUG oslo_service.service [None req-1ceabe8b-8f5e-42f4-9bf6-8e5ee5557daa None None] Stop services. {{(pid=3295785) stop /usr/local/lib/python3.8/dist-packages/oslo_service/service.py:695}}
Aug 22 17:37:11 datacore-PowerEdge-R740 cinder-volume[3295785]: DEBUG oslo_service.service [None req-1ceabe8b-8f5e-42f4-9bf6-8e5ee5557daa None None] Killing children. {{(pid=3295785) stop /usr/local/lib/python3.8/dist-packages/oslo_service/service.py:700}}
Aug 22 17:37:11 datacore-PowerEdge-R740 cinder-volume[3295785]: INFO oslo_service.service [None req-1ceabe8b-8f5e-42f4-9bf6-8e5ee5557daa None None] Waiting on 1 children to exit
Aug 22 17:37:11 datacore-PowerEdge-R740 cinder-volume[3295994]: DEBUG oslo_concurrency.lockutils [None req-1ceabe8b-8f5e-42f4-9bf6-8e5ee5557daa None None] Acquiring lock "singleton_lock" {{(pid=3295994) lock /usr/local/lib/python3.8/dist-packages/oslo_concurrency/lockutils.py:293}}
Aug 22 17:37:11 datacore-PowerEdge-R740 cinder-volume[3295994]: DEBUG oslo_concurrency.lockutils [None req-1ceabe8b-8f5e-42f4-9bf6-8e5ee5557daa None None] Acquired lock "singleton_lock" {{(pid=3295994) lock /usr/local/lib/python3.8/dist-packages/oslo_concurrency/lockutils.py:296}}
Aug 22 17:37:11 datacore-PowerEdge-R740 cinder-volume[3295994]: DEBUG oslo_concurrency.lockutils [None req-1ceabe8b-8f5e-42f4-9bf6-8e5ee5557daa None None] Releasing lock "singleton_lock" {{(pid=3295994) lock /usr/local/lib/python3.8/dist-packages/oslo_concurrency/lockutils.py:314}}
Aug 22 17:37:11 datacore-PowerEdge-R740 cinder-volume[3295994]: WARNING amqp [None req-1ceabe8b-8f5e-42f4-9bf6-8e5ee5557daa None None] Received method (60, 30) during closing channel 1. This method will be ignored
Aug 22 17:37:11 datacore-PowerEdge-R740 cinder-volume[3295994]: WARNING amqp [None req-1ceabe8b-8f5e-42f4-9bf6-8e5ee5557daa None None] Received method (60, 30) during closing channel 1. This method will be ignored
Aug 22 17:37:11 datacore-PowerEdge-R740 cinder-volume[3295785]: INFO oslo_service.service [None req-1ceabe8b-8f5e-42f4-9bf6-8e5ee5557daa None None] Child 3295994 exited with status 0
Aug 22 17:37:11 datacore-PowerEdge-R740 cinder-volume[3295785]: /usr/lib/python3/dist-packages/secretstorage/dhcrypto.py:15: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
Aug 22 17:37:11 datacore-PowerEdge-R740 cinder-volume[3295785]:   from cryptography.utils import int_from_bytes
Aug 22 17:37:11 datacore-PowerEdge-R740 cinder-volume[3295785]: /usr/lib/python3/dist-packages/secretstorage/util.py:19: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
Aug 22 17:37:11 datacore-PowerEdge-R740 cinder-volume[3295785]:   from cryptography.utils import int_from_bytes
Aug 22 17:37:11 datacore-PowerEdge-R740 cinder-volume[3295785]: /opt/stack/cinder/cinder/db/sqlalchemy/models.py:152: SAWarning: implicitly coercing SELECT object to scalar subquery; please use the .scalar_subquery() method to produce a scalar subquery.
Aug 22 17:37:11 datacore-PowerEdge-R740 cinder-volume[3295785]:   last_heartbeat = column_property(
Aug 22 17:37:11 datacore-PowerEdge-R740 cinder-volume[3295785]: /opt/stack/cinder/cinder/db/sqlalchemy/models.py:160: SAWarning: implicitly coercing SELECT object to scalar subquery; please use the .scalar_subquery() method to produce a scalar subquery.
Aug 22 17:37:11 datacore-PowerEdge-R740 cinder-volume[3295785]:   num_hosts = column_property(
Aug 22 17:37:11 datacore-PowerEdge-R740 cinder-volume[3295785]: /opt/stack/cinder/cinder/db/sqlalchemy/models.py:169: SAWarning: implicitly coercing SELECT object to scalar subquery; please use the .scalar_subquery() method to produce a scalar subquery.
Aug 22 17:37:11 datacore-PowerEdge-R740 cinder-volume[3295785]:   num_down_hosts = column_property(
Aug 22 17:37:11 datacore-PowerEdge-R740 systemd[1]: devstack@c-vol.service: Succeeded.
Aug 22 17:37:11 datacore-PowerEdge-R740 systemd[1]: Stopped Devstack devstack@c-vol.service.
Aug 22 17:37:11 datacore-PowerEdge-R740 systemd[1]: Started Devstack devstack@c-vol.service.
Aug 22 17:37:13 datacore-PowerEdge-R740 cinder-volume[3296546]: DEBUG oslo_concurrency.lockutils [-] Acquiring lock "singleton_lock" {{(pid=3296546) lock /usr/local/lib/python3.8/dist-packages/oslo_concurrency/lockutils.py:293}}
Aug 22 17:37:13 datacore-PowerEdge-R740 cinder-volume[3296546]: DEBUG oslo_concurrency.lockutils [-] Acquired lock "singleton_lock" {{(pid=3296546) lock /usr/local/lib/python3.8/dist-packages/oslo_concurrency/lockutils.py:296}}
Aug 22 17:37:13 datacore-PowerEdge-R740 cinder-volume[3296546]: DEBUG oslo_concurrency.lockutils [-] Releasing lock "singleton_lock" {{(pid=3296546) lock /usr/local/lib/python3.8/dist-packages/oslo_concurrency/lockutils.py:314}}
Aug 22 17:37:14 datacore-PowerEdge-R740 cinder-volume[3296546]: INFO dbcounter [None req-b27a5576-2588-4456-bd4c-8474ca06376e None None] Registered counter for database cinder
Aug 22 17:37:14 datacore-PowerEdge-R740 cinder-volume[3296546]: DEBUG oslo_db.sqlalchemy.engines [None req-b27a5576-2588-4456-bd4c-8474ca06376e None None] MySQL server mode set to STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_ENGINE_SUBSTITUTION {{(pid=3296546) _check_effective_sql_mode /usr/local/lib/python3.8/dist-packages/oslo_db/sqlalchemy/engines.py:314}}
Aug 22 17:37:14 datacore-PowerEdge-R740 cinder-volume[3296546]: DEBUG dbcounter [-] [3296546] Writer thread running {{(pid=3296546) stat_writer /usr/local/lib/python3.8/dist-packages/dbcounter.py:99}}
Aug 22 17:37:14 datacore-PowerEdge-R740 cinder-volume[3296546]: INFO cinder.rpc [None req-b27a5576-2588-4456-bd4c-8474ca06376e None None] Automatically selected cinder-scheduler objects version 1.39 as minimum service version.
Aug 22 17:37:14 datacore-PowerEdge-R740 cinder-volume[3296546]: INFO cinder.rpc [None req-b27a5576-2588-4456-bd4c-8474ca06376e None None] Automatically selected cinder-scheduler RPC version 3.12 as minimum service version.
Aug 22 17:37:14 datacore-PowerEdge-R740 cinder-volume[3296546]: DEBUG oslo_db.sqlalchemy.engines [None req-b27a5576-2588-4456-bd4c-8474ca06376e None None] MySQL server mode set to STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_ENGINE_SUBSTITUTION {{(pid=3296546) _check_effective_sql_mode /usr/local/lib/python3.8/dist-packages/oslo_db/sqlalchemy/engines.py:314}}
Aug 22 17:37:14 datacore-PowerEdge-R740 cinder-volume[3296546]: INFO cinder.volume.manager [None req-b27a5576-2588-4456-bd4c-8474ca06376e None None] Determined volume DB was empty at startup.
Aug 22 17:37:14 datacore-PowerEdge-R740 cinder-volume[3296546]: DEBUG cinder.volume.manager [None req-b27a5576-2588-4456-bd4c-8474ca06376e None None] Cinder Volume DB check: vol_db_empty=True {{(pid=3296546) __init__ /opt/stack/cinder/cinder/volume/manager.py:290}}
Aug 22 17:37:14 datacore-PowerEdge-R740 cinder-volume[3296546]: INFO cinder.volume.manager [None req-b27a5576-2588-4456-bd4c-8474ca06376e None None] Service not found for updating active_backend_id, assuming default for driver init.
Aug 22 17:37:14 datacore-PowerEdge-R740 cinder-volume[3296546]: WARNING stevedore.named [None req-b27a5576-2588-4456-bd4c-8474ca06376e None None] Could not load cinder.keymgr.conf_key_mgr.ConfKeyManager
Aug 22 17:37:14 datacore-PowerEdge-R740 cinder-volume[3296546]: WARNING castellan.key_manager [None req-b27a5576-2588-4456-bd4c-8474ca06376e None None] Deprecation Warning : cinder.keymgr.conf_key_mgr.ConfKeyManager is not a stevedore based driver, trying to load it as a class: stevedore.exception.NoMatches: No 'castellan.drivers' driver found, looking for 'cinder.keymgr.conf_key_mgr.ConfKeyManager'
Aug 22 17:37:14 datacore-PowerEdge-R740 cinder-volume[3296546]: WARNING cinder.keymgr.conf_key_mgr [None req-b27a5576-2588-4456-bd4c-8474ca06376e None None] This key manager is insecure and is not recommended for production deployments: stevedore.exception.NoMatches: No 'castellan.drivers' driver found, looking for 'cinder.keymgr.conf_key_mgr.ConfKeyManager'
Aug 22 17:37:14 datacore-PowerEdge-R740 cinder-volume[3296546]: ERROR cinder.cmd.volume [None req-b27a5576-2588-4456-bd4c-8474ca06376e None None] Volume service hostgroup@datacore_iscsi1 failed to start.: ModuleNotFoundError: No module named 'cinder.volume.drivers.datacore.iscsi'
Aug 22 17:37:14 datacore-PowerEdge-R740 cinder-volume[3296546]: ERROR cinder.cmd.volume Traceback (most recent call last):
Aug 22 17:37:14 datacore-PowerEdge-R740 cinder-volume[3296546]: ERROR cinder.cmd.volume   File "/opt/stack/cinder/cinder/cmd/volume.py", line 99, in _launch_service
Aug 22 17:37:14 datacore-PowerEdge-R740 cinder-volume[3296546]: ERROR cinder.cmd.volume     server = service.Service.create(host=host,
Aug 22 17:37:14 datacore-PowerEdge-R740 cinder-volume[3296546]: ERROR cinder.cmd.volume   File "/opt/stack/cinder/cinder/service.py", line 417, in create
Aug 22 17:37:14 datacore-PowerEdge-R740 cinder-volume[3296546]: ERROR cinder.cmd.volume     service_obj = cls(host, binary, topic, manager,
Aug 22 17:37:14 datacore-PowerEdge-R740 cinder-volume[3296546]: ERROR cinder.cmd.volume   File "/opt/stack/cinder/cinder/service.py", line 158, in __init__
Aug 22 17:37:14 datacore-PowerEdge-R740 cinder-volume[3296546]: ERROR cinder.cmd.volume     self.manager = manager_class(host=self.host,
Aug 22 17:37:14 datacore-PowerEdge-R740 cinder-volume[3296546]: ERROR cinder.cmd.volume   File "/opt/stack/cinder/cinder/volume/manager.py", line 313, in __init__
Aug 22 17:37:14 datacore-PowerEdge-R740 cinder-volume[3296546]: ERROR cinder.cmd.volume     self.driver = importutils.import_object(
Aug 22 17:37:14 datacore-PowerEdge-R740 cinder-volume[3296546]: ERROR cinder.cmd.volume   File "/usr/local/lib/python3.8/dist-packages/oslo_utils/importutils.py", line 44, in import_object
Aug 22 17:37:14 datacore-PowerEdge-R740 cinder-volume[3296546]: ERROR cinder.cmd.volume     return import_class(import_str)(*args, **kwargs)
Aug 22 17:37:14 datacore-PowerEdge-R740 cinder-volume[3296546]: ERROR cinder.cmd.volume   File "/usr/local/lib/python3.8/dist-packages/oslo_utils/importutils.py", line 30, in import_class
Aug 22 17:37:14 datacore-PowerEdge-R740 cinder-volume[3296546]: ERROR cinder.cmd.volume     __import__(mod_str)
Aug 22 17:37:14 datacore-PowerEdge-R740 cinder-volume[3296546]: ERROR cinder.cmd.volume ModuleNotFoundError: No module named 'cinder.volume.drivers.datacore.iscsi'
Aug 22 17:37:14 datacore-PowerEdge-R740 cinder-volume[3296546]: ERROR cinder.cmd.volume 
Aug 22 17:37:14 datacore-PowerEdge-R740 cinder-volume[3296546]: ERROR cinder.cmd.volume [None req-b27a5576-2588-4456-bd4c-8474ca06376e None None] No volume service(s) started successfully, terminating.
Aug 22 17:37:14 datacore-PowerEdge-R740 cinder-volume[3296546]: /usr/lib/python3/dist-packages/secretstorage/dhcrypto.py:15: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
Aug 22 17:37:14 datacore-PowerEdge-R740 cinder-volume[3296546]:   from cryptography.utils import int_from_bytes
Aug 22 17:37:14 datacore-PowerEdge-R740 cinder-volume[3296546]: /usr/lib/python3/dist-packages/secretstorage/util.py:19: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
Aug 22 17:37:14 datacore-PowerEdge-R740 cinder-volume[3296546]:   from cryptography.utils import int_from_bytes
Aug 22 17:37:14 datacore-PowerEdge-R740 cinder-volume[3296546]: /opt/stack/cinder/cinder/db/sqlalchemy/models.py:152: SAWarning: implicitly coercing SELECT object to scalar subquery; please use the .scalar_subquery() method to produce a scalar subquery.
Aug 22 17:37:14 datacore-PowerEdge-R740 cinder-volume[3296546]:   last_heartbeat = column_property(
Aug 22 17:37:14 datacore-PowerEdge-R740 cinder-volume[3296546]: /opt/stack/cinder/cinder/db/sqlalchemy/models.py:160: SAWarning: implicitly coercing SELECT object to scalar subquery; please use the .scalar_subquery() method to produce a scalar subquery.
Aug 22 17:37:14 datacore-PowerEdge-R740 cinder-volume[3296546]:   num_hosts = column_property(
Aug 22 17:37:14 datacore-PowerEdge-R740 cinder-volume[3296546]: /opt/stack/cinder/cinder/db/sqlalchemy/models.py:169: SAWarning: implicitly coercing SELECT object to scalar subquery; please use the .scalar_subquery() method to produce a scalar subquery.
Aug 22 17:37:14 datacore-PowerEdge-R740 cinder-volume[3296546]:   num_down_hosts = column_property(
Aug 22 17:37:14 datacore-PowerEdge-R740 systemd[1]: devstack@c-vol.service: Main process exited, code=exited, status=1/FAILURE
Aug 22 17:37:14 datacore-PowerEdge-R740 systemd[1]: devstack@c-vol.service: Failed with result 'exit-code'.
