-- Logs begin at Thu 2022-09-15 16:00:50 IST, end at Thu 2022-09-15 16:01:00 IST. --
Sep 15 16:00:50 datacore-PowerEdge-R740 sudo[3014432]: pam_unix(sudo:session): session closed for user root
Sep 15 16:00:50 datacore-PowerEdge-R740 cinder-volume[3014228]: DEBUG oslo_concurrency.processutils [None req-39ac9f61-1f0b-469f-9896-78085d8bbeb6 None None] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C pvs --noheadings --unit=g -o vg_name,name,size,free --separator | --nosuffix --ignoreskippedcluster" returned: 0 in 0.682s {{(pid=3014228) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Sep 15 16:00:50 datacore-PowerEdge-R740 cinder-volume[3014228]: DEBUG oslo_concurrency.processutils [None req-39ac9f61-1f0b-469f-9896-78085d8bbeb6 None None] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix stack-volumes-lvmdriver-1 {{(pid=3014228) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Sep 15 16:00:50 datacore-PowerEdge-R740 sudo[3014493]:    stack : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/local/bin/cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix stack-volumes-lvmdriver-1
Sep 15 16:00:50 datacore-PowerEdge-R740 sudo[3014493]: pam_unix(sudo:session): session opened for user root by (uid=0)
Sep 15 16:00:51 datacore-PowerEdge-R740 sudo[3014493]: pam_unix(sudo:session): session closed for user root
Sep 15 16:00:51 datacore-PowerEdge-R740 cinder-volume[3014228]: DEBUG oslo_concurrency.processutils [None req-39ac9f61-1f0b-469f-9896-78085d8bbeb6 None None] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix stack-volumes-lvmdriver-1" returned: 0 in 0.657s {{(pid=3014228) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Sep 15 16:00:51 datacore-PowerEdge-R740 cinder-volume[3014228]: DEBUG oslo_concurrency.processutils [None req-39ac9f61-1f0b-469f-9896-78085d8bbeb6 None None] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix stack-volumes-lvmdriver-1 {{(pid=3014228) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Sep 15 16:00:51 datacore-PowerEdge-R740 sudo[3014497]:    stack : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/local/bin/cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix stack-volumes-lvmdriver-1
Sep 15 16:00:51 datacore-PowerEdge-R740 sudo[3014497]: pam_unix(sudo:session): session opened for user root by (uid=0)
Sep 15 16:00:51 datacore-PowerEdge-R740 sudo[3014497]: pam_unix(sudo:session): session closed for user root
Sep 15 16:00:51 datacore-PowerEdge-R740 cinder-volume[3014228]: DEBUG oslo_concurrency.processutils [None req-39ac9f61-1f0b-469f-9896-78085d8bbeb6 None None] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix stack-volumes-lvmdriver-1" returned: 0 in 0.655s {{(pid=3014228) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Sep 15 16:00:51 datacore-PowerEdge-R740 cinder-volume[3014228]: DEBUG oslo_concurrency.processutils [None req-39ac9f61-1f0b-469f-9896-78085d8bbeb6 None None] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1 {{(pid=3014228) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Sep 15 16:00:51 datacore-PowerEdge-R740 sudo[3014520]:    stack : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/local/bin/cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1
Sep 15 16:00:51 datacore-PowerEdge-R740 sudo[3014520]: pam_unix(sudo:session): session opened for user root by (uid=0)
Sep 15 16:00:52 datacore-PowerEdge-R740 sudo[3014520]: pam_unix(sudo:session): session closed for user root
Sep 15 16:00:52 datacore-PowerEdge-R740 cinder-volume[3014228]: DEBUG oslo_concurrency.processutils [None req-39ac9f61-1f0b-469f-9896-78085d8bbeb6 None None] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1" returned: 0 in 0.629s {{(pid=3014228) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Sep 15 16:00:52 datacore-PowerEdge-R740 cinder-volume[3014228]: DEBUG oslo_concurrency.processutils [None req-39ac9f61-1f0b-469f-9896-78085d8bbeb6 None None] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o size,data_percent --separator : --nosuffix /dev/stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool {{(pid=3014228) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Sep 15 16:00:52 datacore-PowerEdge-R740 sudo[3014535]:    stack : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/local/bin/cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o size,data_percent --separator : --nosuffix /dev/stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool
Sep 15 16:00:52 datacore-PowerEdge-R740 sudo[3014535]: pam_unix(sudo:session): session opened for user root by (uid=0)
Sep 15 16:00:53 datacore-PowerEdge-R740 sudo[3014535]: pam_unix(sudo:session): session closed for user root
Sep 15 16:00:53 datacore-PowerEdge-R740 cinder-volume[3014228]: DEBUG oslo_concurrency.processutils [None req-39ac9f61-1f0b-469f-9896-78085d8bbeb6 None None] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o size,data_percent --separator : --nosuffix /dev/stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool" returned: 0 in 0.651s {{(pid=3014228) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Sep 15 16:00:53 datacore-PowerEdge-R740 cinder-volume[3014228]: DEBUG oslo_concurrency.processutils [None req-39ac9f61-1f0b-469f-9896-78085d8bbeb6 None None] Running cmd (subprocess): env LC_ALL=C lvm version {{(pid=3014228) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Sep 15 16:00:53 datacore-PowerEdge-R740 cinder-volume[3014228]: DEBUG oslo_concurrency.processutils [None req-39ac9f61-1f0b-469f-9896-78085d8bbeb6 None None] CMD "env LC_ALL=C lvm version" returned: 0 in 0.017s {{(pid=3014228) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Sep 15 16:00:53 datacore-PowerEdge-R740 cinder-volume[3014228]: DEBUG oslo_concurrency.processutils [None req-39ac9f61-1f0b-469f-9896-78085d8bbeb6 None None] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool {{(pid=3014228) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Sep 15 16:00:53 datacore-PowerEdge-R740 sudo[3014542]:    stack : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/local/bin/cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool
Sep 15 16:00:53 datacore-PowerEdge-R740 sudo[3014542]: pam_unix(sudo:session): session opened for user root by (uid=0)
Sep 15 16:00:53 datacore-PowerEdge-R740 sudo[3014542]: pam_unix(sudo:session): session closed for user root
Sep 15 16:00:53 datacore-PowerEdge-R740 cinder-volume[3014228]: DEBUG oslo_concurrency.processutils [None req-39ac9f61-1f0b-469f-9896-78085d8bbeb6 None None] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool" returned: 0 in 0.634s {{(pid=3014228) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Sep 15 16:00:53 datacore-PowerEdge-R740 cinder-volume[3014228]: INFO cinder.volume.drivers.lvm [None req-39ac9f61-1f0b-469f-9896-78085d8bbeb6 None None] Enabling LVM thin provisioning by default because a thin pool exists.
Sep 15 16:00:53 datacore-PowerEdge-R740 cinder-volume[3014228]: DEBUG oslo_concurrency.processutils [None req-39ac9f61-1f0b-469f-9896-78085d8bbeb6 None None] Running cmd (subprocess): env LC_ALL=C lvm version {{(pid=3014228) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Sep 15 16:00:53 datacore-PowerEdge-R740 cinder-volume[3014228]: DEBUG oslo_concurrency.processutils [None req-39ac9f61-1f0b-469f-9896-78085d8bbeb6 None None] CMD "env LC_ALL=C lvm version" returned: 0 in 0.019s {{(pid=3014228) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Sep 15 16:00:53 datacore-PowerEdge-R740 cinder-volume[3014228]: DEBUG oslo_concurrency.processutils [None req-39ac9f61-1f0b-469f-9896-78085d8bbeb6 None None] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool {{(pid=3014228) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Sep 15 16:00:53 datacore-PowerEdge-R740 sudo[3014551]:    stack : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/local/bin/cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool
Sep 15 16:00:53 datacore-PowerEdge-R740 sudo[3014551]: pam_unix(sudo:session): session opened for user root by (uid=0)
Sep 15 16:00:54 datacore-PowerEdge-R740 sudo[3014551]: pam_unix(sudo:session): session closed for user root
Sep 15 16:00:54 datacore-PowerEdge-R740 cinder-volume[3014228]: DEBUG oslo_concurrency.processutils [None req-39ac9f61-1f0b-469f-9896-78085d8bbeb6 None None] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool" returned: 0 in 0.614s {{(pid=3014228) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Sep 15 16:00:54 datacore-PowerEdge-R740 cinder-volume[3014228]: DEBUG cinder.volume.drivers.lvm [None req-39ac9f61-1f0b-469f-9896-78085d8bbeb6 None None] Updating volume stats {{(pid=3014228) _update_volume_stats /opt/stack/cinder/cinder/volume/drivers/lvm.py:213}}
Sep 15 16:00:54 datacore-PowerEdge-R740 cinder-volume[3014228]: DEBUG oslo_concurrency.processutils [None req-39ac9f61-1f0b-469f-9896-78085d8bbeb6 None None] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix stack-volumes-lvmdriver-1 {{(pid=3014228) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Sep 15 16:00:54 datacore-PowerEdge-R740 sudo[3014555]:    stack : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/local/bin/cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix stack-volumes-lvmdriver-1
Sep 15 16:00:54 datacore-PowerEdge-R740 sudo[3014555]: pam_unix(sudo:session): session opened for user root by (uid=0)
Sep 15 16:00:55 datacore-PowerEdge-R740 sudo[3014555]: pam_unix(sudo:session): session closed for user root
Sep 15 16:00:55 datacore-PowerEdge-R740 cinder-volume[3014228]: DEBUG oslo_concurrency.processutils [None req-39ac9f61-1f0b-469f-9896-78085d8bbeb6 None None] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix stack-volumes-lvmdriver-1" returned: 0 in 0.674s {{(pid=3014228) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Sep 15 16:00:55 datacore-PowerEdge-R740 cinder-volume[3014228]: DEBUG oslo_concurrency.processutils [None req-39ac9f61-1f0b-469f-9896-78085d8bbeb6 None None] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1 {{(pid=3014228) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Sep 15 16:00:55 datacore-PowerEdge-R740 sudo[3014570]:    stack : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/local/bin/cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1
Sep 15 16:00:55 datacore-PowerEdge-R740 sudo[3014570]: pam_unix(sudo:session): session opened for user root by (uid=0)
Sep 15 16:00:55 datacore-PowerEdge-R740 sudo[3014570]: pam_unix(sudo:session): session closed for user root
Sep 15 16:00:55 datacore-PowerEdge-R740 cinder-volume[3014228]: DEBUG oslo_concurrency.processutils [None req-39ac9f61-1f0b-469f-9896-78085d8bbeb6 None None] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1" returned: 0 in 0.666s {{(pid=3014228) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Sep 15 16:00:55 datacore-PowerEdge-R740 cinder-volume[3014228]: DEBUG oslo_concurrency.processutils [None req-39ac9f61-1f0b-469f-9896-78085d8bbeb6 None None] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o size,data_percent --separator : --nosuffix /dev/stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool {{(pid=3014228) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Sep 15 16:00:55 datacore-PowerEdge-R740 sudo[3014574]:    stack : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/local/bin/cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o size,data_percent --separator : --nosuffix /dev/stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool
Sep 15 16:00:55 datacore-PowerEdge-R740 sudo[3014574]: pam_unix(sudo:session): session opened for user root by (uid=0)
Sep 15 16:00:56 datacore-PowerEdge-R740 sudo[3014574]: pam_unix(sudo:session): session closed for user root
Sep 15 16:00:56 datacore-PowerEdge-R740 cinder-volume[3014012]: DEBUG dbcounter [-] [3014012] Writing DB stats cinder:SELECT=16,cinder:UPDATE=1 {{(pid=3014012) stat_writer /usr/local/lib/python3.8/dist-packages/dbcounter.py:114}}
Sep 15 16:00:56 datacore-PowerEdge-R740 cinder-volume[3014228]: DEBUG oslo_concurrency.processutils [None req-39ac9f61-1f0b-469f-9896-78085d8bbeb6 None None] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o size,data_percent --separator : --nosuffix /dev/stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool" returned: 0 in 0.665s {{(pid=3014228) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Sep 15 16:00:56 datacore-PowerEdge-R740 cinder-volume[3014228]: DEBUG oslo_concurrency.processutils [None req-39ac9f61-1f0b-469f-9896-78085d8bbeb6 None None] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1 {{(pid=3014228) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Sep 15 16:00:56 datacore-PowerEdge-R740 sudo[3014586]:    stack : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/local/bin/cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1
Sep 15 16:00:56 datacore-PowerEdge-R740 sudo[3014586]: pam_unix(sudo:session): session opened for user root by (uid=0)
Sep 15 16:00:57 datacore-PowerEdge-R740 sudo[3014586]: pam_unix(sudo:session): session closed for user root
Sep 15 16:00:57 datacore-PowerEdge-R740 cinder-volume[3014228]: DEBUG oslo_concurrency.processutils [None req-39ac9f61-1f0b-469f-9896-78085d8bbeb6 None None] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1" returned: 0 in 0.661s {{(pid=3014228) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Sep 15 16:00:57 datacore-PowerEdge-R740 cinder-volume[3014228]: INFO cinder.volume.driver [None req-39ac9f61-1f0b-469f-9896-78085d8bbeb6 None None] Driver hasn't implemented _init_vendor_properties()
Sep 15 16:00:57 datacore-PowerEdge-R740 cinder-volume[3014228]: DEBUG cinder.volume.driver [None req-39ac9f61-1f0b-469f-9896-78085d8bbeb6 None None] Initialized capabilities list: {'volume_backend_name': 'lvmdriver-1', 'vendor_name': 'Open Source', 'driver_version': '3.0.0', 'storage_protocol': 'iSCSI', 'pools': [{'pool_name': 'lvmdriver-1', 'total_capacity_gb': 28.5, 'free_capacity_gb': 28.5, 'reserved_percentage': 0, 'location_info': 'LVMVolumeDriver:datacore-PowerEdge-R740:stack-volumes-lvmdriver-1:thin:0', 'QoS_support': False, 'provisioned_capacity_gb': 0.0, 'max_over_subscription_ratio': '20.0', 'thin_provisioning_support': True, 'thick_provisioning_support': False, 'total_volumes': 1, 'filter_function': None, 'goodness_function': None, 'multiattach': True, 'backend_state': 'up'}], 'shared_targets': False, 'sparse_copy_volume': True, 'properties': {'thin_provisioning': {'title': 'Thin Provisioning', 'description': 'Sets thin provisioning.', 'type': 'boolean'}, 'compression': {'title': 'Compression', 'description': 'Enables compression.', 'type': 'boolean'}, 'qos': {'title': 'QoS', 'description': 'Enables QoS.', 'type': 'boolean'}, 'replication_enabled': {'title': 'Replication', 'description': 'Enables replication.', 'type': 'boolean'}}}. {{(pid=3014228) init_capabilities /opt/stack/cinder/cinder/volume/driver.py:820}}
Sep 15 16:00:57 datacore-PowerEdge-R740 cinder-volume[3014228]: DEBUG oslo_db.sqlalchemy.engines [None req-39ac9f61-1f0b-469f-9896-78085d8bbeb6 None None] MySQL server mode set to STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_ENGINE_SUBSTITUTION {{(pid=3014228) _check_effective_sql_mode /usr/local/lib/python3.8/dist-packages/oslo_db/sqlalchemy/engines.py:314}}
Sep 15 16:00:57 datacore-PowerEdge-R740 cinder-volume[3014228]: DEBUG dbcounter [-] [3014228] Writer thread running {{(pid=3014228) stat_writer /usr/local/lib/python3.8/dist-packages/dbcounter.py:99}}
Sep 15 16:00:57 datacore-PowerEdge-R740 cinder-volume[3014228]: DEBUG cinder.db.sqlalchemy.api [None req-39ac9f61-1f0b-469f-9896-78085d8bbeb6 None None] Building query based on filter {{(pid=3014228) _process_snaps_filters /opt/stack/cinder/cinder/db/sqlalchemy/api.py:3156}}
Sep 15 16:00:57 datacore-PowerEdge-R740 cinder-volume[3014228]: DEBUG cinder.image.image_utils [None req-39ac9f61-1f0b-469f-9896-78085d8bbeb6 None None] Configuration image_conversion_dir is None or the path doesn't exist. {{(pid=3014228) cleanup_temporary_file /opt/stack/cinder/cinder/image/image_utils.py:955}}
Sep 15 16:00:57 datacore-PowerEdge-R740 cinder-volume[3014228]: DEBUG cinder.volume.drivers.lvm [None req-39ac9f61-1f0b-469f-9896-78085d8bbeb6 None None] Updating volume stats {{(pid=3014228) _update_volume_stats /opt/stack/cinder/cinder/volume/drivers/lvm.py:213}}
Sep 15 16:00:57 datacore-PowerEdge-R740 cinder-volume[3014228]: DEBUG oslo_concurrency.processutils [None req-39ac9f61-1f0b-469f-9896-78085d8bbeb6 None None] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix stack-volumes-lvmdriver-1 {{(pid=3014228) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Sep 15 16:00:57 datacore-PowerEdge-R740 sudo[3014597]:    stack : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/local/bin/cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix stack-volumes-lvmdriver-1
Sep 15 16:00:57 datacore-PowerEdge-R740 sudo[3014597]: pam_unix(sudo:session): session opened for user root by (uid=0)
Sep 15 16:00:57 datacore-PowerEdge-R740 cinder-volume[3014228]: INFO cinder.keymgr.migration [None req-bbaf2cd6-548a-45c1-a679-e60aaf6d26e7 None None] Not migrating encryption keys because the ConfKeyManager is still in use.
Sep 15 16:00:57 datacore-PowerEdge-R740 sudo[3014597]: pam_unix(sudo:session): session closed for user root
Sep 15 16:00:57 datacore-PowerEdge-R740 cinder-volume[3014228]: DEBUG oslo_concurrency.processutils [None req-39ac9f61-1f0b-469f-9896-78085d8bbeb6 None None] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix stack-volumes-lvmdriver-1" returned: 0 in 0.655s {{(pid=3014228) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Sep 15 16:00:57 datacore-PowerEdge-R740 cinder-volume[3014228]: DEBUG oslo_concurrency.processutils [None req-39ac9f61-1f0b-469f-9896-78085d8bbeb6 None None] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1 {{(pid=3014228) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Sep 15 16:00:57 datacore-PowerEdge-R740 sudo[3014604]:    stack : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/local/bin/cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1
Sep 15 16:00:57 datacore-PowerEdge-R740 sudo[3014604]: pam_unix(sudo:session): session opened for user root by (uid=0)
Sep 15 16:00:58 datacore-PowerEdge-R740 sudo[3014604]: pam_unix(sudo:session): session closed for user root
Sep 15 16:00:58 datacore-PowerEdge-R740 cinder-volume[3014228]: DEBUG oslo_concurrency.processutils [None req-39ac9f61-1f0b-469f-9896-78085d8bbeb6 None None] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1" returned: 0 in 0.633s {{(pid=3014228) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Sep 15 16:00:58 datacore-PowerEdge-R740 cinder-volume[3014228]: DEBUG oslo_concurrency.processutils [None req-39ac9f61-1f0b-469f-9896-78085d8bbeb6 None None] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o size,data_percent --separator : --nosuffix /dev/stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool {{(pid=3014228) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Sep 15 16:00:58 datacore-PowerEdge-R740 sudo[3014611]:    stack : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/local/bin/cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o size,data_percent --separator : --nosuffix /dev/stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool
Sep 15 16:00:58 datacore-PowerEdge-R740 sudo[3014611]: pam_unix(sudo:session): session opened for user root by (uid=0)
Sep 15 16:00:59 datacore-PowerEdge-R740 sudo[3014611]: pam_unix(sudo:session): session closed for user root
Sep 15 16:00:59 datacore-PowerEdge-R740 cinder-volume[3014228]: DEBUG oslo_concurrency.processutils [None req-39ac9f61-1f0b-469f-9896-78085d8bbeb6 None None] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o size,data_percent --separator : --nosuffix /dev/stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool" returned: 0 in 0.661s {{(pid=3014228) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Sep 15 16:00:59 datacore-PowerEdge-R740 cinder-volume[3014228]: DEBUG oslo_concurrency.processutils [None req-39ac9f61-1f0b-469f-9896-78085d8bbeb6 None None] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1 {{(pid=3014228) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Sep 15 16:00:59 datacore-PowerEdge-R740 sudo[3014628]:    stack : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/local/bin/cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1
Sep 15 16:00:59 datacore-PowerEdge-R740 sudo[3014628]: pam_unix(sudo:session): session opened for user root by (uid=0)
Sep 15 16:00:59 datacore-PowerEdge-R740 sudo[3014628]: pam_unix(sudo:session): session closed for user root
Sep 15 16:00:59 datacore-PowerEdge-R740 cinder-volume[3014228]: DEBUG oslo_concurrency.processutils [None req-39ac9f61-1f0b-469f-9896-78085d8bbeb6 None None] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1" returned: 0 in 0.643s {{(pid=3014228) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Sep 15 16:00:59 datacore-PowerEdge-R740 cinder-volume[3014228]: DEBUG cinder.manager [None req-39ac9f61-1f0b-469f-9896-78085d8bbeb6 None None] Notifying Schedulers of capabilities ... {{(pid=3014228) _publish_service_capabilities /opt/stack/cinder/cinder/manager.py:202}}
Sep 15 16:00:59 datacore-PowerEdge-R740 cinder-volume[3014228]: INFO cinder.volume.manager [None req-39ac9f61-1f0b-469f-9896-78085d8bbeb6 None None] Driver initialization completed successfully.
Sep 15 16:00:59 datacore-PowerEdge-R740 cinder-volume[3014228]: INFO cinder.manager [None req-39ac9f61-1f0b-469f-9896-78085d8bbeb6 None None] Initiating service 2 cleanup
Sep 15 16:00:59 datacore-PowerEdge-R740 cinder-volume[3014228]: INFO cinder.manager [None req-39ac9f61-1f0b-469f-9896-78085d8bbeb6 None None] Service 2 cleanup completed.
Sep 15 16:00:59 datacore-PowerEdge-R740 cinder-volume[3014228]: DEBUG cinder.service [None req-39ac9f61-1f0b-469f-9896-78085d8bbeb6 None None] Creating RPC server for service cinder-volume {{(pid=3014228) start /opt/stack/cinder/cinder/service.py:231}}
Sep 15 16:00:59 datacore-PowerEdge-R740 cinder-volume[3014228]: DEBUG cinder.service [None req-39ac9f61-1f0b-469f-9896-78085d8bbeb6 None None] Pinning object versions for RPC server serializer to 1.39 {{(pid=3014228) start /opt/stack/cinder/cinder/service.py:237}}
Sep 15 16:00:59 datacore-PowerEdge-R740 cinder-volume[3014228]: INFO cinder.volume.manager [None req-39ac9f61-1f0b-469f-9896-78085d8bbeb6 None None] Initializing RPC dependent components of volume driver LVMVolumeDriver (3.0.0)
Sep 15 16:00:59 datacore-PowerEdge-R740 cinder-volume[3014228]: DEBUG cinder.volume.drivers.lvm [None req-39ac9f61-1f0b-469f-9896-78085d8bbeb6 None None] Updating volume stats {{(pid=3014228) _update_volume_stats /opt/stack/cinder/cinder/volume/drivers/lvm.py:213}}
Sep 15 16:00:59 datacore-PowerEdge-R740 cinder-volume[3014228]: DEBUG oslo_concurrency.processutils [None req-39ac9f61-1f0b-469f-9896-78085d8bbeb6 None None] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix stack-volumes-lvmdriver-1 {{(pid=3014228) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Sep 15 16:00:59 datacore-PowerEdge-R740 sudo[3014651]:    stack : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/local/bin/cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix stack-volumes-lvmdriver-1
Sep 15 16:00:59 datacore-PowerEdge-R740 sudo[3014651]: pam_unix(sudo:session): session opened for user root by (uid=0)
Sep 15 16:01:00 datacore-PowerEdge-R740 sudo[3014651]: pam_unix(sudo:session): session closed for user root
Sep 15 16:01:00 datacore-PowerEdge-R740 cinder-volume[3014228]: DEBUG oslo_concurrency.processutils [None req-39ac9f61-1f0b-469f-9896-78085d8bbeb6 None None] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix stack-volumes-lvmdriver-1" returned: 0 in 0.661s {{(pid=3014228) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Sep 15 16:01:00 datacore-PowerEdge-R740 cinder-volume[3014228]: DEBUG oslo_concurrency.processutils [None req-39ac9f61-1f0b-469f-9896-78085d8bbeb6 None None] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1 {{(pid=3014228) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Sep 15 16:01:00 datacore-PowerEdge-R740 sudo[3014658]:    stack : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/local/bin/cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1
Sep 15 16:01:00 datacore-PowerEdge-R740 sudo[3014658]: pam_unix(sudo:session): session opened for user root by (uid=0)
