-- Logs begin at Fri 2022-10-07 15:13:53 IST, end at Fri 2022-10-07 15:14:04 IST. --
Oct 07 15:13:54 datacore-PowerEdge-R740 sudo[2046680]: pam_unix(sudo:session): session closed for user root
Oct 07 15:13:54 datacore-PowerEdge-R740 cinder-volume[2046504]: DEBUG oslo_concurrency.processutils [None req-c9cfc6ac-2b68-455f-8d6b-0b495327a437 None None] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C pvs --noheadings --unit=g -o vg_name,name,size,free --separator | --nosuffix --ignoreskippedcluster" returned: 0 in 0.694s {{(pid=2046504) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Oct 07 15:13:54 datacore-PowerEdge-R740 cinder-volume[2046504]: DEBUG oslo_concurrency.processutils [None req-c9cfc6ac-2b68-455f-8d6b-0b495327a437 None None] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix stack-volumes-lvmdriver-1 {{(pid=2046504) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Oct 07 15:13:54 datacore-PowerEdge-R740 sudo[2046726]:    stack : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/local/bin/cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix stack-volumes-lvmdriver-1
Oct 07 15:13:54 datacore-PowerEdge-R740 sudo[2046726]: pam_unix(sudo:session): session opened for user root by (uid=0)
Oct 07 15:13:55 datacore-PowerEdge-R740 sudo[2046726]: pam_unix(sudo:session): session closed for user root
Oct 07 15:13:55 datacore-PowerEdge-R740 cinder-volume[2046504]: DEBUG oslo_concurrency.processutils [None req-c9cfc6ac-2b68-455f-8d6b-0b495327a437 None None] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix stack-volumes-lvmdriver-1" returned: 0 in 0.734s {{(pid=2046504) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Oct 07 15:13:55 datacore-PowerEdge-R740 cinder-volume[2046504]: DEBUG oslo_concurrency.processutils [None req-c9cfc6ac-2b68-455f-8d6b-0b495327a437 None None] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix stack-volumes-lvmdriver-1 {{(pid=2046504) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Oct 07 15:13:55 datacore-PowerEdge-R740 sudo[2046779]:    stack : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/local/bin/cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix stack-volumes-lvmdriver-1
Oct 07 15:13:55 datacore-PowerEdge-R740 sudo[2046779]: pam_unix(sudo:session): session opened for user root by (uid=0)
Oct 07 15:13:55 datacore-PowerEdge-R740 sudo[2046779]: pam_unix(sudo:session): session closed for user root
Oct 07 15:13:55 datacore-PowerEdge-R740 cinder-volume[2046504]: DEBUG oslo_concurrency.processutils [None req-c9cfc6ac-2b68-455f-8d6b-0b495327a437 None None] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix stack-volumes-lvmdriver-1" returned: 0 in 0.693s {{(pid=2046504) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Oct 07 15:13:55 datacore-PowerEdge-R740 cinder-volume[2046504]: DEBUG oslo_concurrency.processutils [None req-c9cfc6ac-2b68-455f-8d6b-0b495327a437 None None] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1 {{(pid=2046504) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Oct 07 15:13:55 datacore-PowerEdge-R740 sudo[2046816]:    stack : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/local/bin/cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1
Oct 07 15:13:55 datacore-PowerEdge-R740 sudo[2046816]: pam_unix(sudo:session): session opened for user root by (uid=0)
Oct 07 15:13:56 datacore-PowerEdge-R740 sudo[2046816]: pam_unix(sudo:session): session closed for user root
Oct 07 15:13:56 datacore-PowerEdge-R740 cinder-volume[2046504]: DEBUG oslo_concurrency.processutils [None req-c9cfc6ac-2b68-455f-8d6b-0b495327a437 None None] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1" returned: 0 in 0.663s {{(pid=2046504) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Oct 07 15:13:56 datacore-PowerEdge-R740 cinder-volume[2046504]: DEBUG oslo_concurrency.processutils [None req-c9cfc6ac-2b68-455f-8d6b-0b495327a437 None None] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o size,data_percent --separator : --nosuffix /dev/stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool {{(pid=2046504) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Oct 07 15:13:56 datacore-PowerEdge-R740 sudo[2046820]:    stack : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/local/bin/cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o size,data_percent --separator : --nosuffix /dev/stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool
Oct 07 15:13:56 datacore-PowerEdge-R740 sudo[2046820]: pam_unix(sudo:session): session opened for user root by (uid=0)
Oct 07 15:13:57 datacore-PowerEdge-R740 sudo[2046820]: pam_unix(sudo:session): session closed for user root
Oct 07 15:13:57 datacore-PowerEdge-R740 cinder-volume[2046504]: DEBUG oslo_concurrency.processutils [None req-c9cfc6ac-2b68-455f-8d6b-0b495327a437 None None] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o size,data_percent --separator : --nosuffix /dev/stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool" returned: 0 in 0.631s {{(pid=2046504) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Oct 07 15:13:57 datacore-PowerEdge-R740 cinder-volume[2046504]: DEBUG oslo_concurrency.processutils [None req-c9cfc6ac-2b68-455f-8d6b-0b495327a437 None None] Running cmd (subprocess): env LC_ALL=C lvm version {{(pid=2046504) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Oct 07 15:13:57 datacore-PowerEdge-R740 cinder-volume[2046504]: DEBUG oslo_concurrency.processutils [None req-c9cfc6ac-2b68-455f-8d6b-0b495327a437 None None] CMD "env LC_ALL=C lvm version" returned: 0 in 0.012s {{(pid=2046504) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Oct 07 15:13:57 datacore-PowerEdge-R740 cinder-volume[2046504]: DEBUG oslo_concurrency.processutils [None req-c9cfc6ac-2b68-455f-8d6b-0b495327a437 None None] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool {{(pid=2046504) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Oct 07 15:13:57 datacore-PowerEdge-R740 sudo[2046825]:    stack : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/local/bin/cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool
Oct 07 15:13:57 datacore-PowerEdge-R740 sudo[2046825]: pam_unix(sudo:session): session opened for user root by (uid=0)
Oct 07 15:13:57 datacore-PowerEdge-R740 sudo[2046825]: pam_unix(sudo:session): session closed for user root
Oct 07 15:13:57 datacore-PowerEdge-R740 cinder-volume[2046504]: DEBUG oslo_concurrency.processutils [None req-c9cfc6ac-2b68-455f-8d6b-0b495327a437 None None] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool" returned: 0 in 0.623s {{(pid=2046504) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Oct 07 15:13:57 datacore-PowerEdge-R740 cinder-volume[2046504]: INFO cinder.volume.drivers.lvm [None req-c9cfc6ac-2b68-455f-8d6b-0b495327a437 None None] Enabling LVM thin provisioning by default because a thin pool exists.
Oct 07 15:13:57 datacore-PowerEdge-R740 cinder-volume[2046504]: DEBUG oslo_concurrency.processutils [None req-c9cfc6ac-2b68-455f-8d6b-0b495327a437 None None] Running cmd (subprocess): env LC_ALL=C lvm version {{(pid=2046504) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Oct 07 15:13:57 datacore-PowerEdge-R740 cinder-volume[2046504]: DEBUG oslo_concurrency.processutils [None req-c9cfc6ac-2b68-455f-8d6b-0b495327a437 None None] CMD "env LC_ALL=C lvm version" returned: 0 in 0.015s {{(pid=2046504) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Oct 07 15:13:57 datacore-PowerEdge-R740 cinder-volume[2046504]: DEBUG oslo_concurrency.processutils [None req-c9cfc6ac-2b68-455f-8d6b-0b495327a437 None None] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool {{(pid=2046504) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Oct 07 15:13:57 datacore-PowerEdge-R740 sudo[2046830]:    stack : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/local/bin/cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool
Oct 07 15:13:57 datacore-PowerEdge-R740 sudo[2046830]: pam_unix(sudo:session): session opened for user root by (uid=0)
Oct 07 15:13:58 datacore-PowerEdge-R740 sudo[2046830]: pam_unix(sudo:session): session closed for user root
Oct 07 15:13:58 datacore-PowerEdge-R740 cinder-volume[2046504]: DEBUG oslo_concurrency.processutils [None req-c9cfc6ac-2b68-455f-8d6b-0b495327a437 None None] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool" returned: 0 in 0.653s {{(pid=2046504) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Oct 07 15:13:58 datacore-PowerEdge-R740 cinder-volume[2046504]: DEBUG cinder.volume.drivers.lvm [None req-c9cfc6ac-2b68-455f-8d6b-0b495327a437 None None] Updating volume stats {{(pid=2046504) _update_volume_stats /opt/stack/cinder/cinder/volume/drivers/lvm.py:213}}
Oct 07 15:13:58 datacore-PowerEdge-R740 cinder-volume[2046504]: DEBUG oslo_concurrency.processutils [None req-c9cfc6ac-2b68-455f-8d6b-0b495327a437 None None] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix stack-volumes-lvmdriver-1 {{(pid=2046504) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Oct 07 15:13:58 datacore-PowerEdge-R740 sudo[2046836]:    stack : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/local/bin/cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix stack-volumes-lvmdriver-1
Oct 07 15:13:58 datacore-PowerEdge-R740 sudo[2046836]: pam_unix(sudo:session): session opened for user root by (uid=0)
Oct 07 15:13:59 datacore-PowerEdge-R740 sudo[2046836]: pam_unix(sudo:session): session closed for user root
Oct 07 15:13:59 datacore-PowerEdge-R740 cinder-volume[2046504]: DEBUG oslo_concurrency.processutils [None req-c9cfc6ac-2b68-455f-8d6b-0b495327a437 None None] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix stack-volumes-lvmdriver-1" returned: 0 in 0.634s {{(pid=2046504) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Oct 07 15:13:59 datacore-PowerEdge-R740 cinder-volume[2046504]: DEBUG oslo_concurrency.processutils [None req-c9cfc6ac-2b68-455f-8d6b-0b495327a437 None None] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1 {{(pid=2046504) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Oct 07 15:13:59 datacore-PowerEdge-R740 sudo[2046851]:    stack : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/local/bin/cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1
Oct 07 15:13:59 datacore-PowerEdge-R740 sudo[2046851]: pam_unix(sudo:session): session opened for user root by (uid=0)
Oct 07 15:13:59 datacore-PowerEdge-R740 sudo[2046851]: pam_unix(sudo:session): session closed for user root
Oct 07 15:13:59 datacore-PowerEdge-R740 cinder-volume[2046504]: DEBUG oslo_concurrency.processutils [None req-c9cfc6ac-2b68-455f-8d6b-0b495327a437 None None] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1" returned: 0 in 0.620s {{(pid=2046504) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Oct 07 15:13:59 datacore-PowerEdge-R740 cinder-volume[2046504]: DEBUG oslo_concurrency.processutils [None req-c9cfc6ac-2b68-455f-8d6b-0b495327a437 None None] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o size,data_percent --separator : --nosuffix /dev/stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool {{(pid=2046504) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Oct 07 15:13:59 datacore-PowerEdge-R740 sudo[2046856]:    stack : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/local/bin/cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o size,data_percent --separator : --nosuffix /dev/stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool
Oct 07 15:13:59 datacore-PowerEdge-R740 sudo[2046856]: pam_unix(sudo:session): session opened for user root by (uid=0)
Oct 07 15:14:00 datacore-PowerEdge-R740 cinder-volume[2046297]: DEBUG dbcounter [-] [2046297] Writing DB stats cinder:SELECT=16,cinder:UPDATE=1 {{(pid=2046297) stat_writer /usr/local/lib/python3.8/dist-packages/dbcounter.py:114}}
Oct 07 15:14:00 datacore-PowerEdge-R740 sudo[2046856]: pam_unix(sudo:session): session closed for user root
Oct 07 15:14:00 datacore-PowerEdge-R740 cinder-volume[2046504]: DEBUG oslo_concurrency.processutils [None req-c9cfc6ac-2b68-455f-8d6b-0b495327a437 None None] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o size,data_percent --separator : --nosuffix /dev/stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool" returned: 0 in 0.633s {{(pid=2046504) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Oct 07 15:14:00 datacore-PowerEdge-R740 cinder-volume[2046504]: DEBUG oslo_concurrency.processutils [None req-c9cfc6ac-2b68-455f-8d6b-0b495327a437 None None] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1 {{(pid=2046504) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Oct 07 15:14:00 datacore-PowerEdge-R740 sudo[2046865]:    stack : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/local/bin/cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1
Oct 07 15:14:00 datacore-PowerEdge-R740 sudo[2046865]: pam_unix(sudo:session): session opened for user root by (uid=0)
Oct 07 15:14:00 datacore-PowerEdge-R740 sudo[2046865]: pam_unix(sudo:session): session closed for user root
Oct 07 15:14:00 datacore-PowerEdge-R740 cinder-volume[2046504]: DEBUG oslo_concurrency.processutils [None req-c9cfc6ac-2b68-455f-8d6b-0b495327a437 None None] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1" returned: 0 in 0.629s {{(pid=2046504) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Oct 07 15:14:00 datacore-PowerEdge-R740 cinder-volume[2046504]: INFO cinder.volume.driver [None req-c9cfc6ac-2b68-455f-8d6b-0b495327a437 None None] Driver hasn't implemented _init_vendor_properties()
Oct 07 15:14:00 datacore-PowerEdge-R740 cinder-volume[2046504]: DEBUG cinder.volume.driver [None req-c9cfc6ac-2b68-455f-8d6b-0b495327a437 None None] Initialized capabilities list: {'volume_backend_name': 'lvmdriver-1', 'vendor_name': 'Open Source', 'driver_version': '3.0.0', 'storage_protocol': 'iSCSI', 'pools': [{'pool_name': 'lvmdriver-1', 'total_capacity_gb': 28.5, 'free_capacity_gb': 28.5, 'reserved_percentage': 0, 'location_info': 'LVMVolumeDriver:datacore-PowerEdge-R740:stack-volumes-lvmdriver-1:thin:0', 'QoS_support': False, 'provisioned_capacity_gb': 0.0, 'max_over_subscription_ratio': '20.0', 'thin_provisioning_support': True, 'thick_provisioning_support': False, 'total_volumes': 1, 'filter_function': None, 'goodness_function': None, 'multiattach': True, 'backend_state': 'up'}], 'shared_targets': False, 'sparse_copy_volume': True, 'properties': {'thin_provisioning': {'title': 'Thin Provisioning', 'description': 'Sets thin provisioning.', 'type': 'boolean'}, 'compression': {'title': 'Compression', 'description': 'Enables compression.', 'type': 'boolean'}, 'qos': {'title': 'QoS', 'description': 'Enables QoS.', 'type': 'boolean'}, 'replication_enabled': {'title': 'Replication', 'description': 'Enables replication.', 'type': 'boolean'}}}. {{(pid=2046504) init_capabilities /opt/stack/cinder/cinder/volume/driver.py:812}}
Oct 07 15:14:00 datacore-PowerEdge-R740 cinder-volume[2046504]: DEBUG oslo_db.sqlalchemy.engines [None req-c9cfc6ac-2b68-455f-8d6b-0b495327a437 None None] MySQL server mode set to STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_ENGINE_SUBSTITUTION {{(pid=2046504) _check_effective_sql_mode /usr/local/lib/python3.8/dist-packages/oslo_db/sqlalchemy/engines.py:314}}
Oct 07 15:14:00 datacore-PowerEdge-R740 cinder-volume[2046504]: DEBUG dbcounter [-] [2046504] Writer thread running {{(pid=2046504) stat_writer /usr/local/lib/python3.8/dist-packages/dbcounter.py:99}}
Oct 07 15:14:00 datacore-PowerEdge-R740 cinder-volume[2046504]: DEBUG cinder.db.sqlalchemy.api [None req-c9cfc6ac-2b68-455f-8d6b-0b495327a437 None None] Building query based on filter {{(pid=2046504) _process_snaps_filters /opt/stack/cinder/cinder/db/sqlalchemy/api.py:3885}}
Oct 07 15:14:00 datacore-PowerEdge-R740 cinder-volume[2046504]: DEBUG cinder.image.image_utils [None req-c9cfc6ac-2b68-455f-8d6b-0b495327a437 None None] Configuration image_conversion_dir is None or the path doesn't exist. {{(pid=2046504) cleanup_temporary_file /opt/stack/cinder/cinder/image/image_utils.py:991}}
Oct 07 15:14:00 datacore-PowerEdge-R740 cinder-volume[2046504]: DEBUG cinder.volume.drivers.lvm [None req-c9cfc6ac-2b68-455f-8d6b-0b495327a437 None None] Updating volume stats {{(pid=2046504) _update_volume_stats /opt/stack/cinder/cinder/volume/drivers/lvm.py:213}}
Oct 07 15:14:00 datacore-PowerEdge-R740 cinder-volume[2046504]: DEBUG oslo_concurrency.processutils [None req-c9cfc6ac-2b68-455f-8d6b-0b495327a437 None None] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix stack-volumes-lvmdriver-1 {{(pid=2046504) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Oct 07 15:14:00 datacore-PowerEdge-R740 cinder-volume[2046504]: INFO cinder.keymgr.migration [None req-b2d8c9b8-e4a8-4a59-9bc8-beecef22cfc4 None None] Not migrating encryption keys because the ConfKeyManager is still in use.
Oct 07 15:14:00 datacore-PowerEdge-R740 sudo[2046876]:    stack : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/local/bin/cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix stack-volumes-lvmdriver-1
Oct 07 15:14:00 datacore-PowerEdge-R740 sudo[2046876]: pam_unix(sudo:session): session opened for user root by (uid=0)
Oct 07 15:14:01 datacore-PowerEdge-R740 sudo[2046876]: pam_unix(sudo:session): session closed for user root
Oct 07 15:14:01 datacore-PowerEdge-R740 cinder-volume[2046504]: DEBUG oslo_concurrency.processutils [None req-c9cfc6ac-2b68-455f-8d6b-0b495327a437 None None] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix stack-volumes-lvmdriver-1" returned: 0 in 0.621s {{(pid=2046504) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Oct 07 15:14:01 datacore-PowerEdge-R740 cinder-volume[2046504]: DEBUG oslo_concurrency.processutils [None req-c9cfc6ac-2b68-455f-8d6b-0b495327a437 None None] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1 {{(pid=2046504) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Oct 07 15:14:01 datacore-PowerEdge-R740 sudo[2046884]:    stack : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/local/bin/cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1
Oct 07 15:14:01 datacore-PowerEdge-R740 sudo[2046884]: pam_unix(sudo:session): session opened for user root by (uid=0)
Oct 07 15:14:02 datacore-PowerEdge-R740 sudo[2046884]: pam_unix(sudo:session): session closed for user root
Oct 07 15:14:02 datacore-PowerEdge-R740 cinder-volume[2046504]: DEBUG oslo_concurrency.processutils [None req-c9cfc6ac-2b68-455f-8d6b-0b495327a437 None None] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1" returned: 0 in 0.629s {{(pid=2046504) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Oct 07 15:14:02 datacore-PowerEdge-R740 cinder-volume[2046504]: DEBUG oslo_concurrency.processutils [None req-c9cfc6ac-2b68-455f-8d6b-0b495327a437 None None] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o size,data_percent --separator : --nosuffix /dev/stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool {{(pid=2046504) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Oct 07 15:14:02 datacore-PowerEdge-R740 sudo[2046894]:    stack : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/local/bin/cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o size,data_percent --separator : --nosuffix /dev/stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool
Oct 07 15:14:02 datacore-PowerEdge-R740 sudo[2046894]: pam_unix(sudo:session): session opened for user root by (uid=0)
Oct 07 15:14:02 datacore-PowerEdge-R740 sudo[2046894]: pam_unix(sudo:session): session closed for user root
Oct 07 15:14:02 datacore-PowerEdge-R740 cinder-volume[2046504]: DEBUG oslo_concurrency.processutils [None req-c9cfc6ac-2b68-455f-8d6b-0b495327a437 None None] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o size,data_percent --separator : --nosuffix /dev/stack-volumes-lvmdriver-1/stack-volumes-lvmdriver-1-pool" returned: 0 in 0.658s {{(pid=2046504) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Oct 07 15:14:02 datacore-PowerEdge-R740 cinder-volume[2046504]: DEBUG oslo_concurrency.processutils [None req-c9cfc6ac-2b68-455f-8d6b-0b495327a437 None None] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1 {{(pid=2046504) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Oct 07 15:14:02 datacore-PowerEdge-R740 sudo[2046908]:    stack : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/local/bin/cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1
Oct 07 15:14:02 datacore-PowerEdge-R740 sudo[2046908]: pam_unix(sudo:session): session opened for user root by (uid=0)
Oct 07 15:14:03 datacore-PowerEdge-R740 sudo[2046908]: pam_unix(sudo:session): session closed for user root
Oct 07 15:14:03 datacore-PowerEdge-R740 cinder-volume[2046504]: DEBUG oslo_concurrency.processutils [None req-c9cfc6ac-2b68-455f-8d6b-0b495327a437 None None] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1" returned: 0 in 0.641s {{(pid=2046504) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Oct 07 15:14:03 datacore-PowerEdge-R740 cinder-volume[2046504]: DEBUG cinder.manager [None req-c9cfc6ac-2b68-455f-8d6b-0b495327a437 None None] Notifying Schedulers of capabilities ... {{(pid=2046504) _publish_service_capabilities /opt/stack/cinder/cinder/manager.py:202}}
Oct 07 15:14:03 datacore-PowerEdge-R740 cinder-volume[2046504]: INFO cinder.volume.manager [None req-c9cfc6ac-2b68-455f-8d6b-0b495327a437 None None] Driver initialization completed successfully.
Oct 07 15:14:03 datacore-PowerEdge-R740 cinder-volume[2046504]: INFO cinder.manager [None req-c9cfc6ac-2b68-455f-8d6b-0b495327a437 None None] Initiating service 2 cleanup
Oct 07 15:14:03 datacore-PowerEdge-R740 cinder-volume[2046504]: INFO cinder.manager [None req-c9cfc6ac-2b68-455f-8d6b-0b495327a437 None None] Service 2 cleanup completed.
Oct 07 15:14:03 datacore-PowerEdge-R740 cinder-volume[2046504]: DEBUG cinder.service [None req-c9cfc6ac-2b68-455f-8d6b-0b495327a437 None None] Creating RPC server for service cinder-volume {{(pid=2046504) start /opt/stack/cinder/cinder/service.py:238}}
Oct 07 15:14:03 datacore-PowerEdge-R740 cinder-volume[2046504]: DEBUG cinder.service [None req-c9cfc6ac-2b68-455f-8d6b-0b495327a437 None None] Pinning object versions for RPC server serializer to 1.39 {{(pid=2046504) start /opt/stack/cinder/cinder/service.py:244}}
Oct 07 15:14:03 datacore-PowerEdge-R740 cinder-volume[2046504]: INFO cinder.volume.manager [None req-c9cfc6ac-2b68-455f-8d6b-0b495327a437 None None] Initializing RPC dependent components of volume driver LVMVolumeDriver (3.0.0)
Oct 07 15:14:03 datacore-PowerEdge-R740 cinder-volume[2046504]: DEBUG cinder.volume.drivers.lvm [None req-c9cfc6ac-2b68-455f-8d6b-0b495327a437 None None] Updating volume stats {{(pid=2046504) _update_volume_stats /opt/stack/cinder/cinder/volume/drivers/lvm.py:213}}
Oct 07 15:14:03 datacore-PowerEdge-R740 cinder-volume[2046504]: DEBUG oslo_concurrency.processutils [None req-c9cfc6ac-2b68-455f-8d6b-0b495327a437 None None] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix stack-volumes-lvmdriver-1 {{(pid=2046504) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Oct 07 15:14:03 datacore-PowerEdge-R740 sudo[2046932]:    stack : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/local/bin/cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix stack-volumes-lvmdriver-1
Oct 07 15:14:03 datacore-PowerEdge-R740 sudo[2046932]: pam_unix(sudo:session): session opened for user root by (uid=0)
Oct 07 15:14:04 datacore-PowerEdge-R740 sudo[2046932]: pam_unix(sudo:session): session closed for user root
Oct 07 15:14:04 datacore-PowerEdge-R740 cinder-volume[2046504]: DEBUG oslo_concurrency.processutils [None req-c9cfc6ac-2b68-455f-8d6b-0b495327a437 None None] CMD "sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C vgs --noheadings --unit=g -o name,size,free,lv_count,uuid --separator : --nosuffix stack-volumes-lvmdriver-1" returned: 0 in 0.639s {{(pid=2046504) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:422}}
Oct 07 15:14:04 datacore-PowerEdge-R740 cinder-volume[2046504]: DEBUG oslo_concurrency.processutils [None req-c9cfc6ac-2b68-455f-8d6b-0b495327a437 None None] Running cmd (subprocess): sudo cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1 {{(pid=2046504) execute /usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py:384}}
Oct 07 15:14:04 datacore-PowerEdge-R740 sudo[2046942]:    stack : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/local/bin/cinder-rootwrap /etc/cinder/rootwrap.conf env LC_ALL=C lvs --noheadings --unit=g -o vg_name,name,size --nosuffix --readonly stack-volumes-lvmdriver-1
Oct 07 15:14:04 datacore-PowerEdge-R740 sudo[2046942]: pam_unix(sudo:session): session opened for user root by (uid=0)
